package computerdatabase.Module.payrollObject

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object PayrollBorangLampiran1 {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Lampiran 1 Page")
      .get("/Report/Lampiran1Report")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
    )
      .exec(http("request_72")
        .get("/signalr/hubs")
      )
      .exec(http("request_73")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(1)
      .exec(http("request_74")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_75")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .exec(http("request_76")
        .get("/DXR.axd?r=0_2314-O3Vxm")
      )
      .exec(http("request_77")
        .get("/DXR.axd?r=0_2216-O3Vxm")
      )
      .exec(http("request_78")
        .get("/DXR.axd?r=0_2316-O3Vxm")
      )
      .pause(270.milliseconds)
      .exec(http("request_79")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_80")
        .get("/DXR.axd?r=0_2303-O3Vxm")
      )
      .exec(http("request_81")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_82")
        .post("/Lampiran1Report/ComboBoxTextDisplay")

        .formParam("objectLabel", "PayrollMonth")
        .formParam("comboBoxValue", "")
        .formParam("textBoxValue", "2021"))
      .exec(http("request_83")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "EMPLOYER_AGENCY_ID")
        .formParam("isAllSelected", "false"))
      .exec(http("request_84")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_85")
        .post("/Lampiran1Report/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "PayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "SocsoEmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "100")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyNo")
        .formParam("CustomSearchParameters[0][Value]", "")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
        .formParam("CustomSearchParameters[1][Value]", "")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", ""))
      .exec(http("request_86")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_87")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("isAllSelected", "false"))
      .exec(http("request_88")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_89")
        .post("/Lampiran1Report/CheckBoxListDisplay")

        .formParam("objectLabel", "EmployeeStatus")
        .formParam("objectSelectedIds[]", "A")
        .formParam("objectSelectedIds[]", "L")
        .formParam("objectSelectedIds[]", "I"))
      .pause(196.milliseconds)
      .exec(http("request_90")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_91")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_92")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "59")
        .formParam("objectSelectedIds[]", "82")
        .formParam("objectSelectedIds[]", "91")
        .formParam("objectSelectedIds[]", "105")
        .formParam("objectSelectedIds[]", "113")
        .formParam("objectSelectedIds[]", "124")
        .formParam("objectSelectedIds[]", "135")
        .formParam("objectSelectedIds[]", "147")
        .formParam("objectSelectedIds[]", "165")
        .formParam("objectSelectedIds[]", "186")
        .formParam("objectSelectedIds[]", "211")
        .formParam("objectSelectedIds[]", "227")
        .formParam("objectSelectedIds[]", "238")
        .formParam("objectSelectedIds[]", "249")
        .formParam("objectSelectedIds[]", "255")
        .formParam("objectSelectedIds[]", "268")
        .formParam("objectSelectedIds[]", "310")
        .formParam("objectSelectedIds[]", "311")
        .formParam("objectSelectedIds[]", "312")
        .formParam("objectSelectedIds[]", "313")
        .formParam("objectSelectedIds[]", "314")
        .formParam("objectSelectedIds[]", "315")
        .formParam("objectSelectedIds[]", "316")
        .formParam("objectSelectedIds[]", "317")
        .formParam("objectSelectedIds[]", "318")
        .formParam("objectSelectedIds[]", "319")
        .formParam("objectSelectedIds[]", "320")
        .formParam("objectSelectedIds[]", "321")
        .formParam("objectSelectedIds[]", "343")
        .formParam("objectSelectedIds[]", "344")
        .formParam("objectSelectedIds[]", "347")
        .formParam("objectSelectedIds[]", "348")
        .formParam("objectSelectedIds[]", "349")
        .formParam("objectSelectedIds[]", "350")
        .formParam("objectSelectedIds[]", "351")
        .formParam("objectSelectedIds[]", "352")
        .formParam("objectSelectedIds[]", "353")
        .formParam("objectSelectedIds[]", "354")
        .formParam("objectSelectedIds[]", "355")
        .formParam("objectSelectedIds[]", "356")
        .formParam("objectSelectedIds[]", "357")
        .formParam("objectSelectedIds[]", "379")
        .formParam("objectSelectedIds[]", "380")
        .formParam("objectSelectedIds[]", "387")
        .formParam("objectSelectedIds[]", "390")
        .formParam("objectSelectedIds[]", "393")
        .formParam("objectSelectedIds[]", "396")
        .formParam("objectSelectedIds[]", "399")
        .formParam("objectSelectedIds[]", "402")
        .formParam("objectSelectedIds[]", "405")
        .formParam("objectSelectedIds[]", "408")
        .formParam("objectSelectedIds[]", "411")
        .formParam("objectSelectedIds[]", "414")
        .formParam("objectSelectedIds[]", "417")
        .formParam("objectSelectedIds[]", "420")
        .formParam("objectSelectedIds[]", "424")
        .formParam("objectSelectedIds[]", "427")
        .formParam("objectSelectedIds[]", "430")
        .formParam("objectSelectedIds[]", "438")
        .formParam("objectSelectedIds[]", "443")
        .formParam("objectSelectedIds[]", "445")
        .formParam("objectSelectedIds[]", "446")
        .formParam("objectSelectedIds[]", "447")
        .formParam("objectSelectedIds[]", "448")
        .formParam("objectSelectedIds[]", "449")
        .formParam("objectSelectedIds[]", "450")
        .formParam("objectSelectedIds[]", "451")
        .formParam("objectSelectedIds[]", "452")
        .formParam("objectSelectedIds[]", "453")
        .formParam("objectSelectedIds[]", "454")
        .formParam("objectSelectedIds[]", "455")
        .formParam("objectSelectedIds[]", "483")
        .formParam("objectSelectedIds[]", "484")
        .formParam("objectSelectedIds[]", "485")
        .formParam("objectSelectedIds[]", "486")
        .formParam("objectSelectedIds[]", "487")
        .formParam("objectSelectedIds[]", "488")
        .formParam("objectSelectedIds[]", "489")
        .formParam("objectSelectedIds[]", "490")
        .formParam("objectSelectedIds[]", "491")
        .formParam("objectSelectedIds[]", "492")
        .formParam("objectSelectedIds[]", "493")
        .formParam("objectSelectedIds[]", "522")
        .formParam("objectSelectedIds[]", "523")
        .formParam("objectSelectedIds[]", "524")
        .formParam("objectSelectedIds[]", "525")
        .formParam("objectSelectedIds[]", "526")
        .formParam("objectSelectedIds[]", "527")
        .formParam("objectSelectedIds[]", "528")
        .formParam("objectSelectedIds[]", "529")
        .formParam("objectSelectedIds[]", "530")
        .formParam("objectSelectedIds[]", "531")
        .formParam("objectSelectedIds[]", "532")
        .formParam("objectSelectedIds[]", "561")
        .formParam("objectSelectedIds[]", "562")
        .formParam("objectSelectedIds[]", "563")
        .formParam("objectSelectedIds[]", "564")
        .formParam("objectSelectedIds[]", "565")
        .formParam("objectSelectedIds[]", "566")
        .formParam("objectSelectedIds[]", "567")
        .formParam("objectSelectedIds[]", "568")
        .formParam("objectSelectedIds[]", "569")
        .formParam("objectSelectedIds[]", "570")
        .formParam("objectSelectedIds[]", "571")
        .formParam("objectSelectedIds[]", "599")
        .formParam("objectSelectedIds[]", "600")
        .formParam("objectSelectedIds[]", "601")
        .formParam("objectSelectedIds[]", "602")
        .formParam("objectSelectedIds[]", "603")
        .formParam("objectSelectedIds[]", "604")
        .formParam("objectSelectedIds[]", "605")
        .formParam("objectSelectedIds[]", "606")
        .formParam("objectSelectedIds[]", "607")
        .formParam("objectSelectedIds[]", "608")
        .formParam("objectSelectedIds[]", "609")
        .formParam("objectSelectedIds[]", "637")
        .formParam("objectSelectedIds[]", "638")
        .formParam("objectSelectedIds[]", "639")
        .formParam("objectSelectedIds[]", "640")
        .formParam("objectSelectedIds[]", "641")
        .formParam("objectSelectedIds[]", "642")
        .formParam("objectSelectedIds[]", "643")
        .formParam("objectSelectedIds[]", "644")
        .formParam("objectSelectedIds[]", "645")
        .formParam("objectSelectedIds[]", "646")
        .formParam("objectSelectedIds[]", "647")
        .formParam("objectSelectedIds[]", "675")
        .formParam("objectSelectedIds[]", "676")
        .formParam("objectSelectedIds[]", "677")
        .formParam("objectSelectedIds[]", "678")
        .formParam("objectSelectedIds[]", "679")
        .formParam("objectSelectedIds[]", "680")
        .formParam("objectSelectedIds[]", "681")
        .formParam("objectSelectedIds[]", "682")
        .formParam("objectSelectedIds[]", "683")
        .formParam("objectSelectedIds[]", "684")
        .formParam("objectSelectedIds[]", "685")
        .formParam("objectSelectedIds[]", "718")
        .formParam("objectSelectedIds[]", "720")
        .formParam("objectSelectedIds[]", "721")
        .formParam("objectSelectedIds[]", "722")
        .formParam("objectSelectedIds[]", "723")
        .formParam("objectSelectedIds[]", "724")
        .formParam("objectSelectedIds[]", "725")
        .formParam("objectSelectedIds[]", "726")
        .formParam("objectSelectedIds[]", "727")
        .formParam("objectSelectedIds[]", "728")
        .formParam("objectSelectedIds[]", "729")
        .formParam("objectSelectedIds[]", "730")
        .formParam("objectSelectedIds[]", "758")
        .formParam("objectSelectedIds[]", "759")
        .formParam("objectSelectedIds[]", "760")
        .formParam("objectSelectedIds[]", "761")
        .formParam("objectSelectedIds[]", "762")
        .formParam("objectSelectedIds[]", "763")
        .formParam("objectSelectedIds[]", "764")
        .formParam("objectSelectedIds[]", "765")
        .formParam("objectSelectedIds[]", "766")
        .formParam("objectSelectedIds[]", "767")
        .formParam("objectSelectedIds[]", "768")
        .formParam("objectSelectedIds[]", "796")
        .formParam("objectSelectedIds[]", "797")
        .formParam("objectSelectedIds[]", "798")
        .formParam("objectSelectedIds[]", "799")
        .formParam("objectSelectedIds[]", "800")
        .formParam("objectSelectedIds[]", "801")
        .formParam("objectSelectedIds[]", "802")
        .formParam("objectSelectedIds[]", "803")
        .formParam("objectSelectedIds[]", "804")
        .formParam("objectSelectedIds[]", "805")
        .formParam("objectSelectedIds[]", "806")
        .formParam("objectSelectedIds[]", "834")
        .formParam("objectSelectedIds[]", "835")
        .formParam("objectSelectedIds[]", "836")
        .formParam("objectSelectedIds[]", "837")
        .formParam("objectSelectedIds[]", "838")
        .formParam("objectSelectedIds[]", "839")
        .formParam("objectSelectedIds[]", "840")
        .formParam("objectSelectedIds[]", "841")
        .formParam("objectSelectedIds[]", "842")
        .formParam("objectSelectedIds[]", "843")
        .formParam("objectSelectedIds[]", "844")
        .formParam("objectSelectedIds[]", "872")
        .formParam("objectSelectedIds[]", "873")
        .formParam("objectSelectedIds[]", "874")
        .formParam("objectSelectedIds[]", "875")
        .formParam("objectSelectedIds[]", "876")
        .formParam("objectSelectedIds[]", "877")
        .formParam("objectSelectedIds[]", "878")
        .formParam("objectSelectedIds[]", "879")
        .formParam("objectSelectedIds[]", "880")
        .formParam("objectSelectedIds[]", "881")
        .formParam("objectSelectedIds[]", "882")
        .formParam("objectSelectedIds[]", "910")
        .formParam("objectSelectedIds[]", "911")
        .formParam("objectSelectedIds[]", "912")
        .formParam("objectSelectedIds[]", "913")
        .formParam("objectSelectedIds[]", "914")
        .formParam("objectSelectedIds[]", "915")
        .formParam("objectSelectedIds[]", "916")
        .formParam("objectSelectedIds[]", "917")
        .formParam("objectSelectedIds[]", "918")
        .formParam("objectSelectedIds[]", "919")
        .formParam("objectSelectedIds[]", "920")
        .formParam("objectSelectedIds[]", "948")
        .formParam("objectSelectedIds[]", "949")
        .formParam("objectSelectedIds[]", "950")
        .formParam("objectSelectedIds[]", "951")
        .formParam("objectSelectedIds[]", "952")
        .formParam("objectSelectedIds[]", "953")
        .formParam("objectSelectedIds[]", "954")
        .formParam("objectSelectedIds[]", "955")
        .formParam("objectSelectedIds[]", "956")
        .formParam("objectSelectedIds[]", "957")
        .formParam("objectSelectedIds[]", "958")
        .formParam("objectSelectedIds[]", "986")
        .formParam("objectSelectedIds[]", "987")
        .formParam("objectSelectedIds[]", "988")
        .formParam("objectSelectedIds[]", "989")
        .formParam("objectSelectedIds[]", "990")
        .formParam("objectSelectedIds[]", "991")
        .formParam("objectSelectedIds[]", "992")
        .formParam("objectSelectedIds[]", "993")
        .formParam("objectSelectedIds[]", "994")
        .formParam("objectSelectedIds[]", "995")
        .formParam("objectSelectedIds[]", "996")
        .formParam("objectSelectedIds[]", "1029")
        .formParam("objectSelectedIds[]", "1030")
        .formParam("objectSelectedIds[]", "1031")
        .formParam("isAllSelected", "true"))
      .exec(http("request_93")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_94")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622533209100")
      )
      .pause(2)
      .exec(http("request_95")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FReport%2FLampiran1Report&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._fwbcqb&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=41252")
      )
      .exec(http("request_96")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=BXQHuQXu%2B2kUAdE5J93lXO5EE4TH9f%2BGLfqCGmgQscxzmh9l%2B4%2Fe%2Bb7dVnwbfE1JOKAMrBAzk3QawBMzBBU2Q%2BjLhpkBSVNMFQQphl8%2BXhqdXH0UwvyxRTKsihUkipam1bDUh5do6cddNGGrBlVh79V%2BKg2JSv8ltJ%2B0PJCoteg%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622533209101")
      )
      .pause(3)
      .exec(http("request_97")
        .get("/DXR.axd?r=0_2223-O3Vxm")
      )
      .pause(903.milliseconds)
      .exec(http("request_98")
        .post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")

        .formParam("DXCallbackName", "EmployerAgencyNo_DDD_gv")
        .formParam("__DXCallbackArgument", """c0:KV|128;["79","8","32","18","71","11","14","6","73","30","3","19","23","27","36","42","63","57","44","46","38","59","50","53","65","68"];FR|1;0;GB|32;14|CUSTOMCALLBACK12|GLP_AC|2;79;;""")
        .formParam("EmployerAgencyNo$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;79&quot;,&quot;8&quot;,&quot;32&quot;,&quot;18&quot;,&quot;71&quot;,&quot;11&quot;,&quot;14&quot;,&quot;6&quot;,&quot;73&quot;,&quot;30&quot;,&quot;3&quot;,&quot;19&quot;,&quot;23&quot;,&quot;27&quot;,&quot;36&quot;,&quot;42&quot;,&quot;63&quot;,&quot;57&quot;,&quot;44&quot;,&quot;46&quot;,&quot;38&quot;,&quot;59&quot;,&quot;50&quot;,&quot;53&quot;,&quot;65&quot;,&quot;68&quot;],&quot;callbackState&quot;:&quot;EVupuM7sQz54gqLpBVpYl6JdGr2vnoSY/QxYNYXEAl8IwoLhGf4LJO1EOXb8X51xiSZ6rfTYEaJCVOnzWAT4eeXoZOxdxKq7/aHr023na6K/iUzq+u89hHTscQhqINRnE8Lm2rkNXQ6rDxqa6LQWmRFiw3Y1tKXTNDmrVOB/++uxs3vIBXIFgINpbgHUW9nkYlI6fJ9xM0Aul4otZ1R7zhWkttLvvy2335MQKGtjBbliFZ8XYrwSyPyYOyqQSa6odl95KFPzjvoj65w7CHZxqn5FmdZ7PXqBLeE5Gm9PLrBK2CwnNkWsYJGIIOVN2lEVXkW1+7CPwJAIAfaK3Gkt9b1X9wzZpVlUyV9vnzEfDQJE2wLLadSxcdXiUeApqmNMobYdx73InefPD10VponOVbCHE13ZvW9eObGMvTIZCBXWUfMgW7spEJt0+p8+FOWh&quot;,&quot;focusedRow&quot;:0,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:&quot;79&quot;}")
        .formParam("EmployerAgencyNo$DDD$gv$DXFREditorcol0", "")
        .formParam("EmployerAgencyNo$DDD$gv$DXFREditorcol1", "")
        .formParam("EmployerAgencyNo$DDD$gv$DXFREditorcol2", "")
        .formParam("DXMVCEditorsValues", """{"EmployerAgencyNo_DDD_gv_DXFREditorcol0":null,"EmployerAgencyNo_DDD_gv_DXFREditorcol1":null,"EmployerAgencyNo_DDD_gv_DXFREditorcol2":null,"EmployerAgencyNo":null,"PayrollMonth_DDD_L":[],"PayrollMonth":null,"PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":["59","82","91","105","113","124","135","147","165","186","211","227","238","249","255","268","310","311","312","313","314","315","316","317","318","319","320","321","343","344","347","348","349","350","351","352","353","354","355","356","357","379","380","387","390","393","396","399","402","405","408","411","414","417","420","424","427","430","438","443","445","446","447","448","449","450","451","452","453","454","455","483","484","485","486","487","488","489","490","491","492","493","522","523","524","525","526","527","528","529","530","531","532","561","562","563","564","565","566","567","568","569","570","571","599","600","601","602","603","604","605","606","607","608","609","637","638","639","640","641","642","643","644","645","646","647","675","676","677","678","679","680","681","682","683","684","685","718","720","721","722","723","724","725","726","727","728","729","730","758","759","760","761","762","763","764","765","766","767","768","796","797","798","799","800","801","802","803","804","805","806","834","835","836","837","838","839","840","841","842","843","844","872","873","874","875","876","877","878","879","880","881","882","910","911","912","913","914","915","916","917","918","919","920","948","949","950","951","952","953","954","955","956","957","958","986","987","988","989","990","991","992","993","994","995","996","1029","1030","1031"],"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null}""")
        .formParam("EmployerAgencyNo$State", "{&quot;rawValue&quot;:&quot;ARC&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:[&quot;79&quot;]}")
        .formParam("EmployerAgencyNo", "ARC")
        .formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"EmployerAgencyNo","Label":"EMPLOYER_AGENCY_ID","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":{"Id":1,"Title":"Mandatory Selection"},"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"AGENCY_NO","ValueField":"ID","FilterField":null,"FilterFieldList":[],"DatasourceName":"SocsoEmployerAgencyNo","DisplayFormatString":null,"SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"LOCATION_CODE","Label":"Company","Width":90,"ColumnDisplayFormatString":null},{"Name":"AGENCY_NO","Label":"EmployerAgencyNo","Width":150,"ColumnDisplayFormatString":null},{"Name":"AGENCY_NAME","Label":"Description","Width":250,"ColumnDisplayFormatString":null}],"CascadeControl":"PayPeriod","LoadOnDemand":false,"SelectAllMode":false,"DefaultSelectAll":false,"IsMultiSelection":false,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyNo")
        .formParam("CustomSearchParameters[0][Value]", "")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
        .formParam("CustomSearchParameters[1][Value]", "")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[3][Value]", "59,82,91,105,113,124,135,147,165,186,211,227,238,249,255,268,310,311,312,313,314,315,316,317,318,319,320,321,343,344,347,348,349,350,351,352,353,354,355,356,357,379,380,387,390,393,396,399,402,405,408,411,414,417,420,424,427,430,438,443,445,446,447,448,449,450,451,452,453,454,455,483,484,485,486,487,488,489,490,491,492,493,522,523,524,525,526,527,528,529,530,531,532,561,562,563,564,565,566,567,568,569,570,571,599,600,601,602,603,604,605,606,607,608,609,637,638,639,640,641,642,643,644,645,646,647,675,676,677,678,679,680,681,682,683,684,685,718,720,721,722,723,724,725,726,727,728,729,730,758,759,760,761,762,763,764,765,766,767,768,796,797,798,799,800,801,802,803,804,805,806,834,835,836,837,838,839,840,841,842,843,844,872,873,874,875,876,877,878,879,880,881,882,910,911,912,913,914,915,916,917,918,919,920,948,949,950,951,952,953,954,955,956,957,958,986,987,988,989,990,991,992,993,994,995,996,1029,1030,1031")
        .formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[4][Value]", "A,L,I")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", ""))
      .exec(http("request_99")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_100")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "EMPLOYER_AGENCY_ID")
        .formParam("objectSelectedIds[]", "79")
        .formParam("isAllSelected", "false"))
      .exec(http("request_101")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_102")
        .post("/Lampiran1Report/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "PayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "SocsoEmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "100")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyNo")
        .formParam("CustomSearchParameters[0][Value]", "79")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
        .formParam("CustomSearchParameters[1][Value]", "")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[3][Value]", "59,82,91,105,113,124,135,147,165,186,211,227,238,249,255,268,310,311,312,313,314,315,316,317,318,319,320,321,343,344,347,348,349,350,351,352,353,354,355,356,357,379,380,387,390,393,396,399,402,405,408,411,414,417,420,424,427,430,438,443,445,446,447,448,449,450,451,452,453,454,455,483,484,485,486,487,488,489,490,491,492,493,522,523,524,525,526,527,528,529,530,531,532,561,562,563,564,565,566,567,568,569,570,571,599,600,601,602,603,604,605,606,607,608,609,637,638,639,640,641,642,643,644,645,646,647,675,676,677,678,679,680,681,682,683,684,685,718,720,721,722,723,724,725,726,727,728,729,730,758,759,760,761,762,763,764,765,766,767,768,796,797,798,799,800,801,802,803,804,805,806,834,835,836,837,838,839,840,841,842,843,844,872,873,874,875,876,877,878,879,880,881,882,910,911,912,913,914,915,916,917,918,919,920,948,949,950,951,952,953,954,955,956,957,958,986,987,988,989,990,991,992,993,994,995,996,1029,1030,1031")
        .formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[4][Value]", "A,L,I")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", ""))
      .exec(http("request_103")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_104")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "268")
        .formParam("objectSelectedIds[]", "347")
        .formParam("objectSelectedIds[]", "348")
        .formParam("objectSelectedIds[]", "349")
        .formParam("objectSelectedIds[]", "350")
        .formParam("objectSelectedIds[]", "351")
        .formParam("objectSelectedIds[]", "352")
        .formParam("objectSelectedIds[]", "353")
        .formParam("objectSelectedIds[]", "354")
        .formParam("objectSelectedIds[]", "355")
        .formParam("objectSelectedIds[]", "356")
        .formParam("objectSelectedIds[]", "357")
        .formParam("objectSelectedIds[]", "379")
        .formParam("objectSelectedIds[]", "380")
        .formParam("objectSelectedIds[]", "438")
        .formParam("isAllSelected", "true"))
      .pause(2)
      .exec(http("request_105")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_106")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_107")
        .post("/Lampiran1Report/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "PayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "SocsoEmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "100")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyNo")
        .formParam("CustomSearchParameters[0][Value]", "79")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
        .formParam("CustomSearchParameters[1][Value]", "5")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[3][Value]", "268,347,348,349,350,351,352,353,354,355,356,357,379,380,438")
        .formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[4][Value]", "A,L,I")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", ""))
      .exec(http("request_108")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_109")
        .post("/Lampiran1Report/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "350")
        .formParam("isAllSelected", "true"))
      .exec(http("request_110")
        .post("/Lampiran1Report/ComboBoxTextDisplay")

        .formParam("objectLabel", "PayrollMonth")
        .formParam("comboBoxValue", "5")
        .formParam("textBoxValue", "2021"))
      .pause(2)
      .exec(http("request_111")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_112")
        .post("/Report/GenerateXtraReport")

        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyNo")
        .formParam("CustomSearchParameters[0][Value]", "79")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
        .formParam("CustomSearchParameters[1][Value]", "5")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[3][Value]", "350")
        .formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[4][Value]", "A,L,I")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", "")
        .formParam("ReportObjectTypeName", "Reports.Payroll.RPT_PAY_LAMPIRAN1"))
      .pause(171.milliseconds)
      .exec(http("request_113")
        .get("/DXR.axd?r=24_367-N3Vxm")
      )
      .pause(147.milliseconds)
      .exec(http("request_114")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "startBuild")
        .formParam("arg", "%7B%22reportId%22%3A%22ed3ba549f41a4ca2b3594db76fd4a9b6%22%2C%22reportUrl%22%3A%22%22%2C%22drillDownKeys%22%3A%5B%5D%2C%22sortingState%22%3A%5B%5D%2C%22timeZoneOffset%22%3A480%2C%22parameters%22%3A%5B%5D%7D"))
      .pause(390.milliseconds)
      .exec(http("request_115")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getBuildStatus")
        .formParam("arg", "%7B%22documentId%22%3A%22640561edada34dc5a79e13b95516e5cd%22%2C%22timeOut%22%3A120000%7D"))
      .pause(287.milliseconds)
      .exec(http("request_116")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getBuildStatus")
        .formParam("arg", "%7B%22documentId%22%3A%22640561edada34dc5a79e13b95516e5cd%22%2C%22timeOut%22%3A120000%7D"))
      .exec(http("request_117")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getDocumentData")
        .formParam("arg", "640561edada34dc5a79e13b95516e5cd"))

      /*	.exec(http("request_118")
          .get("/Report/DXXRDV.axd?actionKey=getPage&unifier=811eb223-e213-06ad-e667-094d19d30fea&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%22640561edada34dc5a79e13b95516e5cd%22%2C%22resolution%22%3A96%7D")
          )*/


      .exec(http("request_119")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getBrickMap")
        .formParam("arg", "%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%22640561edada34dc5a79e13b95516e5cd%22%7D"))

      .pause(12)
  }

  def logout = {
    exec(http("Logout Submission")
      .post("/Account/LogOff")

      .formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css")
      .check(status.is(302)))
      .exec(http("Login After Logout")
        .get("/Account/Login")
      )
      .exec(http("request_123")
        .get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
      )
      .exec(http("request_124")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_125")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
      )
      .exec(http("request_126")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_127")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
      )
      .exec(http("request_128")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_129")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }

}
