package computerdatabase.Module.payrollObject

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object PayrollBorangPTPTN {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Borang PTPTN Page")
			.get("/Report/PTPTNReport")
			.check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
			)
		.exec(http("request_72")
			.get("/Content/fonts/icomoon.ttf?5vru0d")
			)
		.pause(796.milliseconds)
		.exec(http("request_73")
			.get("/Scripts/MasterDevExBundle?v=0Nfn5KbcdrNt5eTp8R1rjNA5IlQgPjvDQ2MUmQSG31o1")
			)
		.exec(http("request_74")
			.get("/signalr/hubs")
			)
		.exec(http("request_75")
			.get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
			)
		.exec(http("request_76")
			.get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
			)
		.exec(http("request_77")
			.get("/DXR.axd?r=0_2314-O3Vxm")
			)
		.exec(http("request_78")
			.get("/DXR.axd?r=0_2216-O3Vxm")
			)
		.exec(http("request_79")
			.get("/DXR.axd?r=0_2316-O3Vxm")
			)
		.pause(227.milliseconds)
		.exec(http("request_80")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_81")
			.get("/DXR.axd?r=0_2303-O3Vxm"))
		.exec(http("request_82")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "EMPLOYER_AGENCY_ID")
			.formParam("comboBoxValue", ""))
		.exec(http("request_83")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_84")
			.post("/PTPTNReport/ComboBoxTextDisplay")
			
			.formParam("objectLabel", "PayrollMonth")
			.formParam("comboBoxValue", "6")
			.formParam("textBoxValue", "2021"))
		.exec(http("request_85")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_86")
			.post("/PTPTNReport/GetCascadeChildDropdown")
			
			.formParam("criteriaObject[Type]", "CascadeComboBox")
			.formParam("criteriaObject[Name]", "PayPeriod")
			.formParam("criteriaObject[Label]", "PayPeriod")
			.formParam("criteriaObject[GroupId]", "1")
			.formParam("criteriaObject[IsRequired]", "False")
			.formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyPTPTN")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "PtptnEmployerAgencyNo")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
			.formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
			.formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "50")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
			.formParam("ParentId", "")
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "")
			.formParam("CustomSearchParameters[15][Name]", "ChequeNo")
			.formParam("CustomSearchParameters[15][Value]", "")
			.formParam("CustomSearchParameters[16][Name]", "IssuingBank")
			.formParam("CustomSearchParameters[16][Value]", "")
			.formParam("CustomSearchParameters[17][Name]", "ChequeDate")
			.formParam("CustomSearchParameters[17][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[18][Name]", "DepositDate")
			.formParam("CustomSearchParameters[18][Value]", "2021/06/01"))
		.exec(http("request_87")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_88")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("isAllSelected", "false"))
		.exec(http("request_89")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_90")
			.post("/PTPTNReport/CheckBoxListDisplay")
			
			.formParam("objectLabel", "EmployeeStatus")
			.formParam("objectSelectedIds[]", "A")
			.formParam("objectSelectedIds[]", "L")
			.formParam("objectSelectedIds[]", "I"))
		.exec(http("request_91")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_92")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "PayMode")
			.formParam("comboBoxValue", "Q"))
		.exec(http("request_93")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_94")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "IssuingBank")
			.formParam("comboBoxValue", ""))
		.pause(141.milliseconds)
		.exec(http("request_95")
			.get("/DXR.axd?r=0_2303-O3Vxm"))
		.exec(http("request_96")
			.get("/Notifications/GetNotificationCounts")
			)
		.exec(http("request_97")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_98")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("objectSelectedIds[]", "315")
			.formParam("objectSelectedIds[]", "351")
			.formParam("objectSelectedIds[]", "449")
			.formParam("objectSelectedIds[]", "487")
			.formParam("objectSelectedIds[]", "526")
			.formParam("objectSelectedIds[]", "565")
			.formParam("objectSelectedIds[]", "603")
			.formParam("objectSelectedIds[]", "641")
			.formParam("objectSelectedIds[]", "679")
			.formParam("objectSelectedIds[]", "724")
			.formParam("objectSelectedIds[]", "762")
			.formParam("objectSelectedIds[]", "800")
			.formParam("objectSelectedIds[]", "838")
			.formParam("objectSelectedIds[]", "876")
			.formParam("objectSelectedIds[]", "914")
			.formParam("objectSelectedIds[]", "952")
			.formParam("objectSelectedIds[]", "990")
			.formParam("isAllSelected", "true"))
		.exec(http("request_99")
			.get("/Notifications/GetNotificationUserId")
			)
		.exec(http("request_100")
			.get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622532855881")
			)
		.pause(1)
		.exec(http("request_101")
			.get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=6eEeKJJU3NRGiyRmhZxbBEeKv9mUI5cnvFDaDGOkyJnhyvwdiPPqTR0BxITerZcfw33ujJIFCeofeL%2Bxb33IXgYSuOK4RauyLAcYcD2ieoyhJYQghaVIYsJooEvElZjsgEM5pyMDt6NxIxPhbeRAMEgpTmfW33LLBidvShT6Yao%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622532855882")
			)
		.pause(1)
		.exec(http("request_102")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_103")
			.get("/DXR.axd?r=0_2303-O3Vxm"))
		.exec(http("request_104")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "EMPLOYER_AGENCY_ID")
			.formParam("comboBoxValue", "135"))
		.exec(http("request_105")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_106")
			.get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FReport%2FPTPTNReport&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._gweun2&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=80149")
			)
		.exec(http("request_107")
			.post("/PTPTNReport/GetCascadeChildDropdown")
			
			.formParam("criteriaObject[Type]", "CascadeComboBox")
			.formParam("criteriaObject[Name]", "PayPeriod")
			.formParam("criteriaObject[Label]", "PayPeriod")
			.formParam("criteriaObject[GroupId]", "1")
			.formParam("criteriaObject[IsRequired]", "False")
			.formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyPTPTN")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "PtptnEmployerAgencyNo")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
			.formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
			.formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "50")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
			.formParam("ParentId", "")
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "135")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "315,351,449,487,526,565,603,641,679,724,762,800,838,876,914,952,990")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "Q")
			.formParam("CustomSearchParameters[15][Name]", "ChequeNo")
			.formParam("CustomSearchParameters[15][Value]", "")
			.formParam("CustomSearchParameters[16][Name]", "IssuingBank")
			.formParam("CustomSearchParameters[16][Value]", "")
			.formParam("CustomSearchParameters[17][Name]", "ChequeDate")
			.formParam("CustomSearchParameters[17][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[18][Name]", "DepositDate")
			.formParam("CustomSearchParameters[18][Value]", "2021/06/01"))
		.exec(http("request_108")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_109")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("objectSelectedIds[]", "762")
			.formParam("isAllSelected", "true"))
		.pause(3)
		.exec(http("request_110")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_111")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "PayMode")
			.formParam("comboBoxValue", "E"))
		.exec(http("request_112")
			.get("/Account/VerifyAccess")
			)
		.exec(http("request_113")
			.get("/Report/LoadCriteriaByPayMode?selectedPayMode=E")
			)
		.pause(164.milliseconds)
		.exec(http("request_114")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_115")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "EMPLOYER_AGENCY_ID")
			.formParam("comboBoxValue", ""))
		.exec(http("request_116")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_117")
			.post("/PTPTNReport/ComboBoxTextDisplay")
			
			.formParam("objectLabel", "PayrollMonth")
			.formParam("comboBoxValue", "6")
			.formParam("textBoxValue", "2021"))
		.exec(http("request_118")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_119")
			.post("/PTPTNReport/GetCascadeChildDropdown")
			
			.formParam("criteriaObject[Type]", "CascadeComboBox")
			.formParam("criteriaObject[Name]", "PayPeriod")
			.formParam("criteriaObject[Label]", "PayPeriod")
			.formParam("criteriaObject[GroupId]", "1")
			.formParam("criteriaObject[IsRequired]", "False")
			.formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyPTPTN")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "PtptnEmployerAgencyNo")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonth")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthTextBox")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
			.formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
			.formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "50")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
			.formParam("ParentId", "")
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "")
			.formParam("CustomSearchParameters[15][Name]", "TransferDate")
			.formParam("CustomSearchParameters[15][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[16][Name]", "EftRefNo")
			.formParam("CustomSearchParameters[16][Value]", ""))
		.exec(http("request_120")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_121")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("isAllSelected", "false"))
		.exec(http("request_122")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_123")
			.post("/PTPTNReport/CheckBoxListDisplay")
			
			.formParam("objectLabel", "EmployeeStatus")
			.formParam("objectSelectedIds[]", "A")
			.formParam("objectSelectedIds[]", "L")
			.formParam("objectSelectedIds[]", "I"))
		.exec(http("request_124")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_125")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "PayMode")
			.formParam("comboBoxValue", "Q"))
		.exec(http("request_126")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_127")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_128")
			.post("/PTPTNReport/ComboBoxTextDisplay")
			
			.formParam("objectLabel", "PayrollMonth")
			.formParam("comboBoxValue", "6")
			.formParam("textBoxValue", "2021"))
		.exec(http("request_129")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_130")
			.get("/DXR.axd?r=0_2303-O3Vxm"))
		.exec(http("request_131")
			.post("/PTPTNReport/ComboBoxTextDisplay")
			
			.formParam("objectLabel", "PayrollMonth")
			.formParam("comboBoxValue", "6")
			.formParam("textBoxValue", "2021"))
		.exec(http("request_132")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_133")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("isAllSelected", "false"))
		.exec(http("request_134")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_135")
			.post("/PTPTNReport/CheckBoxListDisplay")
			
			.formParam("objectLabel", "EmployeeStatus")
			.formParam("objectSelectedIds[]", "A")
			.formParam("objectSelectedIds[]", "L")
			.formParam("objectSelectedIds[]", "I"))
		.exec(http("request_136")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_137")
			.post("/PTPTNReport/OrganizationUnitsDisplay")
			
			.formParam("objectLabel", "Organization"))
		.exec(http("request_138")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "EMPLOYER_AGENCY_ID")
			.formParam("comboBoxValue", "135"))
		.exec(http("request_139")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_140")
			.post("/PTPTNReport/SearchableDropDownListDisplay")
			
			.formParam("objectLabel", "Category")
			.formParam("isAllSelected", "false"))
		.exec(http("request_141")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_142")
			.post("/PTPTNReport/SearchableDropDownListDisplay")
			
			.formParam("objectLabel", "Grade")
			.formParam("isAllSelected", "false"))
		.exec(http("request_143")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_144")
			.post("/PTPTNReport/SearchableDropDownListDisplay")
			
			.formParam("objectLabel", "Employee")
			.formParam("isAllSelected", "false"))
		.exec(http("request_145")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_146")
			.post("/PTPTNReport/DateRangeDisplay")
			
			.formParam("objectLabel", "HireDate")
			.formParam("dateFrom", "From")
			.formParam("dateTo", "To"))
		.exec(http("request_147")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_148")
			.post("/PTPTNReport/DateRangeDisplay")
			
			.formParam("objectLabel", "TerminationDate")
			.formParam("dateFrom", "From")
			.formParam("dateTo", "To"))
		.exec(http("request_149")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_150")
			.post("/PTPTNReport/ComboBoxDisplay")
			
			.formParam("objectLabel", "PayMode")
			.formParam("comboBoxValue", "E"))
		.exec(http("request_151")
			.post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")
			
			.formParam("DXCallbackName", "PayPeriod_DDD_gv")
			.formParam("__DXCallbackArgument", "c0:KV|2;[];FR|2;-1;GB|27;13|SELECTROWSKEY4|true3|762;")
			.formParam("PayPeriod$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[],&quot;callbackState&quot;:&quot;jaPhmB38UeCwDwohMqi2Szepg6w/ozz6Nhx2CBHD6zx03+saatfLMXuN6kyhdSQMkJkAdyeo8s/8kL3UMblYIFnDMwf5IHPwfuvavsnhjnXAShNFKNNiplFbB38AsDe50SKcGG3irkitFBvL/cKHGJx8QiCy9atpjn0wNuoVki3nHO2AGmBdlP2gAzDXC4Ab29gq1eubiFec6hHGQE65AAAE9a/qIdbw50LjJ6srxi2omqSAortcbqlWLX9GVaXdI2pOOKWGYTMgJwFdleNuKCftp2yY0hTSp5DuAC+rp4rH9rlh+1urPSJ4nQTQNG1AIM3vNxdThUE4d5/09BnPKKekgaARhg5kcBkIBxt4/WMYnQXd+3v5Gf4FJhFNK4me10AaeF7UCeLIL6EbduVFkrdpVMzi0y0tl2fPUg99fsFh40wl9azG+iD0JBrd1qNR&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
			.formParam("PayPeriod$DDD$gv$DXFREditorcol1", "")
			.formParam("PayPeriod$DDD$gv$DXFREditorcol2", "")
			.formParam("DXMVCEditorsValues", """{"EmployerAgencyPTPTN_DDD_L":["135"],"EmployerAgencyPTPTN":"135","PayrollMonth_DDD_L":["6"],"PayrollMonth":"6","PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"PaymentModePtptn_DDD_L":["E"],"PaymentModePtptn":"E","TransferDate":new Date(2021,5,1),"EftRefNo":null}""")
			.formParam("PayPeriod$State", "{&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:null}")
			.formParam("PayPeriod", "Please Select")
			.formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"PayPeriod","Label":"PayPeriod","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":null,"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"PAY_PERIOD_DESCRIPTION","ValueField":"ID","FilterField":null,"FilterFieldList":[{"ParameterName":"EmployerAgencyPTPTN","FilterField":"LOCATION_ID","FilterOperator":0,"TargetDatasourceName":"PtptnEmployerAgencyNo","TargetDatasourceProperty":"ID"},{"ParameterName":"PayrollMonth","FilterField":"PAYROLL_MONTH","FilterOperator":0,"TargetDatasourceName":null,"TargetDatasourceProperty":null},{"ParameterName":"PayrollMonthTextBox","FilterField":"PAYROLL_YEAR","FilterOperator":0,"TargetDatasourceName":null,"TargetDatasourceProperty":null}],"DatasourceName":"PayPeriods","DisplayFormatString":"{0}","SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"PAY_PERIOD_DESCRIPTION","Label":"PayPeriod","Width":250,"ColumnDisplayFormatString":null},{"Name":"COMPANY.LOCATION_CODE","Label":"Company","Width":50,"ColumnDisplayFormatString":null}],"CascadeControl":null,"LoadOnDemand":true,"SelectAllMode":true,"DefaultSelectAll":true,"IsMultiSelection":true,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
			.formParam("ParentId", "")
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "135")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "Q")
			.formParam("CustomSearchParameters[15][Name]", "TransferDate")
			.formParam("CustomSearchParameters[15][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[16][Name]", "EftRefNo")
			.formParam("CustomSearchParameters[16][Value]", ""))
		.exec(http("request_152")
			.post("/Criteria/SearchableDropDownListGridLookupPartial?criteriaObjectInString=%7B%22Type%22%3A%22SearchableDropDownList%22%2C%22Name%22%3A%22Grade%22%2C%22Label%22%3A%22Grade%22%2C%22DefaultValue%22%3Anull%2C%22DefaultDate%22%3Anull%2C%22DefaultDateRangeFrom%22%3Anull%2C%22DefaultDateRangeTo%22%3Anull%2C%22Value%22%3Anull%2C%22GroupId%22%3A2%2C%22IsRequired%22%3Afalse%2C%22Group%22%3Anull%2C%22DropDownListProperties%22%3A%7B%22TextField%22%3A%22GRADE_DESCRIPTION%22%2C%22ValueField%22%3A%22GRADE_CODE%22%2C%22FilterField%22%3Anull%2C%22DatasourceName%22%3A%22Grades%22%2C%22DisplayFormatString%22%3Anull%2C%22SourceFrom%22%3A0%2C%22DefaultIndex%22%3Anull%2C%22SelectedIndexChangedJsCallBack%22%3Anull%2C%22ColumnsList%22%3A%5B%7B%22Name%22%3A%22GRADE_DESCRIPTION%22%2C%22Label%22%3A%22Description%22%2C%22Width%22%3A250%2C%22ColumnDisplayFormatString%22%3Anull%7D%5D%2C%22IsMultiSelection%22%3Atrue%2C%22DefaultValues%22%3Anull%2C%22LoadOnDemand%22%3Afalse%2C%22SelectAllMode%22%3Atrue%2C%22DefaultSelectAll%22%3Afalse%2C%22CascadeControl%22%3Anull%2C%22DatasourceParameters%22%3Anull%2C%22IsWrapText%22%3Afalse%7D%2C%22CascadeDropDownListProperties%22%3Anull%2C%22ChildDropDownListProperties%22%3Anull%2C%22CheckListProperties%22%3Anull%2C%22DefaultIndex%22%3Anull%2C%22IsAddLabel%22%3Afalse%2C%22IsChecked%22%3Afalse%2C%22Caption%22%3Anull%2C%22CheckedChangedJsCallBack%22%3Anull%2C%22MaxLength%22%3A0%2C%22DisplayFormatString%22%3Anull%2C%22NullText%22%3Anull%2C%22ShowIncrementButtons%22%3Afalse%2C%22Page%22%3A0%2C%22CascadeControl%22%3Anull%2C%22ValueFieldDelimiter%22%3Anull%2C%22DownloadBy%22%3Anull%2C%22InitJsCallBack%22%3Anull%2C%22MultiValueDelimiter%22%3Anull%2C%22DefaultValueTo%22%3Anull%7D")
			
			.formParam("DXCallbackName", "Grade_DDD_gv")
			.formParam("__DXCallbackArgument", """c0:KV|543;["1","2","2A","2B","3A","3B","4A","4AII","4A3","4B","4C","4D","4E","5A","5B","5C","6A","6B","6C","6D","6E","7A","7B","7C","7D","7E","7F","7G","7I","A","5","N14","JG8","JG9","N02","N01","N10","JG12","G12","B","C1","C2","C3","C4","GM12","10","N15","11","N16","E1","AG","E2","SM","M","E3","E4","NE","E5","E6","JG6","EXAN","EXAH","EXCS","EXDO","EXNU","G1","G10","G2","G3","G4","G5","G6","G7","G8","G9","N05","JG14","G14","M1","M2","M3","4","JG10","MG1","MG2","MG3","MG4","8","JG2","NEAN","NEAH","NECS","NENU","NA","N12","N11","O1","O2","O3","JG5"];FR|2;-1;GB|22;13|SELECTROWSKEY4|true;""")
			.formParam("Grade$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;1&quot;,&quot;2&quot;,&quot;2A&quot;,&quot;2B&quot;,&quot;3A&quot;,&quot;3B&quot;,&quot;4A&quot;,&quot;4AII&quot;,&quot;4A3&quot;,&quot;4B&quot;,&quot;4C&quot;,&quot;4D&quot;,&quot;4E&quot;,&quot;5A&quot;,&quot;5B&quot;,&quot;5C&quot;,&quot;6A&quot;,&quot;6B&quot;,&quot;6C&quot;,&quot;6D&quot;,&quot;6E&quot;,&quot;7A&quot;,&quot;7B&quot;,&quot;7C&quot;,&quot;7D&quot;,&quot;7E&quot;,&quot;7F&quot;,&quot;7G&quot;,&quot;7I&quot;,&quot;A&quot;,&quot;5&quot;,&quot;N14&quot;,&quot;JG8&quot;,&quot;JG9&quot;,&quot;N02&quot;,&quot;N01&quot;,&quot;N10&quot;,&quot;JG12&quot;,&quot;G12&quot;,&quot;B&quot;,&quot;C1&quot;,&quot;C2&quot;,&quot;C3&quot;,&quot;C4&quot;,&quot;GM12&quot;,&quot;10&quot;,&quot;N15&quot;,&quot;11&quot;,&quot;N16&quot;,&quot;E1&quot;,&quot;AG&quot;,&quot;E2&quot;,&quot;SM&quot;,&quot;M&quot;,&quot;E3&quot;,&quot;E4&quot;,&quot;NE&quot;,&quot;E5&quot;,&quot;E6&quot;,&quot;JG6&quot;,&quot;EXAN&quot;,&quot;EXAH&quot;,&quot;EXCS&quot;,&quot;EXDO&quot;,&quot;EXNU&quot;,&quot;G1&quot;,&quot;G10&quot;,&quot;G2&quot;,&quot;G3&quot;,&quot;G4&quot;,&quot;G5&quot;,&quot;G6&quot;,&quot;G7&quot;,&quot;G8&quot;,&quot;G9&quot;,&quot;N05&quot;,&quot;JG14&quot;,&quot;G14&quot;,&quot;M1&quot;,&quot;M2&quot;,&quot;M3&quot;,&quot;4&quot;,&quot;JG10&quot;,&quot;MG1&quot;,&quot;MG2&quot;,&quot;MG3&quot;,&quot;MG4&quot;,&quot;8&quot;,&quot;JG2&quot;,&quot;NEAN&quot;,&quot;NEAH&quot;,&quot;NECS&quot;,&quot;NENU&quot;,&quot;NA&quot;,&quot;N12&quot;,&quot;N11&quot;,&quot;O1&quot;,&quot;O2&quot;,&quot;O3&quot;,&quot;JG5&quot;],&quot;callbackState&quot;:&quot;h2LgAn8SUR38IX+Pch4n55cBd+5syyG5mk0ytZ+d9v8CYSwkKjx4IRawK5Oz8+fcOgabCycsOFMkZPmJrm87PimCw/RG2AbjhUjFMkke2yBy/xgGzGPRuBBq873HLI+X0c/UrmusIL+y8rm8fpBu10plHC9lY8SelNZ7IDPfe/aDIiHGd5atUO5Gnd2kgVvHVRCeb65Kc+bCpZKCWE/LanYpGJYcU5fz6VR5mdOXeeajdEkI04+8YJo7VIvDZfcTW0+18wuYqVhcKBVBu/DeJ2Zw8EQ5yWzlPXVKC2NEmWZUpdq6W0hqP+KIQ0i4hTbonFA0hMqSk9nEDQBe2CEvdD4DBUCTHOmqXF2PYT3MYWLIdEG+P1iawFIHxC0X/MR0nU+RcGsMbkIeyiJJFyJC8oF+BLSZgScAj4E3/+mzsoU3oLBt6X5WeQQPjQFJUVy3AGX7vRXfBCwZ+zl6EG3AJI184IXgq9AsAG/w9XynDa5yU4vrJ6mc6Pk4VIgPyn95nOo8sbbshK1I6a//17s426THdErU5lZbp5dkYYxSq6gYqwep2KyUhAvQLNZbBRQe6hJUi0N/WDWnTGugRTGxI8YqZ5KGG7FI425CcerBEQY=&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
			.formParam("Grade$DDD$gv$DXFREditorcol1", "")
			.formParam("DXMVCEditorsValues", """{"EmployerAgencyPTPTN_DDD_L":["135"],"EmployerAgencyPTPTN":"135","PayrollMonth_DDD_L":["6"],"PayrollMonth":"6","PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"PaymentModePtptn_DDD_L":["E"],"PaymentModePtptn":"E","TransferDate":new Date(2021,5,1),"EftRefNo":null}""")
			.formParam("Grade$State", "{&quot;selectedKeyValues&quot;:null}")
			.formParam("Grade", "Please Select"))
		.exec(http("request_153")
			.post("/Criteria/SearchableDropDownListGridLookupPartial?criteriaObjectInString=%7B%22Type%22%3A%22SearchableDropDownList%22%2C%22Name%22%3A%22Category%22%2C%22Label%22%3A%22Category%22%2C%22DefaultValue%22%3Anull%2C%22DefaultDate%22%3Anull%2C%22DefaultDateRangeFrom%22%3Anull%2C%22DefaultDateRangeTo%22%3Anull%2C%22Value%22%3Anull%2C%22GroupId%22%3A2%2C%22IsRequired%22%3Afalse%2C%22Group%22%3Anull%2C%22DropDownListProperties%22%3A%7B%22TextField%22%3A%22CATEGORY_DESCRIPTION%22%2C%22ValueField%22%3A%22CATEGORY_CODE%22%2C%22FilterField%22%3Anull%2C%22DatasourceName%22%3A%22CategoriesDescription%22%2C%22DisplayFormatString%22%3Anull%2C%22SourceFrom%22%3A0%2C%22DefaultIndex%22%3Anull%2C%22SelectedIndexChangedJsCallBack%22%3Anull%2C%22ColumnsList%22%3A%5B%7B%22Name%22%3A%22CATEGORY_DESCRIPTION%22%2C%22Label%22%3A%22Description%22%2C%22Width%22%3A250%2C%22ColumnDisplayFormatString%22%3Anull%7D%5D%2C%22IsMultiSelection%22%3Atrue%2C%22DefaultValues%22%3Anull%2C%22LoadOnDemand%22%3Afalse%2C%22SelectAllMode%22%3Atrue%2C%22DefaultSelectAll%22%3Afalse%2C%22CascadeControl%22%3Anull%2C%22DatasourceParameters%22%3Anull%2C%22IsWrapText%22%3Afalse%7D%2C%22CascadeDropDownListProperties%22%3Anull%2C%22ChildDropDownListProperties%22%3Anull%2C%22CheckListProperties%22%3Anull%2C%22DefaultIndex%22%3Anull%2C%22IsAddLabel%22%3Afalse%2C%22IsChecked%22%3Afalse%2C%22Caption%22%3Anull%2C%22CheckedChangedJsCallBack%22%3Anull%2C%22MaxLength%22%3A0%2C%22DisplayFormatString%22%3Anull%2C%22NullText%22%3Anull%2C%22ShowIncrementButtons%22%3Afalse%2C%22Page%22%3A0%2C%22CascadeControl%22%3Anull%2C%22ValueFieldDelimiter%22%3Anull%2C%22DownloadBy%22%3Anull%2C%22InitJsCallBack%22%3Anull%2C%22MultiValueDelimiter%22%3Anull%2C%22DefaultValueTo%22%3Anull%7D")
			
			.formParam("DXCallbackName", "Category_DDD_gv")
			.formParam("__DXCallbackArgument", """c0:KV|48;["ADMN","ALLH","CLIN","MEDI","NA","NURS","STUD"];FR|2;-1;GB|22;13|SELECTROWSKEY4|true;""")
			.formParam("Category$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;ADMN&quot;,&quot;ALLH&quot;,&quot;CLIN&quot;,&quot;MEDI&quot;,&quot;NA&quot;,&quot;NURS&quot;,&quot;STUD&quot;],&quot;callbackState&quot;:&quot;kQikmwE+lbft8xL4enCUWKG2L3s+9JqL7zKYKdUP2/xrJdfq7Yt/w3nZW0ciZKK0Y5wK7LW5OFuzSUpLuEy1MUv4hVuGC7P6O00bYHqHvJNH0HryrbOXpbcMMYo9/FXzfvIMKXlLjfCaj91O1KLX3JMYt6VTk7HlzW/mY4hlhzXHOCrFRDPB+VvU8bmpgkPkSgXKwlVicAVDDyimbTAUrQoUskt7k9k2QBSVnWruye/ojI5VfP2Ibb80kSY6EDPi+BPbWjZKNfph4tW0qMgN2sWnlJWM+tlYDifSB2Vm1di31j+NhbpsEtmGtujdpYf7mJLCTZmMuA/YqUf804rOeYdSVCypiFffGfhPSiaIzFJUoBI7+gWjI/GHcfRyZB7b8SOfWCdF15bu+yekPlnLY+iPJF5gLJ9LTXm+/fNUAD81cG92EGDaC/X4ViBM3b2HkmNvjbztMIk2MEgFj0AO5g==&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
			.formParam("Category$DDD$gv$DXFREditorcol1", "")
			.formParam("DXMVCEditorsValues", """{"EmployerAgencyPTPTN_DDD_L":["135"],"EmployerAgencyPTPTN":"135","PayrollMonth_DDD_L":["6"],"PayrollMonth":"6","PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"PaymentModePtptn_DDD_L":["E"],"PaymentModePtptn":"E","TransferDate":new Date(2021,5,1),"EftRefNo":null}""")
			.formParam("Category$State", "{&quot;selectedKeyValues&quot;:null}")
			.formParam("Category", "Please Select"))
		.exec(http("request_154")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_155")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("objectSelectedIds[]", "315")
			.formParam("objectSelectedIds[]", "351")
			.formParam("objectSelectedIds[]", "449")
			.formParam("objectSelectedIds[]", "487")
			.formParam("objectSelectedIds[]", "526")
			.formParam("objectSelectedIds[]", "565")
			.formParam("objectSelectedIds[]", "603")
			.formParam("objectSelectedIds[]", "641")
			.formParam("objectSelectedIds[]", "679")
			.formParam("objectSelectedIds[]", "724")
			.formParam("objectSelectedIds[]", "762")
			.formParam("objectSelectedIds[]", "800")
			.formParam("objectSelectedIds[]", "838")
			.formParam("objectSelectedIds[]", "876")
			.formParam("objectSelectedIds[]", "914")
			.formParam("objectSelectedIds[]", "952")
			.formParam("objectSelectedIds[]", "990")
			.formParam("isAllSelected", "true"))
		.exec(http("request_156")
			.post("/Criteria/SearchableDropDownListGridLookupPartial?criteriaObjectInString=%7B%22Type%22%3A%22SearchableDropDownList%22%2C%22Name%22%3A%22Employee%22%2C%22Label%22%3A%22Employee%22%2C%22DefaultValue%22%3Anull%2C%22DefaultDate%22%3Anull%2C%22DefaultDateRangeFrom%22%3Anull%2C%22DefaultDateRangeTo%22%3Anull%2C%22Value%22%3Anull%2C%22GroupId%22%3A2%2C%22IsRequired%22%3Afalse%2C%22Group%22%3Anull%2C%22DropDownListProperties%22%3A%7B%22TextField%22%3A%22EMPLOYEE_NAME%22%2C%22ValueField%22%3A%22EMPLOYEE_KEY_VALUE%22%2C%22FilterField%22%3Anull%2C%22DatasourceName%22%3A%22PayrollEmployeeListAll%22%2C%22DisplayFormatString%22%3A%22%7B1%7D%22%2C%22SourceFrom%22%3A0%2C%22DefaultIndex%22%3Anull%2C%22SelectedIndexChangedJsCallBack%22%3Anull%2C%22ColumnsList%22%3A%5B%7B%22Name%22%3A%22LOCATION_CODE%22%2C%22Label%22%3A%22CompanyCode%22%2C%22Width%22%3A100%2C%22ColumnDisplayFormatString%22%3Anull%7D%2C%7B%22Name%22%3A%22EMPLOYEE_NO%22%2C%22Label%22%3A%22EmployeeNo%22%2C%22Width%22%3A100%2C%22ColumnDisplayFormatString%22%3Anull%7D%2C%7B%22Name%22%3A%22EMPLOYEE_NAME%22%2C%22Label%22%3A%22EMPLOYEE_NAME%22%2C%22Width%22%3A250%2C%22ColumnDisplayFormatString%22%3Anull%7D%5D%2C%22IsMultiSelection%22%3Atrue%2C%22DefaultValues%22%3Anull%2C%22LoadOnDemand%22%3Afalse%2C%22SelectAllMode%22%3Atrue%2C%22DefaultSelectAll%22%3Afalse%2C%22CascadeControl%22%3Anull%2C%22DatasourceParameters%22%3Anull%2C%22IsWrapText%22%3Afalse%7D%2C%22CascadeDropDownListProperties%22%3Anull%2C%22ChildDropDownListProperties%22%3Anull%2C%22CheckListProperties%22%3Anull%2C%22DefaultIndex%22%3Anull%2C%22IsAddLabel%22%3Afalse%2C%22IsChecked%22%3Afalse%2C%22Caption%22%3Anull%2C%22CheckedChangedJsCallBack%22%3Anull%2C%22MaxLength%22%3A0%2C%22DisplayFormatString%22%3Anull%2C%22NullText%22%3Anull%2C%22ShowIncrementButtons%22%3Afalse%2C%22Page%22%3A1%2C%22CascadeControl%22%3Anull%2C%22ValueFieldDelimiter%22%3A%22_%22%2C%22DownloadBy%22%3Anull%2C%22InitJsCallBack%22%3Anull%2C%22MultiValueDelimiter%22%3Anull%2C%22DefaultValueTo%22%3Anull%7D")
			
			.formParam("DXCallbackName", "Employee_DDD_gv")
			.formParam("__DXCallbackArgument", """c0:KV|1923;["2802_KK000001_ARC","8745_KK000002_ARC","8746_KK000004_ARC","8747_KK000006_ARC","8748_KK000009_ARC","8749_KK000012_ARC","8750_KK000013_ARC","8751_KK000015_ARC","8744_KK000016_ARC","8752_KK000017_ARC","8754_KK000019_ARC","8753_KK000021_ARC","9039_KK000022_ARC","9580_KK000024_ARC","9718_KK000025_ARC","9364_KK000026_ARC","9365_KK000027_ARC","10230_KK000028_ARC","5646_R000088_GKK","6379_R000091_GKK","5660_R000112_GKK","10761_R000117_GKK","5590_R000119_GKK","5591_R000121_GKK","5592_R000122_GKK","6380_R000123_GKK","5593_R000126_GKK","5594_R000127_GKK","5595_R000130_GKK","5596_R000131_GKK","5597_R000132_GKK","6381_R000133_GKK","8743_R000134_GKK","2557_R000135_GKK","5611_R000137_GKK","5612_R000138_GKK","2558_R000139_GKK","5613_R000140_GKK","5614_R000142_GKK","5615_R000143_GKK","5616_R000144_GKK","5617_R000145_GKK","5618_R000148_GKK","5619_R000149_GKK","5620_R000151_GKK","5621_R000152_GKK","5622_R000153_GKK","5623_R000154_GKK","6382_R000155_GKK","5637_R000169_GKK","5840_R000178_GKK","5836_R000182_GKK","11015_R000183_GKK","6383_R000184_GKK","5589_R000186_GKK","5837_R000187_GKK","5838_R000189_GKK","6400_R000190_GKK","5839_R000191_GKK","6401_R000196_GKK","5862_R000197_GKK","5863_R000203_GKK","6402_R000204_GKK","5864_R000206_GKK","5865_R000207_GKK","5866_R000208_GKK","5665_R000213_GKK","6403_R000215_GKK","5666_R000217_GKK","5867_R000218_GKK","6404_R000219_GKK","5868_R000221_GKK","5869_R000224_GKK","5720_R000231_GKK","6405_R000238_GKK","5798_R000241_GKK","5787_R000246_GKK","5783_R000248_GKK","5782_R000251_GKK","5780_R000253_GKK","5679_R000256_GKK","5781_R000262_GKK","5784_R000264_GKK","10829_R000265_GKK","5785_R000267_GKK","5786_R000268_GKK","5641_R000270_GKK","5642_R000272_GKK","5640_R000273_GKK","5639_R000275_GKK","5577_R000287_GKK","5578_R000290_GKK","5580_R000293_GKK","6064_R000294_GKK","6065_R000302_GKK","5606_R000303_GKK","5607_R000304_GKK","5628_R000305_GKK","5629_R000310_GKK","6027_R000317_GKK"];FR|2;-1;GB|22;13|SELECTROWSKEY4|true;""")
			.formParam("Employee$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;2802_KK000001_ARC&quot;,&quot;8745_KK000002_ARC&quot;,&quot;8746_KK000004_ARC&quot;,&quot;8747_KK000006_ARC&quot;,&quot;8748_KK000009_ARC&quot;,&quot;8749_KK000012_ARC&quot;,&quot;8750_KK000013_ARC&quot;,&quot;8751_KK000015_ARC&quot;,&quot;8744_KK000016_ARC&quot;,&quot;8752_KK000017_ARC&quot;,&quot;8754_KK000019_ARC&quot;,&quot;8753_KK000021_ARC&quot;,&quot;9039_KK000022_ARC&quot;,&quot;9580_KK000024_ARC&quot;,&quot;9718_KK000025_ARC&quot;,&quot;9364_KK000026_ARC&quot;,&quot;9365_KK000027_ARC&quot;,&quot;10230_KK000028_ARC&quot;,&quot;5646_R000088_GKK&quot;,&quot;6379_R000091_GKK&quot;,&quot;5660_R000112_GKK&quot;,&quot;10761_R000117_GKK&quot;,&quot;5590_R000119_GKK&quot;,&quot;5591_R000121_GKK&quot;,&quot;5592_R000122_GKK&quot;,&quot;6380_R000123_GKK&quot;,&quot;5593_R000126_GKK&quot;,&quot;5594_R000127_GKK&quot;,&quot;5595_R000130_GKK&quot;,&quot;5596_R000131_GKK&quot;,&quot;5597_R000132_GKK&quot;,&quot;6381_R000133_GKK&quot;,&quot;8743_R000134_GKK&quot;,&quot;2557_R000135_GKK&quot;,&quot;5611_R000137_GKK&quot;,&quot;5612_R000138_GKK&quot;,&quot;2558_R000139_GKK&quot;,&quot;5613_R000140_GKK&quot;,&quot;5614_R000142_GKK&quot;,&quot;5615_R000143_GKK&quot;,&quot;5616_R000144_GKK&quot;,&quot;5617_R000145_GKK&quot;,&quot;5618_R000148_GKK&quot;,&quot;5619_R000149_GKK&quot;,&quot;5620_R000151_GKK&quot;,&quot;5621_R000152_GKK&quot;,&quot;5622_R000153_GKK&quot;,&quot;5623_R000154_GKK&quot;,&quot;6382_R000155_GKK&quot;,&quot;5637_R000169_GKK&quot;,&quot;5840_R000178_GKK&quot;,&quot;5836_R000182_GKK&quot;,&quot;11015_R000183_GKK&quot;,&quot;6383_R000184_GKK&quot;,&quot;5589_R000186_GKK&quot;,&quot;5837_R000187_GKK&quot;,&quot;5838_R000189_GKK&quot;,&quot;6400_R000190_GKK&quot;,&quot;5839_R000191_GKK&quot;,&quot;6401_R000196_GKK&quot;,&quot;5862_R000197_GKK&quot;,&quot;5863_R000203_GKK&quot;,&quot;6402_R000204_GKK&quot;,&quot;5864_R000206_GKK&quot;,&quot;5865_R000207_GKK&quot;,&quot;5866_R000208_GKK&quot;,&quot;5665_R000213_GKK&quot;,&quot;6403_R000215_GKK&quot;,&quot;5666_R000217_GKK&quot;,&quot;5867_R000218_GKK&quot;,&quot;6404_R000219_GKK&quot;,&quot;5868_R000221_GKK&quot;,&quot;5869_R000224_GKK&quot;,&quot;5720_R000231_GKK&quot;,&quot;6405_R000238_GKK&quot;,&quot;5798_R000241_GKK&quot;,&quot;5787_R000246_GKK&quot;,&quot;5783_R000248_GKK&quot;,&quot;5782_R000251_GKK&quot;,&quot;5780_R000253_GKK&quot;,&quot;5679_R000256_GKK&quot;,&quot;5781_R000262_GKK&quot;,&quot;5784_R000264_GKK&quot;,&quot;10829_R000265_GKK&quot;,&quot;5785_R000267_GKK&quot;,&quot;5786_R000268_GKK&quot;,&quot;5641_R000270_GKK&quot;,&quot;5642_R000272_GKK&quot;,&quot;5640_R000273_GKK&quot;,&quot;5639_R000275_GKK&quot;,&quot;5577_R000287_GKK&quot;,&quot;5578_R000290_GKK&quot;,&quot;5580_R000293_GKK&quot;,&quot;6064_R000294_GKK&quot;,&quot;6065_R000302_GKK&quot;,&quot;5606_R000303_GKK&quot;,&quot;5607_R000304_GKK&quot;,&quot;5628_R000305_GKK&quot;,&quot;5629_R000310_GKK&quot;,&quot;6027_R000317_GKK&quot;],&quot;callbackState&quot;:&quot;kV/4+RGdnrhcSP6oUSghcA0jG2KO8TRLhD1Y4J2nhUcS6nt5C/Y9tWZ5Ya+8c1GzL+nAICsbHmgJ4ZkZ1iQztIqOave0UWIH37+bDz2x4mLz0sWn2WMA0nKKXVzXjhyCVsRTNoFAivD+iE0a4vVlpnX02AyuIIwmWavsZytv6hndk+29NjREAEUgzCX6ryQQGvzbS4jQwbs7bZqhxR6iqIfe56rDcLeRAUQM15MTORVDQgY1cSxqrk/470ON//HZw92jK/OrvZKB+3qIU2si3exCjx+TBz5qAKuOTa3lAOSDJRJkgU+VQFLssmPO9uhPWVSfUj/8LzkKaFxdpAN5RS6WRLmmpdX6uUy1wlW4EIRp0wsm+5VCwyZSMFtSdjqAImQ5O6PVDffRAusZnQJFbjt4N7x1NuzNiHv6VUml+3BBG/8I/U24EpsJ6cM98aNYkMVTROyvnMzUb6wYT4Hr5NsrGuC/YBHeOqMxKLtAiPHrZ1qywI7n7pM9wMPYVpiCU+KO4A00cclKs/pVXQ2qE2lVe9iPLELadHv/T8xM6B7IExQgzw9x4p4mObJeDSipHzaSbq9Am3SwG8X0TWJxPYKxOTzmNN+Hq/C2PvwwGwfB/vc5K4EsU9qqrj3zXM+oYkdtWCPkfhjOorypqDOkizGmANAT14brn9KZE2sjeNw=&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
			.formParam("Employee$DDD$gv$DXFREditorcol1", "")
			.formParam("Employee$DDD$gv$DXFREditorcol2", "")
			.formParam("Employee$DDD$gv$DXFREditorcol3", "")
			.formParam("DXMVCEditorsValues", """{"EmployerAgencyPTPTN_DDD_L":["135"],"EmployerAgencyPTPTN":"135","PayrollMonth_DDD_L":["6"],"PayrollMonth":"6","PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"PaymentModePtptn_DDD_L":["E"],"PaymentModePtptn":"E","TransferDate":new Date(2021,5,1),"EftRefNo":null}""")
			.formParam("Employee$State", "{&quot;selectedKeyValues&quot;:null}")
			.formParam("Employee", "Please Select"))
		.exec(http("request_157")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_158")
			.post("/PTPTNReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "PayPeriod")
			.formParam("isAllSelected", "false"))
		.exec(http("request_159")
			.post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")
			
			.formParam("DXCallbackName", "PayPeriod_DDD_gv")
			.formParam("__DXCallbackArgument", """c1:SR|1;U;KV|103;["351","724","762","990","838","679","315","449","603","487","800","526","952","876","565","641","914"];FR|2;-1;GB|27;13|SELECTROWSKEY4|true3|762;""")
			.formParam("PayPeriod$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;351&quot;,&quot;724&quot;,&quot;762&quot;,&quot;990&quot;,&quot;838&quot;,&quot;679&quot;,&quot;315&quot;,&quot;449&quot;,&quot;603&quot;,&quot;487&quot;,&quot;800&quot;,&quot;526&quot;,&quot;952&quot;,&quot;876&quot;,&quot;565&quot;,&quot;641&quot;,&quot;914&quot;],&quot;callbackState&quot;:&quot;hq8Rv7TNxJmzAJLEkE/BhodgYf8MO8xSqVpuyhgnqz27YZxW8IDsNoTKaCMMTVT81hNyYA0g8q5SjDihTTx4Z71+q/GqT4a1fLRYSwpKCYH9Q0qTbVezfZCK5h40pLMd0wYbJ/Jxl++A2nCuZQfdAltNuQcO7AGkp9/qZif4iaExG3s38rSsjMjcHRzCOfYpmPC3ssjmzqj/+hkaiyEehToKfsNSDqNfP3WCJ/PbCqDAxN1pWrAJCe+nwNnvPLsAHuDjJ3n3HUzNFYM8fx9FmpWCFsut03bPUIahmkgHN7UHDSQKCZvAAU/kcG7/VJVYwKuXo3IJPIZNk1swxKyeNqdq9ODrKJFhfs3869x6E2/XJnVUoNCxbdhISrn4bckJqDixgmQcQeyNOsZEf7jp6j1ambXCNaSq1unJKD1jaAV9RlmbXpiVbN6geLbqYFI8f6FUd2CvZiy8sids2hqt8rHwxbkl55mkslDx151J9n6iD6j+qsjKrLMTIiIevAedP1VLjSK+gLF0xJU1ihspnyYrNDVQBZOCBgabXtcmsi8=&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;U&quot;,&quot;focusedKey&quot;:null}")
			.formParam("PayPeriod$DDD$gv$DXFREditorcol1", "")
			.formParam("PayPeriod$DDD$gv$DXFREditorcol2", "")
			.formParam("DXMVCEditorsValues", """{"EmployerAgencyPTPTN_DDD_L":["135"],"EmployerAgencyPTPTN":"135","PayrollMonth_DDD_L":["6"],"PayrollMonth":"6","PayrollMonthTextBox":"2021","PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod_DDD_gv_DXFREditorcol2":null,"PayPeriod":["762"],"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"PaymentModePtptn_DDD_L":["E"],"PaymentModePtptn":"E","TransferDate":new Date(2021,5,1),"EftRefNo":null}""")
			.formParam("PayPeriod$State", "{&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:null}")
			.formParam("PayPeriod", "202106 - Monthly Payment (GMH)")
			.formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"PayPeriod","Label":"PayPeriod","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":null,"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"PAY_PERIOD_DESCRIPTION","ValueField":"ID","FilterField":null,"FilterFieldList":[{"ParameterName":"EmployerAgencyPTPTN","FilterField":"LOCATION_ID","FilterOperator":0,"TargetDatasourceName":"PtptnEmployerAgencyNo","TargetDatasourceProperty":"ID"},{"ParameterName":"PayrollMonth","FilterField":"PAYROLL_MONTH","FilterOperator":0,"TargetDatasourceName":null,"TargetDatasourceProperty":null},{"ParameterName":"PayrollMonthTextBox","FilterField":"PAYROLL_YEAR","FilterOperator":0,"TargetDatasourceName":null,"TargetDatasourceProperty":null}],"DatasourceName":"PayPeriods","DisplayFormatString":"{0}","SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"PAY_PERIOD_DESCRIPTION","Label":"PayPeriod","Width":250,"ColumnDisplayFormatString":null},{"Name":"COMPANY.LOCATION_CODE","Label":"Company","Width":50,"ColumnDisplayFormatString":null}],"CascadeControl":null,"LoadOnDemand":false,"SelectAllMode":true,"DefaultSelectAll":true,"IsMultiSelection":true,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
			.formParam("ParentId[]", "")
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "135")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "E")
			.formParam("CustomSearchParameters[15][Name]", "TransferDate")
			.formParam("CustomSearchParameters[15][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[16][Name]", "EftRefNo")
			.formParam("CustomSearchParameters[16][Value]", ""))
		.pause(4)
		.exec(http("request_160")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_161")
			.get("/DXR.axd?r=0_2303-O3Vxm"))
		.exec(http("request_162")
			.post("/Report/GeneratePTPTNReport")
			
			.formParam("CustomSearchParameters[0][Name]", "EmployerAgencyPTPTN")
			.formParam("CustomSearchParameters[0][Value]", "135")
			.formParam("CustomSearchParameters[1][Name]", "PayrollMonth")
			.formParam("CustomSearchParameters[1][Value]", "6")
			.formParam("CustomSearchParameters[2][Name]", "PayrollMonthTextBox")
			.formParam("CustomSearchParameters[2][Value]", "2021")
			.formParam("CustomSearchParameters[3][Name]", "PayPeriod")
			.formParam("CustomSearchParameters[3][Value]", "762")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", "")
			.formParam("CustomSearchParameters[14][Name]", "PaymentModePtptn")
			.formParam("CustomSearchParameters[14][Value]", "E")
			.formParam("CustomSearchParameters[15][Name]", "TransferDate")
			.formParam("CustomSearchParameters[15][Value]", "2021/06/01")
			.formParam("CustomSearchParameters[16][Name]", "EftRefNo")
			.formParam("CustomSearchParameters[16][Value]", "")
			.formParam("ReportObjectTypeName", "Reports.Statutory.RPT_PTPTN_REPORT"))
		.pause(171.milliseconds)
		.exec(http("request_163")
			.get("/DXR.axd?r=24_367-N3Vxm")
			)
		.pause(145.milliseconds)
		.exec(http("request_164")
			.post("/Report/DXXRDV.axd")
			
			.formParam("actionKey", "startBuild")
			.formParam("arg", "%7B%22reportId%22%3A%220d61828f34d047eab13e4b028df19949%22%2C%22reportUrl%22%3A%22%22%2C%22drillDownKeys%22%3A%5B%5D%2C%22sortingState%22%3A%5B%5D%2C%22timeZoneOffset%22%3A480%2C%22parameters%22%3A%5B%7B%22Value%22%3A%222021-06-01T00%3A00%3A00.000Z%22%2C%22Key%22%3A%22TransferDate%22%2C%22TypeString%22%3A%22System.DateTime%22%7D%2C%7B%22Value%22%3A%22%22%2C%22Key%22%3A%22EftRefNo%22%2C%22TypeString%22%3A%22System.String%22%7D%2C%7B%22Value%22%3A%22%22%2C%22Key%22%3A%22ChequeNo%22%2C%22TypeString%22%3A%22System.String%22%7D%2C%7B%22Value%22%3Anull%2C%22Key%22%3A%22ChequeDate%22%2C%22TypeString%22%3A%22System.DateTime%22%7D%2C%7B%22Value%22%3Anull%2C%22Key%22%3A%22DepositDate%22%2C%22TypeString%22%3A%22System.DateTime%22%7D%2C%7B%22Value%22%3A%22JUN%22%2C%22Key%22%3A%22PayrollMonth%22%2C%22TypeString%22%3A%22System.String%22%7D%2C%7B%22Value%22%3A%222021%22%2C%22Key%22%3A%22PayrollYear%22%2C%22TypeString%22%3A%22System.Int32%22%7D%2C%7B%22Value%22%3A%22%22%2C%22Key%22%3A%22IssuingBank%22%2C%22TypeString%22%3A%22System.String%22%7D%5D%7D"))
		.pause(408.milliseconds)
		.exec(http("request_165")
			.post("/Report/DXXRDV.axd")
			
			.formParam("actionKey", "getBuildStatus")
			.formParam("arg", "%7B%22documentId%22%3A%22cd1e355ee74043a2b7ad93a29457f484%22%2C%22timeOut%22%3A120000%7D"))
		.pause(293.milliseconds)
		.exec(http("request_166")
			.post("/Report/DXXRDV.axd")
			
			.formParam("actionKey", "getBuildStatus")
			.formParam("arg", "%7B%22documentId%22%3A%22cd1e355ee74043a2b7ad93a29457f484%22%2C%22timeOut%22%3A120000%7D"))
		.exec(http("request_167")
			.post("/Report/DXXRDV.axd")
			
			.formParam("actionKey", "getDocumentData")
			.formParam("arg", "cd1e355ee74043a2b7ad93a29457f484"))
/*	.exec(http("request_168")
		.get("/Report/DXXRDV.axd?actionKey=getPage&unifier=dd0f3f22-626d-f87d-a3b0-af0d97e980cd&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%22cd1e355ee74043a2b7ad93a29457f484%22%2C%22resolution%22%3A96%7D")
		)*/
		.exec(http("request_169")
			.post("/Report/DXXRDV.axd")
			
			.formParam("actionKey", "getBrickMap")
			.formParam("arg", "%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%22cd1e355ee74043a2b7ad93a29457f484%22%7D"))

		.pause(15) //TIME is  35
  
  
  }

  def logout = {
    exec(http("Logout Submission")
			.post("/Account/LogOff")
			
			.formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
			.formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
			.formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css")
			.check(status.is(302)))
		.exec(http("Login After Logout")
			.get("/Account/Login")
			)
		.exec(http("request_173")
			.get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
			)
		.exec(http("request_174")
			.get("/DXR.axd?r=1_58-N3Vxm")
			)
		.exec(http("request_175")
			.get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
			)
		.exec(http("request_176")
			.get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
			)
		.exec(http("request_177")
			.get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
			)
		.exec(http("request_178")
			.get("/Content/fonts/icomoon.ttf?5vru0d")
			)
		.exec(http("request_179")
			.get("/Content/Images/bg-login.jpg?V=03")
			)
  }




}
