package computerdatabase.Module.payrollObject

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._


object PayrollBorangZakatSelangor {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Borang Zakat Selangor Page")
      .get("/Report/ZakatSelangorReport")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
    )
      .exec(http("request_74")
        .get("/signalr/hubs")
      )
      .exec(http("request_75")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(924.milliseconds)
      .exec(http("request_76")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_77")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .exec(http("request_78")
        .get("/DXR.axd?r=0_2314-O3Vxm")
      )
      .exec(http("request_79")
        .get("/DXR.axd?r=0_2216-O3Vxm")
      )
      .exec(http("request_80")
        .get("/DXR.axd?r=0_2316-O3Vxm")
      )
      .pause(192.milliseconds)
      .exec(http("request_81")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_82")
        .get("/DXR.axd?r=0_2303-O3Vxm")
      )
      .exec(http("request_83")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_84")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "ZAKAT_STATE")
        .formParam("comboBoxValue", ""))
      .exec(http("request_85")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_86")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "PayrollMonth")
        .formParam("comboBoxValue", ""))
      .exec(http("request_87")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_88")
        .post("/ZakatSelangorReport/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("isAllSelected", "false"))
      .exec(http("request_89")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_90")
        .post("/ZakatSelangorReport/CheckBoxListDisplay")

        .formParam("objectLabel", "EmployeeStatus")
        .formParam("objectSelectedIds[]", "A")
        .formParam("objectSelectedIds[]", "L")
        .formParam("objectSelectedIds[]", "I"))

      .exec(http("request_91")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "EMPLOYER_AGENCY_ID")
        .formParam("comboBoxValue", ""))
      .exec(http("request_92")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_93")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "IssuingBank")
        .formParam("comboBoxValue", ""))
      .pause(193.milliseconds)
      .exec(http("request_94")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_95")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622521685412")
      )
      .exec(http("request_96")
        .get("/Notifications/GetNotificationCounts")
      )
      .pause(440.milliseconds)
      .exec(http("request_97")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=Y1gscoBttjdT2u2R1VSs6oyWhf3V6VGwDmP18OwD1HUZJS%2B5XMWyyp1iCTBGFQL4zk6lMMMckae7ObwPoV%2F3kX4fqqrk4YlmFmYRTokXv15F1RUl4ZKcsO72cQ1r7dgifTYYU9z%2F9%2BACZhxEeMkIP1I%2FlQ8PtecUmKB0F3wgerM%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622521685413")
      )
      .pause(1)
      .exec(http("request_98")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_99")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "EMPLOYER_AGENCY_ID")
        .formParam("comboBoxValue", "105"))
      .exec(http("request_100")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_101")
        .post("/ZakatSelangorReport/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "PayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyZAKAT")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "ZakatEmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayMonths")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollYear")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "50")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyZAKAT")
        .formParam("CustomSearchParameters[0][Value]", "105")
        .formParam("CustomSearchParameters[1][Name]", "ZakatState")
        .formParam("CustomSearchParameters[1][Value]", "")
        .formParam("CustomSearchParameters[2][Name]", "PayrollYear")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayMonths")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[5][Value]", "A,L,I")
        .formParam("CustomSearchParameters[6][Name]", "Location")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[7][Value]", "|||||||||")
        .formParam("CustomSearchParameters[8][Name]", "Category")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Grade")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "Employee")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[13][Value]", "")
        .formParam("CustomSearchParameters[14][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "PrintDate")
        .formParam("CustomSearchParameters[15][Value]", "2021/06/01")
        .formParam("CustomSearchParameters[16][Name]", "ChequeNo")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "CompanyAccount")
        .formParam("CustomSearchParameters[17][Value]", ""))
      .exec(http("request_102")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_103")
        .post("/ZakatSelangorReport/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "427")
        .formParam("objectSelectedIds[]", "986")
        .formParam("objectSelectedIds[]", "987")
        .formParam("objectSelectedIds[]", "988")
        .formParam("objectSelectedIds[]", "989")
        .formParam("objectSelectedIds[]", "990")
        .formParam("objectSelectedIds[]", "991")
        .formParam("objectSelectedIds[]", "992")
        .formParam("objectSelectedIds[]", "993")
        .formParam("objectSelectedIds[]", "994")
        .formParam("objectSelectedIds[]", "995")
        .formParam("objectSelectedIds[]", "996")
        .formParam("isAllSelected", "true"))
      .pause(736.milliseconds)
      .exec(http("request_104")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FReport%2FZakatSelangorReport&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._h7py0m&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=122580")
      )
      .pause(561.milliseconds)
      .exec(http("request_105")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_106")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "ZAKAT_STATE")
        .formParam("comboBoxValue", "01"))
      .pause(2)
      .exec(http("request_107")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_108")
        .post("/ZakatSelangorReport/ComboBoxDisplay")

        .formParam("objectLabel", "PayrollMonth")
        .formParam("comboBoxValue", "5"))
      .exec(http("request_109")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_110")
        .post("/ZakatSelangorReport/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "PayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "EmployerAgencyZAKAT")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "ZakatEmployerAgencyNo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayMonths")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_MONTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollYear")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEAR")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "50")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyZAKAT")
        .formParam("CustomSearchParameters[0][Value]", "105")
        .formParam("CustomSearchParameters[1][Name]", "ZakatState")
        .formParam("CustomSearchParameters[1][Value]", "01")
        .formParam("CustomSearchParameters[2][Name]", "PayrollYear")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayMonths")
        .formParam("CustomSearchParameters[3][Value]", "5")
        .formParam("CustomSearchParameters[4][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[4][Value]", "427,986,987,988,989,990,991,992,993,994,995,996")
        .formParam("CustomSearchParameters[5][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[5][Value]", "A,L,I")
        .formParam("CustomSearchParameters[6][Name]", "Location")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[7][Value]", "|||||||||")
        .formParam("CustomSearchParameters[8][Name]", "Category")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Grade")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "Employee")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[13][Value]", "")
        .formParam("CustomSearchParameters[14][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "PrintDate")
        .formParam("CustomSearchParameters[15][Value]", "2021/06/01")
        .formParam("CustomSearchParameters[16][Name]", "ChequeNo")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "CompanyAccount")
        .formParam("CustomSearchParameters[17][Value]", ""))
      .exec(http("request_111")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_112")
        .post("/ZakatSelangorReport/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "989")
        .formParam("isAllSelected", "true"))
      .pause(1)
      .exec(http("request_113")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_114")
        .post("/Report/GenerateZakatSelangorReport")

        .formParam("CustomSearchParameters[0][Name]", "EmployerAgencyZAKAT")
        .formParam("CustomSearchParameters[0][Value]", "105")
        .formParam("CustomSearchParameters[1][Name]", "ZakatState")
        .formParam("CustomSearchParameters[1][Value]", "01")
        .formParam("CustomSearchParameters[2][Name]", "PayrollYear")
        .formParam("CustomSearchParameters[2][Value]", "2021")
        .formParam("CustomSearchParameters[3][Name]", "PayMonths")
        .formParam("CustomSearchParameters[3][Value]", "5")
        .formParam("CustomSearchParameters[4][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[4][Value]", "989")
        .formParam("CustomSearchParameters[5][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[5][Value]", "A,L,I")
        .formParam("CustomSearchParameters[6][Name]", "Location")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[7][Value]", "|||||||||")
        .formParam("CustomSearchParameters[8][Name]", "Category")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Grade")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "Employee")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[13][Value]", "")
        .formParam("CustomSearchParameters[14][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "PrintDate")
        .formParam("CustomSearchParameters[15][Value]", "2021/06/01")
        .formParam("CustomSearchParameters[16][Name]", "ChequeNo")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "CompanyAccount")
        .formParam("CustomSearchParameters[17][Value]", "")
        .formParam("ReportObjectTypeName", "Reports.Zakat.ZakatSelangorReport"))
      .pause(160.milliseconds)
      .exec(http("request_115")
        .get("/DXR.axd?r=24_367-N3Vxm")
      )
      .pause(119.milliseconds)
      .exec(http("request_116")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "startBuild")
        .formParam("arg", "%7B%22reportId%22%3A%228c8d21c35ccf4892bc32c5325ef13e0c%22%2C%22reportUrl%22%3A%22%22%2C%22drillDownKeys%22%3A%5B%5D%2C%22sortingState%22%3A%5B%5D%2C%22timeZoneOffset%22%3A480%2C%22parameters%22%3A%5B%7B%22Value%22%3A%222021-06-01T00%3A00%3A00.000Z%22%2C%22Key%22%3A%22PrintDate%22%2C%22TypeString%22%3A%22System.DateTime%22%7D%5D%7D"))
      .pause(376.milliseconds)
      .exec(http("request_117")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getBuildStatus")
        .formParam("arg", "%7B%22documentId%22%3A%228c31d757d90c4d0bbe1a7f5033d8309c%22%2C%22timeOut%22%3A120000%7D"))
      .exec(http("request_118")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getDocumentData")
        .formParam("arg", "8c31d757d90c4d0bbe1a7f5033d8309c"))
      /*		.exec(http("request_119")
            .get("/Report/DXXRDV.axd?actionKey=getPage&unifier=0fe734da-f15a-24dd-ed7a-a62d36df1407&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%228c31d757d90c4d0bbe1a7f5033d8309c%22%2C%22resolution%22%3A96%7D")
            )*/
      .exec(http("request_120")
        .post("/Report/DXXRDV.axd")

        .formParam("actionKey", "getBrickMap")
        .formParam("arg", "%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%228c31d757d90c4d0bbe1a7f5033d8309c%22%7D"))

      .pause(9)
  }

  def logout = {
    exec(http("Logout Submission")
      .post("/Account/LogOff")

      .formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css")
      .check(status.is(302)))
      .exec(http("Login After Logout")
        .get("/Account/Login")
      )
      .exec(http("request_124")
        .get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
      )
      .exec(http("request_125")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_126")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_127")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
      )
      .exec(http("request_128")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
      )
      .exec(http("request_129")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_130")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }

}
