package computerdatabase.Module.payrollObject

import io.gatling.core.Predef._
import io.gatling.core.structure.ChainBuilder
import io.gatling.http.Predef._

import scala.concurrent.duration._
import scala.io.Source

object PayrollDeleteAndMovePayroll {
  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadPayrollDelete = {
    exec(http("request_17")
      .get("/PayrollTransaction/DeleteandMovePayTransactions")
      .check(css("input[name='CreatedBy']", "value").saveAs("idNo"))
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationTokenLogout"))
      .check(bodyString.saveAs("body"))
    )
      .exec(session => {

        val key = session("body").as[String]
        val no = session("idNo").as[String]
        val fileContents = Source.fromFile("src/test/resources/data/test.txt").getLines.mkString
        //println(s"GH : $fileContents")
        println(s"Key : $no")

        session.set("transaction",fileContents)
      })

      .exec(http("request_18")
        .get("/DXR.axd?r=0_2314-O3Vxm"))
      .exec(http("request_19")
        .get("/DXR.axd?r=0_2216-O3Vxm"))
      .exec(http("request_20")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A"))
      .exec(http("request_21")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1"))
      .exec(http("request_22")
        .get("/DXR.axd?r=0_2316-O3Vxm"))
      .pause(363.milliseconds)
      .exec(http("request_23")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_24")
        .get("/DXR.axd?r=0_2303-O3Vxm"))
      .exec(http("request_25")
        .post("/DeleteandMovePayTransaction/ComboBoxDisplay")

        .formParam("objectLabel", "ProcessOption")
        .formParam("comboBoxValue", "D"))
      .exec(http("request_26")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_27")
        .post("/DeleteandMovePayTransaction/CascadeComboBoxDisplay")

        .formParam("objectLabel", "CurrentPayPeriod")
        .formParam("isAllSelected", "false"))
      .exec(http("request_28")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_29")
        .post("/DeleteandMovePayTransaction/CheckBoxListDisplay")

        .formParam("objectLabel", "CreationOption")
        .formParam("objectSelectedIds[]", "DL"))
      .exec(http("request_30")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_31")
        .post("/DeleteandMovePayTransaction/CascadeComboBoxDisplay")

        .formParam("objectLabel", "MoveToPayPeriod")
        .formParam("isAllSelected", "false"))
      .exec(http("request_32")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_33")
        .post("/DeleteandMovePayTransaction/SearchableDropDownListDisplay")
      )
      .exec(http("request_34")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_35")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1624105644777")
      )
      .exec(http("request_36")
        .get("/Notifications/GetNotificationCounts")
      )
      .pause(2)
      .exec(http("request_37")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=PNiMbzPxFCt6jpXhxJXM%2BS5ErsbZqKhX2rw5ji9dl8E6FhGw%2BRx4gSVpPGyYbqaY1%2FP1N14j7XiGNzJkBsKb%2FmmKfKgy9WGHpX7x7uBdVglUdXDBHuhvDoKpgCYTVXagd3dLgxtJvFaxPfhWBFrmKiIv9oJ2XEOwbz6UvlWynXQ%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1624105644778")
      )
      .exec(http("request_38")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FPayrollTransaction%2FDeleteandMovePayTransactions&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._fhmiq&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=27140")
      )
      .pause(335.milliseconds)
      .exec(http("request_39")
        .get("/DXR.axd?r=0_2223-O3Vxm"))
      .pause(1)
      .exec(http("request_40")
        .post("/Criteria/SearchableDropDownListGridLookupPartial?criteriaObjectInString=%7B%22Type%22%3A%22SearchableDropDownList%22%2C%22Name%22%3A%22PayPeriod%22%2C%22Label%22%3A%22PayPeriod%22%2C%22DefaultValue%22%3Anull%2C%22DefaultDate%22%3Anull%2C%22DefaultDateRangeFrom%22%3Anull%2C%22DefaultDateRangeTo%22%3Anull%2C%22Value%22%3Anull%2C%22GroupId%22%3A1%2C%22IsRequired%22%3Afalse%2C%22Group%22%3Anull%2C%22DropDownListProperties%22%3A%7B%22TextField%22%3A%22PAY_PERIOD_DESCRIPTION%22%2C%22ValueField%22%3A%22ID%22%2C%22FilterField%22%3Anull%2C%22DatasourceName%22%3A%22CurrentMonthPayPeriods%22%2C%22DisplayFormatString%22%3A%22%7B1%7D%22%2C%22SourceFrom%22%3A0%2C%22DefaultIndex%22%3Anull%2C%22SelectedIndexChangedJsCallBack%22%3Anull%2C%22ColumnsList%22%3A%5B%7B%22Name%22%3A%22COMPANY.LOCATION_CODE%22%2C%22Label%22%3A%22Company%22%2C%22Width%22%3A100%2C%22ColumnDisplayFormatString%22%3Anull%7D%2C%7B%22Name%22%3A%22PAY_PERIOD_DESCRIPTION%22%2C%22Label%22%3A%22Description%22%2C%22Width%22%3A250%2C%22ColumnDisplayFormatString%22%3Anull%7D%2C%7B%22Name%22%3A%22MONTH_YEAR%22%2C%22Label%22%3A%22PayrollMonth%22%2C%22Width%22%3A100%2C%22ColumnDisplayFormatString%22%3Anull%7D%5D%2C%22IsMultiSelection%22%3Afalse%2C%22DefaultValues%22%3Anull%2C%22LoadOnDemand%22%3Afalse%2C%22SelectAllMode%22%3Afalse%2C%22DefaultSelectAll%22%3Afalse%2C%22CascadeControl%22%3Anull%2C%22DatasourceParameters%22%3Anull%2C%22IsWrapText%22%3Afalse%7D%2C%22CascadeDropDownListProperties%22%3Anull%2C%22ChildDropDownListProperties%22%3Anull%2C%22CheckListProperties%22%3Anull%2C%22DefaultIndex%22%3Anull%2C%22IsAddLabel%22%3Afalse%2C%22IsChecked%22%3Afalse%2C%22Caption%22%3Anull%2C%22CheckedChangedJsCallBack%22%3Anull%2C%22MaxLength%22%3A0%2C%22DisplayFormatString%22%3Anull%2C%22NullText%22%3Anull%2C%22ShowIncrementButtons%22%3Afalse%2C%22Page%22%3A0%2C%22CascadeControl%22%3Anull%2C%22ValueFieldDelimiter%22%3Anull%2C%22DownloadBy%22%3Anull%2C%22InitJsCallBack%22%3Anull%2C%22MultiValueDelimiter%22%3Anull%2C%22DefaultValueTo%22%3Anull%7D")
      )
      .pause(113.milliseconds)
      .exec(http("request_41")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_42")
        .post("/DeleteandMovePayTransaction/SearchableDropDownListDisplay")
        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "347")
        .formParam("isAllSelected", "false"))
      .pause(1)
      .exec(http("request_43")
        .post("/Account/VerifyAccess")
      )
  }

  def filterPayroll = {
    exec(http("request_44")
      .post("/PayrollTransaction/PartialPayTransGridview")
      .formParam("Customsearchparameters[0][Name]", "ProcessOption")
      .formParam("Customsearchparameters[0][Value]", "D")
      .formParam("Customsearchparameters[1][Name]", "PayPeriod")
      .formParam("Customsearchparameters[1][Value]", "347")
      .formParam("Customsearchparameters[2][Name]", "CurrentPayPeriod")
      .formParam("Customsearchparameters[2][Value]", "")
      .formParam("Customsearchparameters[3][Name]", "CreatedDateFrom")
      .formParam("Customsearchparameters[3][Value]", "2021/05/19")
      .formParam("Customsearchparameters[4][Name]", "CreatedDateTo")
      .formParam("Customsearchparameters[4][Value]", "2021/08/28")
      .formParam("Customsearchparameters[5][Name]", "CreatedBy")
      .formParam("Customsearchparameters[5][Value]", "${idNo}")
      .formParam("Customsearchparameters[6][Name]", "CreationOption")
      .formParam("Customsearchparameters[6][Value]", "DL")
      .formParam("Customsearchparameters[7][Name]", "EmployeeMove")
      .formParam("Customsearchparameters[7][Value]", "")
      .formParam("Customsearchparameters[8][Name]", "MoveToPayPeriod")
      .formParam("Customsearchparameters[8][Value]", "")
      .formParam("Customsearchparameters[9][Name]", "Employee")
      .formParam("Customsearchparameters[9][Value]", "")
      .formParam("Customsearchparameters[10][Name]", "Transaction")
      .formParam("Customsearchparameters[10][Value]", "${transaction}")
      .check(bodyString.saveAs("body"))
      .check(regex("'keys':\\[(.+?)\\],").saveAs("key"))
      .check(regex("'callbackState':'(.+?)'").saveAs("callBackState"))
    )
      .exec(session =>{

        val body = session("transaction").as[String]
        val key = session("key").as[String]
        val callbackState = session("callBackState").as[String]
        //println(s"Key :$key")
        //println(s"CallBack :$callbackState")
        println(s"Body : $body")
        session
      })
  }
  def deletePayroll = {
    exec(http("request_48")
      .post("/PayrollTransaction/PartialPayTransGridview")
      .formParam("DXCallbackName", "gvTransaction")
      .formParam("__DXCallbackArgument", """c0:KV|19;[${key}];FR|1;0;FB|1;0;GB|21;14|SELFIELDVALUES2|ID;""")
      .formParam("gvTransaction", "{&quot;focusedRow&quot;:0,&quot;keys&quot;:[${key}],&quot;callbackState&quot;:&quot;${callBackState}&quot;,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;TT&quot;,&quot;batchEditClientModifiedValues&quot;:{&quot;ClientState&quot;:{&quot;InsertedIndices&quot;:[],&quot;InsertedValues&quot;:{},&quot;UpdatedValues&quot;:{},&quot;DeletedKeys&quot;:[]},&quot;EditState&quot;:{&quot;insertedRowValues&quot;:{},&quot;modifiedRowValues&quot;:{},&quot;deletedRowKeys&quot;:[]}}}")
      .formParam("gvTransaction$DXEditor1$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor1", "")
      .formParam("gvTransaction$DXEditor2$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor2", "")
      .formParam("gvTransaction$DXEditor2$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor2$DDD$C", "{&quot;visibleDate&quot;:&quot;06/19/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
      .formParam("gvTransaction$DXEditor2$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor3$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction_DXEditor3_VI", "")
      .formParam("gvTransaction$DXEditor3", "")
      .formParam("gvTransaction$DXEditor3$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor3$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor3$DDD$L", "")
      .formParam("gvTransaction$DXEditor4$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor4", "")
      .formParam("gvTransaction$DXEditor5$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor5", "")
      .formParam("gvTransaction$DXEditor6$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction_DXEditor6_VI", "")
      .formParam("gvTransaction$DXEditor6", "")
      .formParam("gvTransaction$DXEditor6$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor6$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor6$DDD$L", "")
      .formParam("gvTransaction$DXEditor7$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor7", "")
      .formParam("gvTransaction$DXEditor8$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor8", "")
      .formParam("gvTransaction$DXEditor9$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor9", "")
      .formParam("gvTransaction$DXEditor9$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor9$DDD$C", "{&quot;visibleDate&quot;:&quot;06/19/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
      .formParam("gvTransaction$DXEditor9$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor10$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor10", "")
      .formParam("gvTransaction$DXEditor10$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor10$DDD$C", "{&quot;visibleDate&quot;:&quot;06/19/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
      .formParam("gvTransaction$DXEditor10$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor11$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor11", "")
      .formParam("gvTransaction$DXEditor12$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor12", "")
      .formParam("gvTransaction$DXEditor13$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction_DXEditor13_VI", "")
      .formParam("gvTransaction$DXEditor13", "")
      .formParam("gvTransaction$DXEditor13$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor13$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor13$DDD$L", "")
      .formParam("gvTransaction$DXEditor14$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor14", "")
      .formParam("gvTransaction$DXEditor15$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction_DXEditor15_VI", "")
      .formParam("gvTransaction$DXEditor15", "")
      .formParam("gvTransaction$DXEditor15$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor15$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor15$DDD$L", "")
      .formParam("gvTransaction$DXEditor16$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor16", "")
      .formParam("gvTransaction$DXEditor17$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor17", "")
      .formParam("gvTransaction$DXEditor18$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction_DXEditor18_VI", "")
      .formParam("gvTransaction$DXEditor18", "")
      .formParam("gvTransaction$DXEditor18$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
      .formParam("gvTransaction$DXEditor18$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor18$DDD$L", "")
      .formParam("gvTransaction$DXEditor19$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor19", "I")
      .formParam("gvTransaction$DXEditor20$State", "{&quot;validationState&quot;:&quot;&quot;}")
      .formParam("gvTransaction$DXEditor20", "I")
      .formParam("DXMVCEditorsValues", "{&quot;ProcessOption_DDD_L&quot;:[&quot;D&quot;],&quot;ProcessOption&quot;:&quot;D&quot;,&quot;PayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;PayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;PayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;PayPeriod&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;CurrentPayPeriod&quot;:null,&quot;CreatedDateFrom&quot;:new Date(2021,5,20,19,14,45,192),&quot;CreatedDateTo&quot;:new Date(2021,8,28,17,14,45,192),&quot;CreatedBy&quot;:&quot;${idNo}&quot;,&quot;CreationOption&quot;:[&quot;DL&quot;],&quot;EmployeeMove_DDD_gv_DXFREditorcol1&quot;:null,&quot;EmployeeMove_DDD_gv_DXFREditorcol2&quot;:null,&quot;EmployeeMove_DDD_gv_DXFREditorcol3&quot;:null,&quot;EmployeeMove&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;MoveToPayPeriod&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol1&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol2&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol3&quot;:null,&quot;Employee&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol1&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol2&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol3&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol4&quot;:null,&quot;Transaction&quot;:[${transaction}]}")
      .formParam("DXMVCBatchEditingValuesRequestKey", "gvTransaction")
      .formParam("DXMVCBatchEditingKeyFieldName", "ID")
      .formParam("Customsearchparameters[0][Name]", "ProcessOption")
      .formParam("Customsearchparameters[0][Value]", "D")
      .formParam("Customsearchparameters[1][Name]", "PayPeriod")
      .formParam("Customsearchparameters[1][Value]", "347")
      .formParam("Customsearchparameters[2][Name]", "CurrentPayPeriod")
      .formParam("Customsearchparameters[2][Value]", "")
      .formParam("Customsearchparameters[3][Name]", "CreatedDateFrom")
      .formParam("Customsearchparameters[3][Value]", "2021/05/19")
      .formParam("Customsearchparameters[4][Name]", "CreatedDateTo")
      .formParam("Customsearchparameters[4][Value]", "2021/08/28")
      .formParam("Customsearchparameters[5][Name]", "CreatedBy")
      .formParam("Customsearchparameters[5][Value]", "${idNo}")
      .formParam("Customsearchparameters[6][Name]", "CreationOption")
      .formParam("Customsearchparameters[6][Value]", "DL")
      .formParam("Customsearchparameters[7][Name]", "EmployeeMove")
      .formParam("Customsearchparameters[7][Value]", "")
      .formParam("Customsearchparameters[8][Name]", "MoveToPayPeriod")
      .formParam("Customsearchparameters[8][Value]", "")
      .formParam("Customsearchparameters[9][Name]", "Employee")
      .formParam("Customsearchparameters[9][Value]", "")
      .formParam("Customsearchparameters[10][Name]", "Transaction")
      .formParam("Customsearchparameters[10][Value]", "${transaction}"))
      .pause(122.milliseconds)
      .exec(http("request_49")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_50")
        .get("/signalr/ping?userid=KM00023&_=1624105644781")
      )
      .exec(http("request_51")
        .post("/PayrollTransaction/DeleteMovePayTransEntry")
      )
      .pause(897.milliseconds)
      .exec(http("request_52")
        .get("/DXR.axd?r=0_2303-O3Vxm"))
      .exec(http("request_53")
        .post("/PayrollTransaction/PartialPayTransGridview")
        .formParam("DXCallbackName", "gvTransaction")
        .formParam("__DXCallbackArgument", """c0:KV|19;[${key}];FR|1;0;GB|19;14|CUSTOMCALLBACK0|;""")
        .formParam("gvTransaction", "{&quot;focusedRow&quot;:0,&quot;keys&quot;:[${key}],&quot;callbackState&quot;:&quot;${callBackState}&quot;,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;TT&quot;,&quot;batchEditClientModifiedValues&quot;:{&quot;ClientState&quot;:{&quot;InsertedIndices&quot;:[],&quot;InsertedValues&quot;:{},&quot;UpdatedValues&quot;:{},&quot;DeletedKeys&quot;:[]},&quot;EditState&quot;:{&quot;insertedRowValues&quot;:{},&quot;modifiedRowValues&quot;:{},&quot;deletedRowKeys&quot;:[]}}}")
        .formParam("gvTransaction$DXEditor1$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor1", "")
        .formParam("gvTransaction$DXEditor2$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor2", "")
        .formParam("gvTransaction$DXEditor2$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor2$DDD$C", "{&quot;visibleDate&quot;:&quot;06/19/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvTransaction$DXEditor2$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor3$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction_DXEditor3_VI", "")
        .formParam("gvTransaction$DXEditor3", "")
        .formParam("gvTransaction$DXEditor3$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor3$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor3$DDD$L", "")
        .formParam("gvTransaction$DXEditor4$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor4", "")
        .formParam("gvTransaction$DXEditor5$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor5", "")
        .formParam("gvTransaction$DXEditor6$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction_DXEditor6_VI", "")
        .formParam("gvTransaction$DXEditor6", "")
        .formParam("gvTransaction$DXEditor6$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor6$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor6$DDD$L", "")
        .formParam("gvTransaction$DXEditor7$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor7", "")
        .formParam("gvTransaction$DXEditor8$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor8", "")
        .formParam("gvTransaction$DXEditor9$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor9", "")
        .formParam("gvTransaction$DXEditor9$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor9$DDD$C", "{&quot;visibleDate&quot;:&quot;06/19/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvTransaction$DXEditor9$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor10$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor10", "")
        .formParam("gvTransaction$DXEditor10$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor10$DDD$C", "{&quot;visibleDate&quot;:&quot;06/28/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/19/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvTransaction$DXEditor10$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor11$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor11", "")
        .formParam("gvTransaction$DXEditor12$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor12", "")
        .formParam("gvTransaction$DXEditor13$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction_DXEditor13_VI", "")
        .formParam("gvTransaction$DXEditor13", "")
        .formParam("gvTransaction$DXEditor13$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor13$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor13$DDD$L", "")
        .formParam("gvTransaction$DXEditor14$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor14", "")
        .formParam("gvTransaction$DXEditor15$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction_DXEditor15_VI", "")
        .formParam("gvTransaction$DXEditor15", "")
        .formParam("gvTransaction$DXEditor15$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor15$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor15$DDD$L", "")
        .formParam("gvTransaction$DXEditor16$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor16", "")
        .formParam("gvTransaction$DXEditor17$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor17", "")
        .formParam("gvTransaction$DXEditor18$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction_DXEditor18_VI", "")
        .formParam("gvTransaction$DXEditor18", "")
        .formParam("gvTransaction$DXEditor18$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvTransaction$DXEditor18$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor18$DDD$L", "")
        .formParam("gvTransaction$DXEditor19$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor19", "I")
        .formParam("gvTransaction$DXEditor20$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvTransaction$DXEditor20", "I")
        .formParam("DXMVCEditorsValues", "{&quot;ProcessOption_DDD_L&quot;:[&quot;D&quot;],&quot;ProcessOption&quot;:&quot;D&quot;,&quot;PayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;PayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;PayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;PayPeriod&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;CurrentPayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;CurrentPayPeriod&quot;:null,&quot;CreatedDateFrom&quot;:new Date(2021,5,19,17,14,45,192),&quot;CreatedDateTo&quot;:new Date(2021,8,28,17,14,45,192),&quot;CreatedBy&quot;:&quot;${idNo}&quot;,&quot;CreationOption&quot;:[&quot;DL&quot;],&quot;EmployeeMove_DDD_gv_DXFREditorcol1&quot;:null,&quot;EmployeeMove_DDD_gv_DXFREditorcol2&quot;:null,&quot;EmployeeMove_DDD_gv_DXFREditorcol3&quot;:null,&quot;EmployeeMove&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol0&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol1&quot;:null,&quot;MoveToPayPeriod_DDD_gv_DXFREditorcol2&quot;:null,&quot;MoveToPayPeriod&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol1&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol2&quot;:null,&quot;Employee_DDD_gv_DXFREditorcol3&quot;:null,&quot;Employee&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol1&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol2&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol3&quot;:null,&quot;Transaction_DDD_gv_DXFREditorcol4&quot;:null,&quot;Transaction&quot;:${transaction}")
        .formParam("DXMVCBatchEditingValuesRequestKey", "gvTransaction")
        .formParam("DXMVCBatchEditingKeyFieldName", "ID")
        .formParam("Customsearchparameters[0][Name]", "ProcessOption")
        .formParam("Customsearchparameters[0][Value]", "D")
        .formParam("Customsearchparameters[1][Name]", "PayPeriod")
        .formParam("Customsearchparameters[1][Value]", "347")
        .formParam("Customsearchparameters[2][Name]", "CurrentPayPeriod")
        .formParam("Customsearchparameters[2][Value]", "")
        .formParam("Customsearchparameters[3][Name]", "CreatedDateFrom")
        .formParam("Customsearchparameters[3][Value]", "2021/06/19")
        .formParam("Customsearchparameters[4][Name]", "CreatedDateTo")
        .formParam("Customsearchparameters[4][Value]", "2021/06/28")
        .formParam("Customsearchparameters[5][Name]", "CreatedBy")
        .formParam("Customsearchparameters[5][Value]", "${idNo}")
        .formParam("Customsearchparameters[6][Name]", "CreationOption")
        .formParam("Customsearchparameters[6][Value]", "DL")
        .formParam("Customsearchparameters[7][Name]", "EmployeeMove")
        .formParam("Customsearchparameters[7][Value]", "")
        .formParam("Customsearchparameters[8][Name]", "MoveToPayPeriod")
        .formParam("Customsearchparameters[8][Value]", "")
        .formParam("Customsearchparameters[9][Name]", "Employee")
        .formParam("Customsearchparameters[9][Value]", "")
        .formParam("Customsearchparameters[10][Name]", "Transaction")
        .formParam("Customsearchparameters[10][Value]", "${transaction}"))
  }

  def logout = {
    exec(http("Submit Logout")
      .post("/Account/LogOff")
      .formParam("__RequestVerificationToken", "${__RequestVerificationTokenLogout}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=Y-cRE08jNAR0IkYEwKTDpwfzJ2kuWuiVp8Nt6e1lBRg1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css")
      .check(status.is(302)))
      .exec(http("request_55")
        .get("/Account/Login")
      )
      .exec(http("request_56")
        .get("/DXR.axd?r=1_58-N3Vxm"))
      .exec(http("request_57")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm"))
      .exec(http("request_58")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1"))
      .exec(http("request_59")
        .get("/bundles/jquery?v=BOadP4NdMhfEAxOx_qgeCESNgZMYYlRzghlNUzq6K-Y1"))
      .exec(http("request_60")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm"))
      .pause(228.milliseconds)
      .exec(http("request_61")
        .get("/Content/Images/bg-login.jpg?V=03"))
      .exec(http("request_62")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
  }


}
