package computerdatabase.Module.payrollObject

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object PayrollFundTransferReport {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Fund Transfer Report")
      .get("/CustomReport/ReportViewerDisplay/fundtransferreport")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
    )
      .exec(http("request_72")
        .get("/signalr/hubs")
      )
      .exec(http("request_73")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(882.milliseconds)
      .exec(http("request_74")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_75")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .exec(http("request_76")
        .get("/DXR.axd?r=0_2314-O3Vxm")
      )
      .exec(http("request_77")
        .get("/DXR.axd?r=0_2216-O3Vxm")
      )
      .pause(274.milliseconds)
      .exec(http("request_78")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_79")
        .get("/DXR.axd?r=0_2303-O3Vxm")
      )
      .exec(http("request_80")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_81")
        .post("/CustomReport/ComboBoxTextDisplay")

        .formParam("objectLabel", "PayrollMonthTo")
        .formParam("comboBoxValue", "5")
        .formParam("textBoxValue", "2021"))
      .exec(http("request_82")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_83")
        .post("/CustomReport/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "CascadePayPeriod")
        .formParam("criteriaObject[Label]", "PayPeriod")
        .formParam("criteriaObject[GroupId]", "1")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "CompanyLocation")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][ParameterName]", "PayrollMonthFromTextBox,PayrollMonthFrom")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterField]", "PAYROLL_YEARMTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][FilterOperator]", "3")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][1][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][ParameterName]", "PayrollMonthToTextBox,PayrollMonthTo")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterField]", "PAYROLL_YEARMTH")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][FilterOperator]", "4")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceName]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][2][TargetDatasourceProperty]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "PayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "PAY_PERIOD_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "350")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "COMPANY.LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "120")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "PayrollMonthFrom")
        .formParam("CustomSearchParameters[0][Value]", "5")
        .formParam("CustomSearchParameters[1][Name]", "PayrollMonthFromTextBox")
        .formParam("CustomSearchParameters[1][Value]", "2021")
        .formParam("CustomSearchParameters[2][Name]", "PayrollMonthTo")
        .formParam("CustomSearchParameters[2][Value]", "5")
        .formParam("CustomSearchParameters[3][Name]", "PayrollMonthToTextBox")
        .formParam("CustomSearchParameters[3][Value]", "2021")
        .formParam("CustomSearchParameters[4][Name]", "CascadePayPeriod")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "Location")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[6][Value]", "|||||||||")
        .formParam("CustomSearchParameters[7][Name]", "Category")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "Grade")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "Employee")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[13][Value]", ""))
      .exec(http("request_84")
        .post("/CustomReport/ComboBoxTextDisplay")

        .formParam("objectLabel", "PayrollMonthFrom")
        .formParam("comboBoxValue", "5")
        .formParam("textBoxValue", "2021"))
      .exec(http("request_85")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_86")
        .post("/CustomReport/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("isAllSelected", "false"))
      .pause(194.milliseconds)
      .exec(http("request_87")
        .get("/Notifications/GetNotificationCounts")
      )
      .exec(http("request_88")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_89")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_90")
        .post("/CustomReport/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "314")
        .formParam("objectSelectedIds[]", "350")
        .formParam("objectSelectedIds[]", "448")
        .formParam("objectSelectedIds[]", "486")
        .formParam("objectSelectedIds[]", "525")
        .formParam("objectSelectedIds[]", "564")
        .formParam("objectSelectedIds[]", "602")
        .formParam("objectSelectedIds[]", "640")
        .formParam("objectSelectedIds[]", "678")
        .formParam("objectSelectedIds[]", "723")
        .formParam("objectSelectedIds[]", "761")
        .formParam("objectSelectedIds[]", "799")
        .formParam("objectSelectedIds[]", "837")
        .formParam("objectSelectedIds[]", "875")
        .formParam("objectSelectedIds[]", "913")
        .formParam("objectSelectedIds[]", "951")
        .formParam("objectSelectedIds[]", "989")
        .formParam("isAllSelected", "true"))
      .exec(http("request_91")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622451190251")
      )
      .pause(2)
      .exec(http("request_92")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=yq0XfjEMV6Itii8U6EFgSbQfZI4BIe6OVA8F7lORlBbkPBflEhruG2ZQQTPIFGBozv6%2FVdX9n55Dtq9hwtQAv9LQBTXds8wi47yFFmnromsdWaycZtXYrE7QEVHwCdZBL8YuOM1xyk5lshJvsv6Yba6vr9EkQZwPbM8NpmgPft8%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622451190252")
      )
      .pause(932.milliseconds)
      .exec(http("request_93")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FCustomReport%2FReportViewerDisplay%2Ffundtransferreport&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._no67bw&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=78842")
      )
      .pause(5)
      .exec(http("request_94")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_95")
        .post("/CustomReport/ReportViewerWithHeaderPartial")

        .formParam("layout[CustomSearchParameters][0][Name]", "PayrollMonthFrom")
        .formParam("layout[CustomSearchParameters][0][Value]", "5")
        .formParam("layout[CustomSearchParameters][1][Name]", "PayrollMonthFromTextBox")
        .formParam("layout[CustomSearchParameters][1][Value]", "2021")
        .formParam("layout[CustomSearchParameters][2][Name]", "PayrollMonthTo")
        .formParam("layout[CustomSearchParameters][2][Value]", "5")
        .formParam("layout[CustomSearchParameters][3][Name]", "PayrollMonthToTextBox")
        .formParam("layout[CustomSearchParameters][3][Value]", "2021")
        .formParam("layout[CustomSearchParameters][4][Name]", "CascadePayPeriod")
        .formParam("layout[CustomSearchParameters][4][Value]", "314,350,448,486,525,564,602,640,678,723,761,799,837,875,913,951,989")
        .formParam("layout[CustomSearchParameters][5][Name]", "Location")
        .formParam("layout[CustomSearchParameters][5][Value]", "")
        .formParam("layout[CustomSearchParameters][6][Name]", "LevelRanges")
        .formParam("layout[CustomSearchParameters][6][Value]", "|||||||||")
        .formParam("layout[CustomSearchParameters][7][Name]", "Category")
        .formParam("layout[CustomSearchParameters][7][Value]", "")
        .formParam("layout[CustomSearchParameters][8][Name]", "Grade")
        .formParam("layout[CustomSearchParameters][8][Value]", "")
        .formParam("layout[CustomSearchParameters][9][Name]", "Employee")
        .formParam("layout[CustomSearchParameters][9][Value]", "")
        .formParam("layout[CustomSearchParameters][10][Name]", "HireDateFrom")
        .formParam("layout[CustomSearchParameters][10][Value]", "")
        .formParam("layout[CustomSearchParameters][11][Name]", "HireDateTo")
        .formParam("layout[CustomSearchParameters][11][Value]", "")
        .formParam("layout[CustomSearchParameters][12][Name]", "TerminationDateFrom")
        .formParam("layout[CustomSearchParameters][12][Value]", "")
        .formParam("layout[CustomSearchParameters][13][Name]", "TerminationDateTo")
        .formParam("layout[CustomSearchParameters][13][Value]", "")
        .formParam("layout[GroupFooterSummaryTextField]", "Entity")
        .formParam("layout[NumberOfVisibleColumns]", "0")
        .formParam("layout[NumberOfGroupedColumns]", "0")
        .formParam("layout[ColumnProperties][0][Visible]", "true")
        .formParam("layout[ColumnProperties][0][Width]", "257")
        .formParam("layout[ColumnProperties][0][VisibleIndex]", "1")
        .formParam("layout[ColumnProperties][0][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][0][FieldName]", "Entity")
        .formParam("layout[ColumnProperties][0][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][0][FieldCaption]", "Entity")
        .formParam("layout[ColumnProperties][0][FieldType]", "")
        .formParam("layout[ColumnProperties][1][Visible]", "true")
        .formParam("layout[ColumnProperties][1][Width]", "100")
        .formParam("layout[ColumnProperties][1][VisibleIndex]", "2")
        .formParam("layout[ColumnProperties][1][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][1][FieldName]", "Type")
        .formParam("layout[ColumnProperties][1][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][1][FieldCaption]", "Type")
        .formParam("layout[ColumnProperties][1][FieldType]", "")
        .formParam("layout[ColumnProperties][2][Visible]", "true")
        .formParam("layout[ColumnProperties][2][Width]", "188")
        .formParam("layout[ColumnProperties][2][VisibleIndex]", "3")
        .formParam("layout[ColumnProperties][2][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][2][FieldName]", "Payment Listing")
        .formParam("layout[ColumnProperties][2][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][2][FieldCaption]", "Payment Listing")
        .formParam("layout[ColumnProperties][2][FieldType]", "")
        .formParam("layout[ColumnProperties][3][Visible]", "true")
        .formParam("layout[ColumnProperties][3][Width]", "222")
        .formParam("layout[ColumnProperties][3][VisibleIndex]", "4")
        .formParam("layout[ColumnProperties][3][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][3][FieldName]", "Jan")
        .formParam("layout[ColumnProperties][3][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][3][FieldCaption]", "Jan")
        .formParam("layout[ColumnProperties][3][FieldType]", "")
        .formParam("layout[ColumnProperties][4][Visible]", "true")
        .formParam("layout[ColumnProperties][4][Width]", "177")
        .formParam("layout[ColumnProperties][4][VisibleIndex]", "5")
        .formParam("layout[ColumnProperties][4][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][4][FieldName]", "Feb")
        .formParam("layout[ColumnProperties][4][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][4][FieldCaption]", "Feb")
        .formParam("layout[ColumnProperties][4][FieldType]", "")
        .formParam("layout[ColumnProperties][5][Visible]", "true")
        .formParam("layout[ColumnProperties][5][Width]", "188")
        .formParam("layout[ColumnProperties][5][VisibleIndex]", "6")
        .formParam("layout[ColumnProperties][5][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][5][FieldName]", "Mar")
        .formParam("layout[ColumnProperties][5][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][5][FieldCaption]", "Mar")
        .formParam("layout[ColumnProperties][5][FieldType]", "")
        .formParam("layout[ColumnProperties][6][Visible]", "true")
        .formParam("layout[ColumnProperties][6][Width]", "196")
        .formParam("layout[ColumnProperties][6][VisibleIndex]", "7")
        .formParam("layout[ColumnProperties][6][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][6][FieldName]", "Apr")
        .formParam("layout[ColumnProperties][6][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][6][FieldCaption]", "Apr")
        .formParam("layout[ColumnProperties][6][FieldType]", "")
        .formParam("layout[ColumnProperties][7][Visible]", "true")
        .formParam("layout[ColumnProperties][7][Width]", "195")
        .formParam("layout[ColumnProperties][7][VisibleIndex]", "8")
        .formParam("layout[ColumnProperties][7][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][7][FieldName]", "May")
        .formParam("layout[ColumnProperties][7][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][7][FieldCaption]", "May")
        .formParam("layout[ColumnProperties][7][FieldType]", "")
        .formParam("layout[ColumnProperties][8][Visible]", "true")
        .formParam("layout[ColumnProperties][8][Width]", "203")
        .formParam("layout[ColumnProperties][8][VisibleIndex]", "9")
        .formParam("layout[ColumnProperties][8][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][8][FieldName]", "Jun")
        .formParam("layout[ColumnProperties][8][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][8][FieldCaption]", "Jun")
        .formParam("layout[ColumnProperties][8][FieldType]", "")
        .formParam("layout[ColumnProperties][9][Visible]", "true")
        .formParam("layout[ColumnProperties][9][Width]", "206")
        .formParam("layout[ColumnProperties][9][VisibleIndex]", "10")
        .formParam("layout[ColumnProperties][9][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][9][FieldName]", "Jul")
        .formParam("layout[ColumnProperties][9][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][9][FieldCaption]", "Jul")
        .formParam("layout[ColumnProperties][9][FieldType]", "")
        .formParam("layout[ColumnProperties][10][Visible]", "true")
        .formParam("layout[ColumnProperties][10][Width]", "235")
        .formParam("layout[ColumnProperties][10][VisibleIndex]", "11")
        .formParam("layout[ColumnProperties][10][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][10][FieldName]", "Aug")
        .formParam("layout[ColumnProperties][10][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][10][FieldCaption]", "Aug")
        .formParam("layout[ColumnProperties][10][FieldType]", "")
        .formParam("layout[ColumnProperties][11][Visible]", "true")
        .formParam("layout[ColumnProperties][11][Width]", "214")
        .formParam("layout[ColumnProperties][11][VisibleIndex]", "12")
        .formParam("layout[ColumnProperties][11][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][11][FieldName]", "Sep")
        .formParam("layout[ColumnProperties][11][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][11][FieldCaption]", "Sep")
        .formParam("layout[ColumnProperties][11][FieldType]", "")
        .formParam("layout[ColumnProperties][12][Visible]", "true")
        .formParam("layout[ColumnProperties][12][Width]", "212")
        .formParam("layout[ColumnProperties][12][VisibleIndex]", "13")
        .formParam("layout[ColumnProperties][12][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][12][FieldName]", "Oct")
        .formParam("layout[ColumnProperties][12][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][12][FieldCaption]", "Oct")
        .formParam("layout[ColumnProperties][12][FieldType]", "")
        .formParam("layout[ColumnProperties][13][Visible]", "true")
        .formParam("layout[ColumnProperties][13][Width]", "195")
        .formParam("layout[ColumnProperties][13][VisibleIndex]", "14")
        .formParam("layout[ColumnProperties][13][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][13][FieldName]", "Nov")
        .formParam("layout[ColumnProperties][13][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][13][FieldCaption]", "Nov")
        .formParam("layout[ColumnProperties][13][FieldType]", "")
        .formParam("layout[ColumnProperties][14][Visible]", "true")
        .formParam("layout[ColumnProperties][14][Width]", "182")
        .formParam("layout[ColumnProperties][14][VisibleIndex]", "15")
        .formParam("layout[ColumnProperties][14][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][14][FieldName]", "Dec")
        .formParam("layout[ColumnProperties][14][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][14][FieldCaption]", "Dec")
        .formParam("layout[ColumnProperties][14][FieldType]", "")
        .formParam("layout[ColumnProperties][15][Visible]", "false")
        .formParam("layout[ColumnProperties][15][Width]", "100")
        .formParam("layout[ColumnProperties][15][VisibleIndex]", "-1")
        .formParam("layout[ColumnProperties][15][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][15][FieldName]", "customer_code")
        .formParam("layout[ColumnProperties][15][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][15][FieldCaption]", "customer_code")
        .formParam("layout[ColumnProperties][15][FieldType]", "R")
        .formParam("layout[ColumnProperties][16][Visible]", "false")
        .formParam("layout[ColumnProperties][16][Width]", "100")
        .formParam("layout[ColumnProperties][16][VisibleIndex]", "-1")
        .formParam("layout[ColumnProperties][16][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][16][FieldName]", "Payroll Year: ")
        .formParam("layout[ColumnProperties][16][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][16][FieldCaption]", "Payroll Year: ")
        .formParam("layout[ColumnProperties][16][FieldType]", "R")
        .formParam("layout[ColumnProperties][17][Visible]", "false")
        .formParam("layout[ColumnProperties][17][Width]", "100")
        .formParam("layout[ColumnProperties][17][VisibleIndex]", "-1")
        .formParam("layout[ColumnProperties][17][GroupIndex]", "-1")
        .formParam("layout[ColumnProperties][17][FieldName]", "Malaysia Operation Division")
        .formParam("layout[ColumnProperties][17][AllowCellMerge]", "false")
        .formParam("layout[ColumnProperties][17][FieldCaption]", "Malaysia Operation Division")
        .formParam("layout[ColumnProperties][17][FieldType]", "R")
        .formParam("layout[GridViewCellStyle][FontSize]", "14")
        .formParam("layout[GridViewExportCellStyle][FontSize]", "14")
        .formParam("layout[ShowGroupSummary]", "False")
        .formParam("layout[ShowTotalSummary]", "False")
        .formParam("layout[GroupSummaryTitleFormat]", "{0}:{1}")
        .formParam("layout[GroupHeaderColumnCount]", "0")
        .formParam("layout[RepeatReportHeader]", "True")
        .formParam("layout[ReportHeaderPageBreak]", "")
        .formParam("layout[ColumnGropingLevelCount]", "0")
        .formParam("layout[RepeatColumnHeader]", "False")
        .formParam("layout[HideDetails]", "False")
        .formParam("TemplateId", "119")
        .formParam("ReportId", "90"))
      .pause(160.milliseconds)
      .exec(http("request_96")
        .get("/DXR.axd?r=24_367-N3Vxm")
      )
      .pause(114.milliseconds)
      .exec(http("request_97")
        .post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")

        .formParam("actionKey", "startBuild")
        .formParam("arg", "%7B%22reportId%22%3A%22da1e055ed36847e69c15b837142bc302%22%2C%22reportUrl%22%3A%22%22%2C%22drillDownKeys%22%3A%5B%5D%2C%22sortingState%22%3A%5B%5D%2C%22timeZoneOffset%22%3A480%2C%22parameters%22%3A%5B%5D%7D"))
      .pause(414.milliseconds)
      .exec(http("request_98")
        .post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")

        .formParam("actionKey", "getBuildStatus")
        .formParam("arg", "%7B%22documentId%22%3A%2261f0f61f55ae4b63927640302e788ad7%22%2C%22timeOut%22%3A120000%7D"))
      .exec(http("request_99")
        .post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")

        .formParam("actionKey", "getDocumentData")
        .formParam("arg", "61f0f61f55ae4b63927640302e788ad7"))

      .exec(http("request_101")
        .post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")

        .formParam("actionKey", "getBrickMap")
        .formParam("arg", "%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%2261f0f61f55ae4b63927640302e788ad7%22%7D"))
      /*		.exec(http("request_102")
            .get("/CustomReport/ReportViewerDisplay/DXXRDV.axd?actionKey=getPage&unifier=42aad8f1-9e16-5407-49c4-d94515890d7e&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%2261f0f61f55ae4b63927640302e788ad7%22%2C%22resolution%22%3A25%7D")
          )*/
      .pause(20)
  }

  def logout = {
    exec(http("Logout Submission")
      .post("/Account/LogOff")

      .formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css,/Content/PayrollProcess.css")
      .check(status.is(302)))
      .exec(http("Login After Logout")
        .get("/Account/Login")
      )
      .exec(http("request_105")
        .get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
      )
      .exec(http("request_106")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_107")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
      )
      .exec(http("request_108")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_109")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
      )
      .exec(http("request_110")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_111")
        .get("/Content/Images/bg-login.jpg?V=03")
      )
  }


}
