package computerdatabase.Module.payrollObject

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object PayrollSpecificTransactionListingReport {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Specific Report Listing Page")
			.get("/CustomReport/ReportViewerDisplay/trx-specific-report")
			.check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
			)
		.exec(http("request_72")
			.get("/signalr/hubs")
			)
		.exec(http("request_73")
			.get("/Content/fonts/icomoon.ttf?5vru0d")
			)
		.pause(886.milliseconds)
		.exec(http("request_74")
			.get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
			)
		.exec(http("request_75")
			.get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
			)
		.exec(http("request_76")
			.get("/DXR.axd?r=0_2314-O3Vxm")
			)
		.exec(http("request_77")
			.get("/DXR.axd?r=0_2216-O3Vxm")
			)
		.exec(http("request_78")
			.get("/DXR.axd?r=0_2316-O3Vxm")
			)
		.pause(275.milliseconds)
		.exec(http("request_79")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_80")
			.get("/DXR.axd?r=0_2303-O3Vxm")
			)
		.exec(http("request_81")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_82")
			.post("/CustomReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "TransType")
			.formParam("isAllSelected", "false"))
		.exec(http("request_83")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_84")
			.post("/CustomReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "TransCode")
			.formParam("isAllSelected", "false"))
		.exec(http("request_85")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_86")
			.post("/CustomReport/CheckBoxListDisplay")
			
			.formParam("objectLabel", "EmployeeStatus")
			.formParam("objectSelectedIds[]", "A")
			.formParam("objectSelectedIds[]", "L")
			.formParam("objectSelectedIds[]", "I"))
		.pause(191.milliseconds)
		.exec(http("request_87")
			.get("/Notifications/GetNotificationCounts")
			)
		.exec(http("request_88")
			.post("/CustomReport/ComboBoxTextDisplay")
			
			.formParam("objectLabel", "PayrollMonth")
			.formParam("comboBoxValue", "5")
			.formParam("textBoxValue", "2021"))
		.exec(http("request_89")
			.get("/Notifications/GetNotificationUserId")
			)
			.exec(http("request_90")
			.get("/signalr/negotiate?clientProtocol=2.1&userid=KM00023&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622451511793")
			)
		.pause(981.milliseconds)
		.exec(http("request_91")
			.get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00023&connectionToken=dm0vWQXMEQwvy8FXDgKtjbrh%2F80HD1kNvwuWK4%2Bm2wU%2BB0bVKIqCjjhV52ka4dEDNqhIuN6Cl3gP9Y1%2FlMUY4esd19WrZ%2BucpgdBYXsWVg74h3HbRkqRdYBzVBisR%2F2Qk2e29T4kPDGmRxE%2B8zmQlOTRXQ5cAxcYo1%2Fvqcjrz%2BU%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1622451511794")
			)
		.pause(1)
		.exec(http("request_92")
			.get("/DXR.axd?r=0_2223-O3Vxm")
			)
		.pause(867.milliseconds)
		.exec(http("request_93")
			.get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FCustomReport%2FReportViewerDisplay%2Ftrx-specific-report&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._mdzl8h&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=77590")
			)
		.pause(129.milliseconds)
		.exec(http("request_94")
			.post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")
			
			.formParam("DXCallbackName", "TransType_DDD_gv")
			.formParam("__DXCallbackArgument", """c0:KV|29;["A","D","O","L","B","N","S"];FR|1;0;GB|31;14|CUSTOMCALLBACK11|GLP_AC|1;A;;""")
			.formParam("TransType$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;A&quot;,&quot;D&quot;,&quot;O&quot;,&quot;L&quot;,&quot;B&quot;,&quot;N&quot;,&quot;S&quot;],&quot;callbackState&quot;:&quot;9rb6j2HcjmglF/D0vgT3RO+KYRSimWN9EKy0DJRJFYmh5Apjv8/VASlBZsLleDR7QBhe+KJ86vvkLdPz7G/oCC8NXeQJmH9sJi+pwWmjhsvwceOj6EHnQ96AY9Jis0LWmzeRUKMbsjS4yKRj7I3tN6nSk/RgjdiVAOgHQ5+NP1p8BaVIdozksikIa9B7laSjmcE5AfGwqgnVaD1mjn2NkT0I7RGWtzZiFyseQY27U+DfNRm8HiKkI2J6cptCbqpNCaTO99OjEq8eK9poPdC5YUSMYbAUlcGLXpPHFFRkHWeGrDGPwekeKp/LtTWJHUpO4sZtb8dcH09U/OPWCck88gnFd/ArB/9NvSxTLyMyzhcmVaWbKg6g91UMGZH1wU1GYb50FLNfMmzuzFfY2sOjRST4+x+1KdZPZTkV3HfBlcSdc7hDmxecbUiY9Pk+srct&quot;,&quot;focusedRow&quot;:0,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:&quot;A&quot;}")
			.formParam("TransType$DDD$gv$DXFREditorcol0", "")
			.formParam("DXMVCEditorsValues", """{"TransMonth_DDD_L":["5"],"TransMonth":"5","TransMonthTextBox":"2021","TransType_DDD_gv_DXFREditorcol0":null,"TransType":null,"TransCode_DDD_gv_DXFREditorcol0":null,"TransCode_DDD_gv_DXFREditorcol1":null,"TransCode_DDD_gv_DXFREditorcol2":null,"TransCode":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null}""")
			.formParam("TransType$State", "{&quot;rawValue&quot;:&quot;Allowance&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:[&quot;A&quot;]}")
			.formParam("TransType", "Allowance")
			.formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"TransType","Label":"TransType","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":{"Id":1,"Title":"Mandatory Selection"},"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"Text","ValueField":"Value","FilterField":null,"FilterFieldList":[],"DatasourceName":"TransactionType","DisplayFormatString":null,"SourceFrom":1,"DefaultIndex":1,"ColumnsList":[{"Name":"Text","Label":"Description","Width":250,"ColumnDisplayFormatString":null}],"CascadeControl":"TransCode","LoadOnDemand":false,"SelectAllMode":false,"DefaultSelectAll":false,"IsMultiSelection":false,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
			.formParam("ParentId", "")
			.formParam("CustomSearchParameters[0][Name]", "TransMonth")
			.formParam("CustomSearchParameters[0][Value]", "5")
			.formParam("CustomSearchParameters[1][Name]", "TransMonthTextBox")
			.formParam("CustomSearchParameters[1][Value]", "2021")
			.formParam("CustomSearchParameters[2][Name]", "TransType")
			.formParam("CustomSearchParameters[2][Value]", "")
			.formParam("CustomSearchParameters[3][Name]", "TransCode")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", ""))
		.exec(http("request_95")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_96")
			.post("/CustomReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "TransType")
			.formParam("objectSelectedIds[]", "A")
			.formParam("isAllSelected", "false"))
		.exec(http("request_97")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_98")
			.post("/CustomReport/GetCascadeChildDropdown")
			
			.formParam("criteriaObject[Type]", "CascadeComboBox")
			.formParam("criteriaObject[Name]", "TransCode")
			.formParam("criteriaObject[Label]", "TransCode")
			.formParam("criteriaObject[GroupId]", "1")
			.formParam("criteriaObject[IsRequired]", "False")
			.formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "LONG_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "TRX_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "TRX_TYPE")
			.formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "TransactionwithStatutory")
			.formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{1}")
			.formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "TRX_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "Code")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "100")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "LONG_DESCRIPTION")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Description")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "250")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Name]", "LOCATION_CODE")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Label]", "Company")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Width]", "90")
			.formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][ColumnDisplayFormatString]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
			.formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "true")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "false")
			.formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "false")
			.formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "false")
			.formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
			.formParam("ParentId[]", "A")
			.formParam("CustomSearchParameters[0][Name]", "TransMonth")
			.formParam("CustomSearchParameters[0][Value]", "5")
			.formParam("CustomSearchParameters[1][Name]", "TransMonthTextBox")
			.formParam("CustomSearchParameters[1][Value]", "2021")
			.formParam("CustomSearchParameters[2][Name]", "TransType")
			.formParam("CustomSearchParameters[2][Value]", "A")
			.formParam("CustomSearchParameters[3][Name]", "TransCode")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", ""))
		.exec(http("request_99")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_100")
			.post("/CustomReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "TransCode")
			.formParam("isAllSelected", "false"))
		.pause(4)
		.exec(http("request_101")
			.post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")
			
			.formParam("DXCallbackName", "TransCode_DDD_gv")
			.formParam("__DXCallbackArgument", """c0:KV|751;["AABP","AAFA","AAHP","AAOC","AASA","AASC","AAUL","ACTI01A","AFDA007","ANGI050","ARRA000","ARRS000","ASNU050","BAAA","BAAL","BABA","BABP","BACA","BACL000","BADA","BADB","BADC","BADD","BADE","BAFB","BAFC","BAGA","BAHA","BAIF","BALA","BALB","BALC","BALD","BALP","BAMA","BAMB","BAMC","BAMD","BAPA","BAPB","BAQA","BAQB","BARB","BATA","BONE003","BPBS","CAAB","CAAC","CAAD","CAAE","CAAT","CABB","CABD","CABE","CABI","CABM","CABP","CACA","CADR","CADV","CAIA","CALA","CALB","CALC","CALF000","CALL","CALL020","CALL045","CAMA","CAMC","CAMS","CANL","CANR","CANS","CANT","CAON","CAPC","CAPN","CARA","CARB","CARC","CARD","CARD000","CASA","CASC","CASH01A","CASH150","CASP","CATC","CATL","CATR","CAUP","CAWP","CBD","CBOI","CCAL","CDRA008","CERT300","CHEM010","CICP"];FR|1;1;GB|34;14|CUSTOMCALLBACK14|GLP_AC|4;AAFA;;""")
			.formParam("TransCode$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;AABP&quot;,&quot;AAFA&quot;,&quot;AAHP&quot;,&quot;AAOC&quot;,&quot;AASA&quot;,&quot;AASC&quot;,&quot;AAUL&quot;,&quot;ACTI01A&quot;,&quot;AFDA007&quot;,&quot;ANGI050&quot;,&quot;ARRA000&quot;,&quot;ARRS000&quot;,&quot;ASNU050&quot;,&quot;BAAA&quot;,&quot;BAAL&quot;,&quot;BABA&quot;,&quot;BABP&quot;,&quot;BACA&quot;,&quot;BACL000&quot;,&quot;BADA&quot;,&quot;BADB&quot;,&quot;BADC&quot;,&quot;BADD&quot;,&quot;BADE&quot;,&quot;BAFB&quot;,&quot;BAFC&quot;,&quot;BAGA&quot;,&quot;BAHA&quot;,&quot;BAIF&quot;,&quot;BALA&quot;,&quot;BALB&quot;,&quot;BALC&quot;,&quot;BALD&quot;,&quot;BALP&quot;,&quot;BAMA&quot;,&quot;BAMB&quot;,&quot;BAMC&quot;,&quot;BAMD&quot;,&quot;BAPA&quot;,&quot;BAPB&quot;,&quot;BAQA&quot;,&quot;BAQB&quot;,&quot;BARB&quot;,&quot;BATA&quot;,&quot;BONE003&quot;,&quot;BPBS&quot;,&quot;CAAB&quot;,&quot;CAAC&quot;,&quot;CAAD&quot;,&quot;CAAE&quot;,&quot;CAAT&quot;,&quot;CABB&quot;,&quot;CABD&quot;,&quot;CABE&quot;,&quot;CABI&quot;,&quot;CABM&quot;,&quot;CABP&quot;,&quot;CACA&quot;,&quot;CADR&quot;,&quot;CADV&quot;,&quot;CAIA&quot;,&quot;CALA&quot;,&quot;CALB&quot;,&quot;CALC&quot;,&quot;CALF000&quot;,&quot;CALL&quot;,&quot;CALL020&quot;,&quot;CALL045&quot;,&quot;CAMA&quot;,&quot;CAMC&quot;,&quot;CAMS&quot;,&quot;CANL&quot;,&quot;CANR&quot;,&quot;CANS&quot;,&quot;CANT&quot;,&quot;CAON&quot;,&quot;CAPC&quot;,&quot;CAPN&quot;,&quot;CARA&quot;,&quot;CARB&quot;,&quot;CARC&quot;,&quot;CARD&quot;,&quot;CARD000&quot;,&quot;CASA&quot;,&quot;CASC&quot;,&quot;CASH01A&quot;,&quot;CASH150&quot;,&quot;CASP&quot;,&quot;CATC&quot;,&quot;CATL&quot;,&quot;CATR&quot;,&quot;CAUP&quot;,&quot;CAWP&quot;,&quot;CBD&quot;,&quot;CBOI&quot;,&quot;CCAL&quot;,&quot;CDRA008&quot;,&quot;CERT300&quot;,&quot;CHEM010&quot;,&quot;CICP&quot;],&quot;callbackState&quot;:&quot;E8jDYTjFVpvn1uMJPI5MmL27w4+8u3pY+LC5W392fxcGDrColnkDnkd+4jGO8hZcL/uv13K9k9AIzzmd/zkwceM68jKfANyZWscupqxkT1rkWKbBgF/2apgJE1nKH58/5p83uB+xy4uqnz+4aGmrWoCf6gmjOg7hH30yBBBjWJF02up3V9nrAYAm3mJZmWF/srPEsrdSmMKH2PhJIjck7eXCR1fe5n5RWcY41syXo8PWKJKjsn06GwcaO/JJW9TngX2L5IMe64PFzx3zeSkaZzsz5QDos0/JDMJi8PKTo4BKIPT9PUUJr2ESnHiLlgg01s6LkzhLm1Cbf8HjHqaB+eDzb2HVYidSuqll2ijVlhJAD6oOWQeAiPDDp8EupgYsBhqIBiSuDdqOVhhE9UwPi9fYvNSyc6aZIVMoPLUrrivyZfFJVlNE+0DCTccXM4WRMVZ28pNFaT/UrlT4H2d1eA==&quot;,&quot;focusedRow&quot;:1,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:&quot;AAFA&quot;}")
			.formParam("TransCode$DDD$gv$DXFREditorcol0", "")
			.formParam("TransCode$DDD$gv$DXFREditorcol1", "")
			.formParam("TransCode$DDD$gv$DXFREditorcol2", "")
			.formParam("DXMVCEditorsValues", """{"TransMonth_DDD_L":["5"],"TransMonth":"5","TransMonthTextBox":"2021","TransType_DDD_gv_DXFREditorcol0":null,"TransType":["A"],"TransCode_DDD_gv_DXFREditorcol0":null,"TransCode_DDD_gv_DXFREditorcol1":null,"TransCode_DDD_gv_DXFREditorcol2":null,"TransCode":null,"EmployeeStatus":["A","L","I"],"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null}""")
			.formParam("TransCode$State", "{&quot;rawValue&quot;:&quot;TRANSPORT ALLOWANCE&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:[&quot;AAFA&quot;]}")
			.formParam("TransCode", "TRANSPORT ALLOWANCE")
			.formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"TransCode","Label":"TransCode","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":null,"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"LONG_DESCRIPTION","ValueField":"TRX_CODE","FilterField":"TRX_TYPE","FilterFieldList":[],"DatasourceName":"TransactionwithStatutory","DisplayFormatString":"{1}","SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"TRX_CODE","Label":"Code","Width":100,"ColumnDisplayFormatString":null},{"Name":"LONG_DESCRIPTION","Label":"Description","Width":250,"ColumnDisplayFormatString":null},{"Name":"LOCATION_CODE","Label":"Company","Width":90,"ColumnDisplayFormatString":null}],"CascadeControl":null,"LoadOnDemand":false,"SelectAllMode":false,"DefaultSelectAll":false,"IsMultiSelection":false,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
			.formParam("ParentId[]", "A")
			.formParam("CustomSearchParameters[0][Name]", "TransMonth")
			.formParam("CustomSearchParameters[0][Value]", "5")
			.formParam("CustomSearchParameters[1][Name]", "TransMonthTextBox")
			.formParam("CustomSearchParameters[1][Value]", "2021")
			.formParam("CustomSearchParameters[2][Name]", "TransType")
			.formParam("CustomSearchParameters[2][Value]", "A")
			.formParam("CustomSearchParameters[3][Name]", "TransCode")
			.formParam("CustomSearchParameters[3][Value]", "")
			.formParam("CustomSearchParameters[4][Name]", "EmployeeStatus")
			.formParam("CustomSearchParameters[4][Value]", "A,L,I")
			.formParam("CustomSearchParameters[5][Name]", "Location")
			.formParam("CustomSearchParameters[5][Value]", "")
			.formParam("CustomSearchParameters[6][Name]", "LevelRanges")
			.formParam("CustomSearchParameters[6][Value]", "|||||||||")
			.formParam("CustomSearchParameters[7][Name]", "Category")
			.formParam("CustomSearchParameters[7][Value]", "")
			.formParam("CustomSearchParameters[8][Name]", "Grade")
			.formParam("CustomSearchParameters[8][Value]", "")
			.formParam("CustomSearchParameters[9][Name]", "Employee")
			.formParam("CustomSearchParameters[9][Value]", "")
			.formParam("CustomSearchParameters[10][Name]", "HireDateFrom")
			.formParam("CustomSearchParameters[10][Value]", "")
			.formParam("CustomSearchParameters[11][Name]", "HireDateTo")
			.formParam("CustomSearchParameters[11][Value]", "")
			.formParam("CustomSearchParameters[12][Name]", "TerminationDateFrom")
			.formParam("CustomSearchParameters[12][Value]", "")
			.formParam("CustomSearchParameters[13][Name]", "TerminationDateTo")
			.formParam("CustomSearchParameters[13][Value]", ""))
		.exec(http("request_102")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_103")
			.post("/CustomReport/CascadeComboBoxDisplay")
			
			.formParam("objectLabel", "TransCode")
			.formParam("objectSelectedIds[]", "AAFA")
			.formParam("isAllSelected", "false"))
		.pause(1)
		.exec(http("request_104")
			.post("/Account/VerifyAccess")
			)
		.exec(http("request_105")
			.post("/CustomReport/ReportViewerWithHeaderPartial")
			
			.formParam("layout[GroupSummary][0][ColumnName]", "Employee Name")
			.formParam("layout[GroupSummary][0][SummaryType]", "Count")
			.formParam("layout[GroupSummary][1][ColumnName]", "Local Amount")
			.formParam("layout[GroupSummary][1][SummaryType]", "Sum")
			.formParam("layout[CustomSearchParameters][0][Name]", "TransMonth")
			.formParam("layout[CustomSearchParameters][0][Value]", "5")
			.formParam("layout[CustomSearchParameters][1][Name]", "TransMonthTextBox")
			.formParam("layout[CustomSearchParameters][1][Value]", "2021")
			.formParam("layout[CustomSearchParameters][2][Name]", "TransType")
			.formParam("layout[CustomSearchParameters][2][Value]", "A")
			.formParam("layout[CustomSearchParameters][3][Name]", "TransCode")
			.formParam("layout[CustomSearchParameters][3][Value]", "AAFA")
			.formParam("layout[CustomSearchParameters][4][Name]", "EmployeeStatus")
			.formParam("layout[CustomSearchParameters][4][Value]", "A,L,I")
			.formParam("layout[CustomSearchParameters][5][Name]", "Location")
			.formParam("layout[CustomSearchParameters][5][Value]", "")
			.formParam("layout[CustomSearchParameters][6][Name]", "LevelRanges")
			.formParam("layout[CustomSearchParameters][6][Value]", "|||||||||")
			.formParam("layout[CustomSearchParameters][7][Name]", "Category")
			.formParam("layout[CustomSearchParameters][7][Value]", "")
			.formParam("layout[CustomSearchParameters][8][Name]", "Grade")
			.formParam("layout[CustomSearchParameters][8][Value]", "")
			.formParam("layout[CustomSearchParameters][9][Name]", "Employee")
			.formParam("layout[CustomSearchParameters][9][Value]", "")
			.formParam("layout[CustomSearchParameters][10][Name]", "HireDateFrom")
			.formParam("layout[CustomSearchParameters][10][Value]", "")
			.formParam("layout[CustomSearchParameters][11][Name]", "HireDateTo")
			.formParam("layout[CustomSearchParameters][11][Value]", "")
			.formParam("layout[CustomSearchParameters][12][Name]", "TerminationDateFrom")
			.formParam("layout[CustomSearchParameters][12][Value]", "")
			.formParam("layout[CustomSearchParameters][13][Name]", "TerminationDateTo")
			.formParam("layout[CustomSearchParameters][13][Value]", "")
			.formParam("layout[GroupFooterSummaryTextField]", "Employee No.")
			.formParam("layout[NumberOfVisibleColumns]", "0")
			.formParam("layout[NumberOfGroupedColumns]", "0")
			.formParam("layout[ColumnProperties][0][Visible]", "true")
			.formParam("layout[ColumnProperties][0][Width]", "127")
			.formParam("layout[ColumnProperties][0][VisibleIndex]", "0")
			.formParam("layout[ColumnProperties][0][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][0][FieldName]", "Employee No.")
			.formParam("layout[ColumnProperties][0][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][0][FieldCaption]", "Employee No.")
			.formParam("layout[ColumnProperties][0][FieldType]", "")
			.formParam("layout[ColumnProperties][1][Visible]", "true")
			.formParam("layout[ColumnProperties][1][Width]", "450")
			.formParam("layout[ColumnProperties][1][VisibleIndex]", "1")
			.formParam("layout[ColumnProperties][1][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][1][FieldName]", "Employee Name")
			.formParam("layout[ColumnProperties][1][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][1][FieldCaption]", "Employee Name")
			.formParam("layout[ColumnProperties][1][FieldType]", "")
			.formParam("layout[ColumnProperties][2][Visible]", "true")
			.formParam("layout[ColumnProperties][2][Width]", "100")
			.formParam("layout[ColumnProperties][2][VisibleIndex]", "2")
			.formParam("layout[ColumnProperties][2][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][2][FieldName]", "Currency")
			.formParam("layout[ColumnProperties][2][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][2][FieldCaption]", "Currency")
			.formParam("layout[ColumnProperties][2][FieldType]", "")
			.formParam("layout[ColumnProperties][3][Visible]", "true")
			.formParam("layout[ColumnProperties][3][Width]", "100")
			.formParam("layout[ColumnProperties][3][VisibleIndex]", "3")
			.formParam("layout[ColumnProperties][3][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][3][FieldName]", "Qty")
			.formParam("layout[ColumnProperties][3][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][3][FieldCaption]", "Qty")
			.formParam("layout[ColumnProperties][3][FieldType]", "")
			.formParam("layout[ColumnProperties][4][Visible]", "true")
			.formParam("layout[ColumnProperties][4][Width]", "100")
			.formParam("layout[ColumnProperties][4][VisibleIndex]", "4")
			.formParam("layout[ColumnProperties][4][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][4][FieldName]", "Rate")
			.formParam("layout[ColumnProperties][4][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][4][FieldCaption]", "Rate")
			.formParam("layout[ColumnProperties][4][FieldType]", "")
			.formParam("layout[ColumnProperties][5][Visible]", "true")
			.formParam("layout[ColumnProperties][5][Width]", "120")
			.formParam("layout[ColumnProperties][5][VisibleIndex]", "5")
			.formParam("layout[ColumnProperties][5][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][5][FieldName]", "Trans. Amount")
			.formParam("layout[ColumnProperties][5][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][5][FieldCaption]", "Trans. Amount")
			.formParam("layout[ColumnProperties][5][FieldType]", "")
			.formParam("layout[ColumnProperties][6][Visible]", "true")
			.formParam("layout[ColumnProperties][6][Width]", "120")
			.formParam("layout[ColumnProperties][6][VisibleIndex]", "6")
			.formParam("layout[ColumnProperties][6][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][6][FieldName]", "Exch. Rate")
			.formParam("layout[ColumnProperties][6][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][6][FieldCaption]", "Exch. Rate")
			.formParam("layout[ColumnProperties][6][FieldType]", "")
			.formParam("layout[ColumnProperties][7][Visible]", "true")
			.formParam("layout[ColumnProperties][7][Width]", "150")
			.formParam("layout[ColumnProperties][7][VisibleIndex]", "7")
			.formParam("layout[ColumnProperties][7][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][7][FieldName]", "Local Amount")
			.formParam("layout[ColumnProperties][7][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][7][FieldCaption]", "Local Amount")
			.formParam("layout[ColumnProperties][7][FieldType]", "")
			.formParam("layout[ColumnProperties][8][Visible]", "false")
			.formParam("layout[ColumnProperties][8][Width]", "100")
			.formParam("layout[ColumnProperties][8][VisibleIndex]", "-1")
			.formParam("layout[ColumnProperties][8][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][8][FieldName]", "Country, Currency")
			.formParam("layout[ColumnProperties][8][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][8][FieldCaption]", "Country, Currency")
			.formParam("layout[ColumnProperties][8][FieldType]", "R")
			.formParam("layout[ColumnProperties][9][Visible]", "false")
			.formParam("layout[ColumnProperties][9][Width]", "100")
			.formParam("layout[ColumnProperties][9][VisibleIndex]", "-1")
			.formParam("layout[ColumnProperties][9][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][9][FieldName]", "Entity")
			.formParam("layout[ColumnProperties][9][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][9][FieldCaption]", "Entity")
			.formParam("layout[ColumnProperties][9][FieldType]", "R")
			.formParam("layout[ColumnProperties][10][Visible]", "false")
			.formParam("layout[ColumnProperties][10][Width]", "100")
			.formParam("layout[ColumnProperties][10][VisibleIndex]", "-1")
			.formParam("layout[ColumnProperties][10][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][10][FieldName]", "Payroll Month")
			.formParam("layout[ColumnProperties][10][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][10][FieldCaption]", "Payroll Month")
			.formParam("layout[ColumnProperties][10][FieldType]", "R")
			.formParam("layout[ColumnProperties][11][Visible]", "false")
			.formParam("layout[ColumnProperties][11][Width]", "100")
			.formParam("layout[ColumnProperties][11][VisibleIndex]", "-1")
			.formParam("layout[ColumnProperties][11][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][11][FieldName]", "Trans. Desc")
			.formParam("layout[ColumnProperties][11][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][11][FieldCaption]", "Trans. Desc")
			.formParam("layout[ColumnProperties][11][FieldType]", "R")
			.formParam("layout[ColumnProperties][12][Visible]", "false")
			.formParam("layout[ColumnProperties][12][Width]", "100")
			.formParam("layout[ColumnProperties][12][VisibleIndex]", "-1")
			.formParam("layout[ColumnProperties][12][GroupIndex]", "-1")
			.formParam("layout[ColumnProperties][12][FieldName]", "Employee Location")
			.formParam("layout[ColumnProperties][12][AllowCellMerge]", "false")
			.formParam("layout[ColumnProperties][12][FieldCaption]", "Employee Location")
			.formParam("layout[ColumnProperties][12][FieldType]", "R")
			.formParam("layout[GridViewCellStyle][FontSize]", "10")
			.formParam("layout[GridViewExportCellStyle][FontSize]", "10")
			.formParam("layout[ShowGroupSummary]", "False")
			.formParam("layout[ShowTotalSummary]", "True")
			.formParam("layout[GroupSummaryTitleFormat]", "{0}:{1}")
			.formParam("layout[GroupHeaderColumnCount]", "0")
			.formParam("layout[RepeatReportHeader]", "False")
			.formParam("layout[ReportHeaderPageBreak]", "")
			.formParam("layout[ColumnGropingLevelCount]", "0")
			.formParam("layout[RepeatColumnHeader]", "False")
			.formParam("layout[HideDetails]", "False")
			.formParam("TemplateId", "44")
			.formParam("ReportId", "34"))
		.pause(159.milliseconds)
		.exec(http("request_106")
			.get("/DXR.axd?r=24_367-N3Vxm")
			)
		.pause(117.milliseconds)
		.exec(http("request_107")
			.post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")
			
			.formParam("actionKey", "startBuild")
			.formParam("arg", "%7B%22reportId%22%3A%220877fb36edff4909bc9f4f491daec5e7%22%2C%22reportUrl%22%3A%22%22%2C%22drillDownKeys%22%3A%5B%5D%2C%22sortingState%22%3A%5B%5D%2C%22timeZoneOffset%22%3A480%2C%22parameters%22%3A%5B%5D%7D"))
		.pause(367.milliseconds)
		.exec(http("request_108")
			.post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")
			
			.formParam("actionKey", "getBuildStatus")
			.formParam("arg", "%7B%22documentId%22%3A%222f56ce63ae834ed288b013a29c71e539%22%2C%22timeOut%22%3A120000%7D"))
		.exec(http("request_109")
			.post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")
			
			.formParam("actionKey", "getDocumentData")
			.formParam("arg", "2f56ce63ae834ed288b013a29c71e539"))
/*		.exec(http("request_110")
			.get("/CustomReport/ReportViewerDisplay/DXXRDV.axd?actionKey=getPage&unifier=70a0a89f-0868-0da4-81b1-aab15c4d4887&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%222f56ce63ae834ed288b013a29c71e539%22%2C%22resolution%22%3A96%7D")
			)*/
		.exec(http("request_111")
			.post("/CustomReport/ReportViewerDisplay/DXXRDV.axd")
			
			.formParam("actionKey", "getBrickMap")
			.formParam("arg", "%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%222f56ce63ae834ed288b013a29c71e539%22%7D"))
/*		.exec(http("request_112")
			.get("/CustomReport/ReportViewerDisplay/DXXRDV.axd?actionKey=getPage&unifier=70a0a89f-0868-0da4-81b1-aab15c4d4887&arg=%7B%22pageIndex%22%3A0%2C%22documentId%22%3A%222f56ce63ae834ed288b013a29c71e539%22%2C%22resolution%22%3A59%7D")
			)*/
		.pause(15)
      }

  def logout = {
    exec(http("Logout Submission")
			.post("/Account/LogOff")
			
			.formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
			.formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
			.formParam("DXCss", "/Content/css/root?v=fQqb8rdb3SX3t_q5clLhrjqLMPJRz5XyrffvnRHeaqY1,0_2312,1_50,1_53,1_51,0_2317,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css,/Content/jquery-ui.css,/Content/PayrollProcess.css")
			.check(status.is(302)))
		.exec(http("Login After Logout")
			.get("/Account/Login")
			)
		.exec(http("request_115")
			.get("/bundles/jquery?v=_pxGe3mY2bQf-xjm4AiFp6ZjEyA5oTa8PuEQsuJbzEk1")
			)
		.exec(http("request_116")
			.get("/DXR.axd?r=1_58-N3Vxm")
			)
		.exec(http("request_117")
			.get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
			)
		.exec(http("request_118")
			.get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
			)
		.exec(http("request_119")
			.get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
			)
		.exec(http("request_120")
			.get("/Content/fonts/icomoon.ttf?5vru0d")
			)
		.exec(http("request_121")
			.get("/Content/Images/bg-login.jpg?V=03")
			)

  }




}
