package computerdatabase.Module.Leave

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

object LeavePostedListing {

  val uri1 = "https://maps.googleapis.com/maps/api/js"
  val uri3 = "https://fonts.googleapis.com/css"

  def loadApplication = {
    exec(http("Leave Posted Listing")
      .get("/Leave/LeavePostedListing")
      .check(regex("""<input name="__RequestVerificationToken" type="hidden" value="(.+?)" />""").find.saveAs("__RequestVerificationToken2"))
    )
      .exec(http("request_66")
        .get("/signalr/hubs")
      )
      .exec(http("request_67")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .pause(892.milliseconds)
      .exec(http("request_68")
        .get("/profile_picture.ashx?EmployeeID=9126")
      )
      .exec(http("request_69")
        .get("/Scripts/MasterDevExBundle?v=h24JJD8hLg2uCOXtSNYJSvolBvJAIdCvb-_JDWPC9d41")
      )
      .exec(http("request_70")
        .get("/DXR.axd?r=0_5687-O3Vxm")
      )
      .exec(http("request_71")
        .get("/DXR.axd?r=0_2314-O3Vxm")
      )
      .exec(http("request_72")
        .get("/DXR.axd?r=0_2218-O3Vxm")
      )
      .exec(http("request_73")
        .get("/DXR.axd?r=0_2216-O3Vxm")
      )
      .exec(http("request_74")
        .get("/DXR.axd?r=0_2316-O3Vxm")
      )
      .exec(http("request_75")
        .get(uri1 + "?key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A")
      )
      .exec(http("request_76")
        .get("/Scripts/RootBundle?v=Z5MJwH8Xi0bCONWdJcmOtX_Ca81BpX4JptdIbZb919g1")
      )
      .pause(219.milliseconds)
      .exec(http("request_77")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_78")
        .get("/DXR.axd?r=0_2303-O3Vxm")
      )
      .exec(http("request_79")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_80")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_81")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_82")
        .post("/LeavePostedListing/CascadeComboBoxDisplay")

        .formParam("objectLabel", "LeaveType")
        .formParam("isAllSelected", "false"))
      .pause(169.milliseconds)
      .exec(http("request_83")
        .get("/Notifications/GetNotificationUserId")
      )
      .exec(http("request_84")
        .get("/signalr/negotiate?clientProtocol=2.1&userid=KM00562&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1623314593241")
      )
      .exec(http("request_85")
        .post("/LeavePostedListing/RadioButtonListDisplay")

        .formParam("objectLabel", "LeavePostedListingType")
        .formParam("radioButtonValue", "L"))
      .exec(http("request_86")
        .post("/LeavePostedListing/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("isAllSelected", "false"))
      .exec(http("request_87")
        .post("/LeavePostedListing/CheckBoxListDisplay")

        .formParam("objectLabel", "EmployeeStatus")
        .formParam("objectSelectedIds[]", "A")
        .formParam("objectSelectedIds[]", "L")
        .formParam("objectSelectedIds[]", "I"))
      .exec(http("request_88")
        .get("/Notifications/GetNotificationCounts")
      )
      .pause(907.milliseconds)
      .exec(http("request_89")
        .get("/DXR.axd?r=0_2223-O3Vxm")
      )
      .pause(1)
      .exec(http("request_90")
        .get("/signalr/start?transport=webSockets&clientProtocol=2.1&userid=KM00562&connectionToken=nc7GhIHoozIziWqjo4ZJrJIDv2yzZz1m9920p1wVpO%2FlCv%2BPG%2BQPZs1IVsSjIjmfjlfcKkrCUaiEGig11SOMJeRtb2iIGGzU0Zwj1NrUCXwLOnGCy3prUaD4r9QUHAtJcS5r%2BKFY2px1zuf7ogjBxM8Fgk%2FTMxEslZf6f8PIHgk%3D&connectionData=%5B%7B%22name%22%3A%22notificationhub%22%7D%5D&_=1623314593242")
      )
      .pause(1)
      .exec(http("request_91")
        .get(uri1 + "/AuthenticationService.Authenticate?1shttps%3A%2F%2Forisoftst.orisoftsaas.com%2FLeave%2FLeavePostedListing&4sAIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&callback=_xdc_._ua56y2&key=AIzaSyDu3r6sgbYDPJTjUH9Dun7RSWAyB5aQi8A&token=125677")
      )
      .pause(1)
      .exec(http("request_92")
        .post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")

        .formParam("DXCallbackName", "PayPeriod_DDD_gv")
        .formParam("__DXCallbackArgument", """c0:KV|219;["1030","1031","347","834","796","872","637","910","720","758","348","987","835","676","312","446","600","484","797","523","949","873","562","638","911","721","759","988","677","313","447","601","485","524","950","563"];FR|2;-1;GB|28;17|APPLYCOLUMNFILTER1|13|phi;""")
        .formParam("PayPeriod$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;1030&quot;,&quot;1031&quot;,&quot;347&quot;,&quot;834&quot;,&quot;796&quot;,&quot;872&quot;,&quot;637&quot;,&quot;910&quot;,&quot;720&quot;,&quot;758&quot;,&quot;348&quot;,&quot;987&quot;,&quot;835&quot;,&quot;676&quot;,&quot;312&quot;,&quot;446&quot;,&quot;600&quot;,&quot;484&quot;,&quot;797&quot;,&quot;523&quot;,&quot;949&quot;,&quot;873&quot;,&quot;562&quot;,&quot;638&quot;,&quot;911&quot;,&quot;721&quot;,&quot;759&quot;,&quot;988&quot;,&quot;677&quot;,&quot;313&quot;,&quot;447&quot;,&quot;601&quot;,&quot;485&quot;,&quot;524&quot;,&quot;950&quot;,&quot;563&quot;],&quot;callbackState&quot;:&quot;zfzNZppRKdV3uQfJe8JR9W5vh+K3Pq00uR6J5tgpOa+kN0oALdVBqY2+Uibwh5fZB9E9X5u8kHND9GUOVTfBmVMxeFZNnGRKJ1Fjid8m6yNWdnSjX+iiOhj5Kt28bEZlUB4hd3sj9ALy84+9iDczwdaWMQhfhRF+ei+AzYejZL9abj4L7vlUz8LCm1F9jpJEVHJ1ZNfC5eSJkh9f8/7XZklKbRhJFF/vyjQBWT/EbdgQhjT/SYqtmP8Xdokym1c6mc+f23bq5nLUX/TUthOfEIUXBlpnDV77lQpRgLtvwvVwBCNk4zt6xS3R+1EtGZrCb4N0anw8/XAzwzpdY736cYRUzxRQeG9zy5o6o9he3iljyH2Ik1qH7Df8LMn3L8tZuWCSE3PIDyDPpT9RZxttwmXrzmjF6OVZlBcdJrOeEXBmEVTA2gIoQNx37cSNyqdC&quot;,&quot;focusedRow&quot;:-1,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol0", "")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol1", "phi")
        .formParam("DXMVCEditorsValues", """{"LeavePostedListingType":"L","PayPeriod_DDD_gv_DXFREditorcol0":null,"PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod":null,"EmployeeStatus":["A","L","I"],"RequestId":null,"Leave_DDD_gv_DXFREditorcol1":null,"Leave_DDD_gv_DXFREditorcol2":null,"Leave_DDD_gv_DXFREditorcol3":null,"Leave":null,"LeaveType_DDD_gv_DXFREditorcol0":null,"LeaveType_DDD_gv_DXFREditorcol1":null,"LeaveType_DDD_gv_DXFREditorcol2":null,"LeaveType":null,"LeaveDateFrom":null,"LeaveDateTo":null,"SubmissionDateFrom":null,"SubmissionDateTo":null,"PostingDateFrom":null,"PostingDateTo":null,"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null}""")
        .formParam("PayPeriod$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:null}")
        .formParam("PayPeriod", "Please Select")
        .formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"PayPeriod","Label":"PayPeriod","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":null,"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"PAY_PERIOD_DESCRIPTION","ValueField":"ID","FilterField":null,"FilterFieldList":[],"DatasourceName":"CurrentMonthPayPeriods","DisplayFormatString":"{0}","SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"PAY_PERIOD_DESCRIPTION","Label":"Description","Width":250,"ColumnDisplayFormatString":null},{"Name":"COMPANY.LOCATION_CODE","Label":"Company","Width":100,"ColumnDisplayFormatString":null}],"CascadeControl":"LeaveType","LoadOnDemand":false,"SelectAllMode":false,"DefaultSelectAll":false,"IsMultiSelection":false,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "LeavePostedListingType")
        .formParam("CustomSearchParameters[0][Value]", "L")
        .formParam("CustomSearchParameters[1][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[1][Value]", "")
        .formParam("CustomSearchParameters[2][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[2][Value]", "A,L,I")
        .formParam("CustomSearchParameters[3][Name]", "RequestId")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "Leave")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "LeaveType")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LeaveDateFrom")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LeaveDateTo")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "SubmissionDateFrom")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "SubmissionDateTo")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "PostingDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "PostingDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "Location")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[13][Value]", "|||||||||")
        .formParam("CustomSearchParameters[14][Name]", "Category")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "Grade")
        .formParam("CustomSearchParameters[15][Value]", "")
        .formParam("CustomSearchParameters[16][Name]", "Employee")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[17][Value]", "")
        .formParam("CustomSearchParameters[18][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[18][Value]", "")
        .formParam("CustomSearchParameters[19][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[19][Value]", "")
        .formParam("CustomSearchParameters[20][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[20][Value]", ""))
      .pause(713.milliseconds)
      .exec(http("request_93")
        .post("/Criteria/SearchableCascadeDropDownListGridLookupPartial")

        .formParam("DXCallbackName", "PayPeriod_DDD_gv")
        .formParam("__DXCallbackArgument", """c0:KV|13;["600","601"];FR|1;0;GB|33;14|CUSTOMCALLBACK13|GLP_AC|3;600;;""")
        .formParam("PayPeriod$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;600&quot;,&quot;601&quot;],&quot;callbackState&quot;:&quot;hv2hfeExnsBj1SmNQ+vwVzvjv6PooWuUPpfXC8eD4eamqNiZC2D1iN/M+XkO8Vh3mTasDdevmHsJ4gc0ndegUt+ZkpqjVYI3x+1A9E2KP/6cAKg+jzmPV/rsfU296UQ99KQWOF7lOQmE8jWZpxH/VOdgvJTwCFV/Vl0wZBoiKHYwFzinxyuDbP2EZZUSOf/66wj0ifWT1fbMfdqF0/9j6+hjgmuca9HvCbJY5+6zBP1/DUZIXtOETsahKVoDL+874PL6STMM6SigvXOooYrRPcQW+17vOqATo0DSj5goQv+jEeijAEunW2pbG4RiEYdZdoF29YbfIHezXwyMhLPK8DqZOYfD30ybYHjtgyncSYOeBGjZezL1d6QxW+50X+P3O1LE3uteLNAhzm85DN6K1dxDALsGXyx1nLZUfWYn33vrWBT3oa4pKxDHzVY+Td7BJ67B+1dCd87opKM6yJAzGXHrjQSw07xkvY0FNdJB9qm++G99WnoGnvdA/QI6Oc+1M9iO1rQaIqhWPzG2ZK+NVudqWjByFup95jIMqsxTBQs=&quot;,&quot;focusedRow&quot;:0,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:&quot;600&quot;}")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol0", "")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol1", "phi")
        .formParam("DXMVCEditorsValues", """{"LeavePostedListingType":"L","PayPeriod_DDD_gv_DXFREditorcol0":null,"PayPeriod_DDD_gv_DXFREditorcol1":"phi","PayPeriod":["600"],"EmployeeStatus":["A","L","I"],"RequestId":null,"Leave_DDD_gv_DXFREditorcol1":null,"Leave_DDD_gv_DXFREditorcol2":null,"Leave_DDD_gv_DXFREditorcol3":null,"Leave":null,"LeaveType_DDD_gv_DXFREditorcol0":null,"LeaveType_DDD_gv_DXFREditorcol1":null,"LeaveType_DDD_gv_DXFREditorcol2":null,"LeaveType":null,"LeaveDateFrom":null,"LeaveDateTo":null,"SubmissionDateFrom":null,"SubmissionDateTo":null,"PostingDateFrom":null,"PostingDateTo":null,"ddlOrganizationLevel_DDD_L":[],"ddlOrganizationLevel":null,"Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null}""")
        .formParam("PayPeriod$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:[&quot;600&quot;]}")
        .formParam("PayPeriod", "Please Select")
        .formParam("criteriaObjectInString", """{"Type":"CascadeComboBox","Name":"PayPeriod","Label":"PayPeriod","DefaultValue":null,"DefaultDate":null,"DefaultDateRangeFrom":null,"DefaultDateRangeTo":null,"Value":null,"GroupId":1,"IsRequired":false,"Group":null,"DropDownListProperties":null,"CascadeDropDownListProperties":{"TextField":"PAY_PERIOD_DESCRIPTION","ValueField":"ID","FilterField":null,"FilterFieldList":[],"DatasourceName":"CurrentMonthPayPeriods","DisplayFormatString":"{0}","SourceFrom":0,"DefaultIndex":null,"ColumnsList":[{"Name":"PAY_PERIOD_DESCRIPTION","Label":"Description","Width":250,"ColumnDisplayFormatString":null},{"Name":"COMPANY.LOCATION_CODE","Label":"Company","Width":100,"ColumnDisplayFormatString":null}],"CascadeControl":"LeaveType","LoadOnDemand":false,"SelectAllMode":false,"DefaultSelectAll":false,"IsMultiSelection":false,"SelectedIndexChangedJsCallBack2":null},"ChildDropDownListProperties":null,"CheckListProperties":null,"DefaultIndex":null,"IsAddLabel":false,"IsChecked":false,"Caption":null,"CheckedChangedJsCallBack":null,"MaxLength":0,"DisplayFormatString":null,"NullText":null,"ShowIncrementButtons":false,"Page":0,"CascadeControl":null,"ValueFieldDelimiter":null,"DownloadBy":null,"InitJsCallBack":null,"MultiValueDelimiter":null,"DefaultValueTo":null}""")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "LeavePostedListingType")
        .formParam("CustomSearchParameters[0][Value]", "L")
        .formParam("CustomSearchParameters[1][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[1][Value]", "600")
        .formParam("CustomSearchParameters[2][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[2][Value]", "A,L,I")
        .formParam("CustomSearchParameters[3][Name]", "RequestId")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "Leave")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "LeaveType")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LeaveDateFrom")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LeaveDateTo")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "SubmissionDateFrom")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "SubmissionDateTo")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "PostingDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "PostingDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "Location")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[13][Value]", "|||||||||")
        .formParam("CustomSearchParameters[14][Name]", "Category")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "Grade")
        .formParam("CustomSearchParameters[15][Value]", "")
        .formParam("CustomSearchParameters[16][Name]", "Employee")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[17][Value]", "")
        .formParam("CustomSearchParameters[18][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[18][Value]", "")
        .formParam("CustomSearchParameters[19][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[19][Value]", "")
        .formParam("CustomSearchParameters[20][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[20][Value]", ""))
      .exec(http("request_94")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_95")
        .post("/LeavePostedListing/CascadeComboBoxDisplay")

        .formParam("objectLabel", "PayPeriod")
        .formParam("objectSelectedIds[]", "600")
        .formParam("isAllSelected", "false"))
      .exec(http("request_96")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_97")
        .post("/LeavePostedListing/GetCascadeChildDropdown")

        .formParam("criteriaObject[Type]", "CascadeComboBox")
        .formParam("criteriaObject[Name]", "LeaveType")
        .formParam("criteriaObject[Label]", "LeaveType")
        .formParam("criteriaObject[GroupId]", "3")
        .formParam("criteriaObject[IsRequired]", "False")
        .formParam("criteriaObject[CascadeDropDownListProperties][TextField]", "LEAVE_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ValueField]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][ParameterName]", "PayPeriod")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterField]", "LOCATION_ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][FilterOperator]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceName]", "CurrentMonthPayPeriods")
        .formParam("criteriaObject[CascadeDropDownListProperties][FilterFieldList][0][TargetDatasourceProperty]", "ID")
        .formParam("criteriaObject[CascadeDropDownListProperties][DatasourceName]", "Leaves")
        .formParam("criteriaObject[CascadeDropDownListProperties][DisplayFormatString]", "{0} - {1}")
        .formParam("criteriaObject[CascadeDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Name]", "LOCATION_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Label]", "Company")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][Width]", "90")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Name]", "LEAVE_CODE")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Label]", "Code")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][Width]", "100")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Name]", "LEAVE_DESCRIPTION")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Label]", "Description")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][Width]", "250")
        .formParam("criteriaObject[CascadeDropDownListProperties][ColumnsList][2][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[CascadeDropDownListProperties][LoadOnDemand]", "false")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectAllMode]", "false")
        .formParam("criteriaObject[CascadeDropDownListProperties][DefaultSelectAll]", "false")
        .formParam("criteriaObject[CascadeDropDownListProperties][IsMultiSelection]", "false")
        .formParam("criteriaObject[CascadeDropDownListProperties][SelectedIndexChangedJsCallBack2]", "")
        .formParam("ParentId", "")
        .formParam("CustomSearchParameters[0][Name]", "LeavePostedListingType")
        .formParam("CustomSearchParameters[0][Value]", "L")
        .formParam("CustomSearchParameters[1][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[1][Value]", "600")
        .formParam("CustomSearchParameters[2][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[2][Value]", "A,L,I")
        .formParam("CustomSearchParameters[3][Name]", "RequestId")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "Leave")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "LeaveType")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LeaveDateFrom")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LeaveDateTo")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "SubmissionDateFrom")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "SubmissionDateTo")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "PostingDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "PostingDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "Location")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[13][Value]", "|||||||||")
        .formParam("CustomSearchParameters[14][Name]", "Category")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "Grade")
        .formParam("CustomSearchParameters[15][Value]", "")
        .formParam("CustomSearchParameters[16][Name]", "Employee")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[17][Value]", "")
        .formParam("CustomSearchParameters[18][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[18][Value]", "")
        .formParam("CustomSearchParameters[19][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[19][Value]", "")
        .formParam("CustomSearchParameters[20][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[20][Value]", ""))
      .exec(http("request_98")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_99")
        .post("/LeavePostedListing/CascadeComboBoxDisplay")

        .formParam("objectLabel", "LeaveType")
        .formParam("isAllSelected", "false"))
      .pause(16)
      .exec(http("request_100")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_101")
        .post("/Criteria/RenderOrganizationUnitsPartial")

        .formParam("organizationLevel", "1")
        .formParam("criteriaObject[Type]", "OrganizationUnits")
        .formParam("criteriaObject[Name]", "Organization")
        .formParam("criteriaObject[Label]", "Organization")
        .formParam("criteriaObject[DefaultValue]", "")
        .formParam("criteriaObject[DefaultDate]", "")
        .formParam("criteriaObject[DefaultDateRangeFrom]", "")
        .formParam("criteriaObject[DefaultDateRangeTo]", "")
        .formParam("criteriaObject[Value]", "")
        .formParam("criteriaObject[GroupId]", "2")
        .formParam("criteriaObject[IsRequired]", "false")
        .formParam("criteriaObject[Group][Id]", "2")
        .formParam("criteriaObject[Group][Title]", "Optional Selection")
        .formParam("criteriaObject[DropDownListProperties][TextField]", "LOCATION_LABEL")
        .formParam("criteriaObject[DropDownListProperties][ValueField]", "LOCATION_LEVEL")
        .formParam("criteriaObject[DropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[DropDownListProperties][DatasourceName]", "OrganizationLevels")
        .formParam("criteriaObject[DropDownListProperties][DisplayFormatString]", "")
        .formParam("criteriaObject[DropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[DropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[DropDownListProperties][SelectedIndexChangedJsCallBack]", "")
        .formParam("criteriaObject[DropDownListProperties][ColumnsList]", "")
        .formParam("criteriaObject[DropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[DropDownListProperties][DefaultValues]", "")
        .formParam("criteriaObject[DropDownListProperties][LoadOnDemand]", "false")
        .formParam("criteriaObject[DropDownListProperties][SelectAllMode]", "false")
        .formParam("criteriaObject[DropDownListProperties][DefaultSelectAll]", "false")
        .formParam("criteriaObject[DropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[DropDownListProperties][DatasourceParameters]", "")
        .formParam("criteriaObject[DropDownListProperties][IsWrapText]", "true")
        .formParam("criteriaObject[CascadeDropDownListProperties]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][TextField]", "LOCATION_NAME")
        .formParam("criteriaObject[ChildDropDownListProperties][ValueField]", "LOCATION_CODE")
        .formParam("criteriaObject[ChildDropDownListProperties][FilterField]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][DatasourceName]", "AllEntityLocations")
        .formParam("criteriaObject[ChildDropDownListProperties][DisplayFormatString]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][SourceFrom]", "0")
        .formParam("criteriaObject[ChildDropDownListProperties][DefaultIndex]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][SelectedIndexChangedJsCallBack]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Name]", "LOCATION_CODE")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Label]", "Code")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][Width]", "120")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][0][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Name]", "LOCATION_NAME")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Label]", "Description")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][Width]", "350")
        .formParam("criteriaObject[ChildDropDownListProperties][ColumnsList][1][ColumnDisplayFormatString]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][IsMultiSelection]", "true")
        .formParam("criteriaObject[ChildDropDownListProperties][DefaultValues]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][LoadOnDemand]", "false")
        .formParam("criteriaObject[ChildDropDownListProperties][SelectAllMode]", "false")
        .formParam("criteriaObject[ChildDropDownListProperties][DefaultSelectAll]", "false")
        .formParam("criteriaObject[ChildDropDownListProperties][CascadeControl]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][DatasourceParameters]", "")
        .formParam("criteriaObject[ChildDropDownListProperties][IsWrapText]", "false")
        .formParam("criteriaObject[CheckListProperties]", "")
        .formParam("criteriaObject[DefaultIndex]", "")
        .formParam("criteriaObject[IsAddLabel]", "false")
        .formParam("criteriaObject[IsChecked]", "false")
        .formParam("criteriaObject[Caption]", "")
        .formParam("criteriaObject[CheckedChangedJsCallBack]", "")
        .formParam("criteriaObject[MaxLength]", "0")
        .formParam("criteriaObject[DisplayFormatString]", "")
        .formParam("criteriaObject[NullText]", "")
        .formParam("criteriaObject[ShowIncrementButtons]", "false")
        .formParam("criteriaObject[Page]", "0")
        .formParam("criteriaObject[CascadeControl]", "")
        .formParam("criteriaObject[ValueFieldDelimiter]", "")
        .formParam("criteriaObject[DownloadBy]", "")
        .formParam("criteriaObject[InitJsCallBack]", "")
        .formParam("criteriaObject[MultiValueDelimiter]", "")
        .formParam("criteriaObject[DefaultValueTo]", ""))
      .pause(2)
      .exec(http("request_102")
        .post("/Account/VerifyAccess")
      )
      .exec(http("request_103")
        .post("/Leave/LeavePostedListingGridViewPartial")

        .formParam("CustomSearchParameters[0][Name]", "LeavePostedListingType")
        .formParam("CustomSearchParameters[0][Value]", "L")
        .formParam("CustomSearchParameters[1][Name]", "PayPeriod")
        .formParam("CustomSearchParameters[1][Value]", "600")
        .formParam("CustomSearchParameters[2][Name]", "EmployeeStatus")
        .formParam("CustomSearchParameters[2][Value]", "A,L,I")
        .formParam("CustomSearchParameters[3][Name]", "RequestId")
        .formParam("CustomSearchParameters[3][Value]", "")
        .formParam("CustomSearchParameters[4][Name]", "Leave")
        .formParam("CustomSearchParameters[4][Value]", "")
        .formParam("CustomSearchParameters[5][Name]", "LeaveType")
        .formParam("CustomSearchParameters[5][Value]", "")
        .formParam("CustomSearchParameters[6][Name]", "LeaveDateFrom")
        .formParam("CustomSearchParameters[6][Value]", "")
        .formParam("CustomSearchParameters[7][Name]", "LeaveDateTo")
        .formParam("CustomSearchParameters[7][Value]", "")
        .formParam("CustomSearchParameters[8][Name]", "SubmissionDateFrom")
        .formParam("CustomSearchParameters[8][Value]", "")
        .formParam("CustomSearchParameters[9][Name]", "SubmissionDateTo")
        .formParam("CustomSearchParameters[9][Value]", "")
        .formParam("CustomSearchParameters[10][Name]", "PostingDateFrom")
        .formParam("CustomSearchParameters[10][Value]", "")
        .formParam("CustomSearchParameters[11][Name]", "PostingDateTo")
        .formParam("CustomSearchParameters[11][Value]", "")
        .formParam("CustomSearchParameters[12][Name]", "Location")
        .formParam("CustomSearchParameters[12][Value]", "")
        .formParam("CustomSearchParameters[13][Name]", "LevelRanges")
        .formParam("CustomSearchParameters[13][Value]", "|||||||||")
        .formParam("CustomSearchParameters[14][Name]", "Category")
        .formParam("CustomSearchParameters[14][Value]", "")
        .formParam("CustomSearchParameters[15][Name]", "Grade")
        .formParam("CustomSearchParameters[15][Value]", "")
        .formParam("CustomSearchParameters[16][Name]", "Employee")
        .formParam("CustomSearchParameters[16][Value]", "")
        .formParam("CustomSearchParameters[17][Name]", "HireDateFrom")
        .formParam("CustomSearchParameters[17][Value]", "")
        .formParam("CustomSearchParameters[18][Name]", "HireDateTo")
        .formParam("CustomSearchParameters[18][Value]", "")
        .formParam("CustomSearchParameters[19][Name]", "TerminationDateFrom")
        .formParam("CustomSearchParameters[19][Value]", "")
        .formParam("CustomSearchParameters[20][Name]", "TerminationDateTo")
        .formParam("CustomSearchParameters[20][Value]", ""))
      .pause(9)
      .exec(http("request_104")
        .post("/Master/ExportTo")

        .formParam("module", "LeavePostedListing")
        .formParam("XLS", "")
        .formParam("RangeSelection", "{&quot;collapsed&quot;:true}")
        .formParam("LeavePostedListingType", "0")
        .formParam("LeavePostedListingType$RB0", "C")
        .formParam("LeavePostedListingType$RB1", "U")
        .formParam("LeavePostedListingType$RB2", "U")
        .formParam("PayPeriod$State", "{&quot;rawValue&quot;:&quot;202103 - Month End Salary (PHI)&quot;,&quot;validationState&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:[&quot;600&quot;]}")
        .formParam("PayPeriod", "202103 - Month End Salary (PHI)")
        .formParam("PayPeriod$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:524:70:1:0:0:1:0:0:0&quot;}")
        .formParam("PayPeriod$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;1030&quot;,&quot;1031&quot;,&quot;347&quot;,&quot;834&quot;,&quot;796&quot;,&quot;872&quot;,&quot;637&quot;,&quot;910&quot;,&quot;720&quot;,&quot;758&quot;,&quot;348&quot;,&quot;987&quot;,&quot;835&quot;,&quot;676&quot;,&quot;312&quot;,&quot;446&quot;,&quot;600&quot;,&quot;484&quot;,&quot;797&quot;,&quot;523&quot;,&quot;949&quot;,&quot;873&quot;,&quot;562&quot;,&quot;638&quot;,&quot;911&quot;,&quot;721&quot;,&quot;759&quot;,&quot;988&quot;,&quot;677&quot;,&quot;313&quot;,&quot;447&quot;,&quot;601&quot;,&quot;485&quot;,&quot;524&quot;,&quot;950&quot;,&quot;563&quot;],&quot;callbackState&quot;:&quot;rRPZu8GsZysOCnLZhvgElZF+qQ8gkStr2SbuChbYpYcoKD00kdlb3VRFzkh+/pkooq65RUJq8/buBVx44HwHmkY2f84nimIXe+FmRaHgwBg5TLSPf0AFTEgEdIY9ReNRcwUqQiHZlL4yXpSm7VMEFQ+GwZnniWE2SX29QbOEqMX18R1lJME3fw7ejH20FfN/+5yb+/rhPEe5uQ1glM+XLlER6xUOdngksLQKZcDjhjXIllC8/IvQcTrt2xAFCzjIP0E02YO/RnNatVIiyG88kI2JqjC2IC8a6up4hcJnyiycf4qImulJY9ck0tAPtTmsSKbC+8O7UiW4NAS4aZCUdoBey8Um3BRGInJdHV8mgoHqQ22K6DbOTirlIJtK7bZVklsmdpHQX/q+GZdNeEFi1WNRcRH8XfGTHUlE0RU3VRnXlSWOXvbElWAAoDrFmczTKU2V94ZfWadMJuFoAQ02bctaVPeQy7hWPXFozcbPEUM=&quot;,&quot;focusedRow&quot;:16,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:&quot;600&quot;}")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol0", "")
        .formParam("PayPeriod$DDD$gv$DXFREditorcol1", "")
        .formParam("EmployeeStatus$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("EmployeeStatus", "1|01|11|2")
        .formParam("EmployeeStatus$RB0", "C")
        .formParam("EmployeeStatus$RB1", "C")
        .formParam("EmployeeStatus$RB2", "C")
        .formParam("RequestId", "")
        .formParam("Leave$State", "{&quot;selectedKeyValues&quot;:null}")
        .formParam("Leave", "Please Select")
        .formParam("Leave$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Leave$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;185&quot;,&quot;186&quot;,&quot;165&quot;,&quot;168&quot;,&quot;169&quot;,&quot;170&quot;,&quot;171&quot;,&quot;167&quot;,&quot;172&quot;,&quot;173&quot;,&quot;166&quot;,&quot;187&quot;,&quot;174&quot;,&quot;175&quot;,&quot;184&quot;,&quot;177&quot;,&quot;178&quot;,&quot;176&quot;,&quot;179&quot;,&quot;180&quot;,&quot;181&quot;,&quot;182&quot;,&quot;183&quot;,&quot;232&quot;,&quot;238&quot;,&quot;237&quot;,&quot;241&quot;,&quot;234&quot;,&quot;233&quot;,&quot;240&quot;,&quot;235&quot;,&quot;242&quot;,&quot;244&quot;,&quot;245&quot;,&quot;246&quot;,&quot;236&quot;,&quot;239&quot;,&quot;243&quot;,&quot;64&quot;,&quot;70&quot;,&quot;71&quot;,&quot;73&quot;,&quot;74&quot;,&quot;68&quot;,&quot;76&quot;,&quot;72&quot;,&quot;67&quot;,&quot;65&quot;,&quot;66&quot;,&quot;69&quot;,&quot;75&quot;,&quot;392&quot;,&quot;373&quot;,&quot;379&quot;,&quot;380&quot;,&quot;382&quot;,&quot;385&quot;,&quot;375&quot;,&quot;374&quot;,&quot;378&quot;,&quot;377&quot;,&quot;390&quot;,&quot;391&quot;,&quot;387&quot;,&quot;388&quot;,&quot;376&quot;,&quot;381&quot;,&quot;389&quot;,&quot;386&quot;,&quot;393&quot;,&quot;383&quot;,&quot;384&quot;,&quot;413&quot;,&quot;394&quot;,&quot;400&quot;,&quot;401&quot;,&quot;403&quot;,&quot;406&quot;,&quot;396&quot;,&quot;395&quot;,&quot;399&quot;,&quot;398&quot;,&quot;411&quot;,&quot;412&quot;,&quot;408&quot;,&quot;409&quot;,&quot;397&quot;,&quot;402&quot;,&quot;410&quot;,&quot;407&quot;,&quot;414&quot;,&quot;404&quot;,&quot;405&quot;,&quot;295&quot;,&quot;301&quot;,&quot;302&quot;,&quot;304&quot;,&quot;305&quot;,&quot;299&quot;,&quot;307&quot;],&quot;callbackState&quot;:&quot;iuufzBKjHwMcQDL2By/zwDHHTFlCuf10pRr/jbEM+WPx2r7hNdKnQo/uhSfGj2Uvx0NXGDDDSkgI/J62w0MnB0x4tNoE5SaEDMFHaI4ci9SAIfBJHYGAFIUrjxqlEytcQs5jWStxyw4mlLnPXd8Krq6J8GpJJuobwjaSXM7JFK+llB2h58PqyNDQnpsrCk8svXlBtu02YIJNwMXefhz9B75dznH8LNTF72N1AJcLXsCn9Tf1AdZ4ppQZIv5GQQ7iWls0Fvyh7JY4YxxGVWi1r3aIgQhKA08pISCpMZ3le/pYBmXTeV/RatrZFqVTWhRwNdNkKHwjzfKOowAOhwEycS5yVaeAnDOPMxIgIHGyMVz5oLGNDpV05mR4XHimjXItLAoyulqfP0tWtiIto4c1YU/Nw+NohmOOPULCtIFFnzNPD/zrBAe7u06KnvgtoGhkj46ONvkfWSskN4bowuef+akrzZxPizzcst8oSBmfE9UII8hSoJU2m6vMxKt/VR8yJ1GHbH0L9DVH9HUn+/hMsntRpsu3Hd1trEA0Fc6MoqQ8hEHspsyZrEKZLWHPWSBMh0i1ihsAZNvlBS/rubrfvBgi6m3Um5syLVtIEKk/boWRgnsSzrTrrzeAdIKy6++J&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("Leave$DDD$gv$DXFREditorcol1", "")
        .formParam("Leave$DDD$gv$DXFREditorcol2", "")
        .formParam("Leave$DDD$gv$DXFREditorcol3", "")
        .formParam("LeavePopupState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("LeaveType$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;selectedKeyValues&quot;:null}")
        .formParam("LeaveType", "Please Select")
        .formParam("LeaveType$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("LeaveType$DDD$gv", "{&quot;scrollState&quot;:null,&quot;keys&quot;:[&quot;131&quot;,&quot;134&quot;,&quot;133&quot;,&quot;132&quot;,&quot;136&quot;,&quot;137&quot;,&quot;141&quot;,&quot;135&quot;,&quot;139&quot;,&quot;138&quot;,&quot;140&quot;,&quot;142&quot;],&quot;callbackState&quot;:&quot;R5AaHOZFSBRR17mq6LV4ISet8uGwxM3q21lOvfCLI9kfwjqyzDcCzchhDpjdNtLY0/TQE/mU5uzdFOTRKAxxNb/6Z5kbPVxIZP0qdBjt47wyTyK7nr0+KG0zuQYSijXFkgvNTd74OgI7jBYILvUnGE2rLb3JLvu+j3EbEyyFz2V7rTegvRRI+8PrPSHduJzviT7LFgSgtZOaE+bAhVmvQ2OFHPs/flRDIxtw407B9m3cz2cxO+y42xrQrAqH9FudFjNJznDX6OgZQ/lhfx0d48UKlGcNKwzPL4L6yQPW9ne3Ek7XuzRT7Ob+i4MPT3RCQZLpgqE9quwdWllGYEr7qN3DCTho6ipnVJf70dxrzuTIjZ3ZD5MMRUt5gQfjQzCUZtMy+nM++kud8LBYKmzJZllwVWkrKo9rSm2wsMAcm8wbrD/loH7cAOxZxi7cYKZT&quot;,&quot;focusedRow&quot;:-1,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("LeaveType$DDD$gv$DXFREditorcol0", "")
        .formParam("LeaveType$DDD$gv$DXFREditorcol1", "")
        .formParam("LeaveType$DDD$gv$DXFREditorcol2", "")
        .formParam("LeaveDateFrom$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("LeaveDateFrom", "From")
        .formParam("LeaveDateFrom$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("LeaveDateFrom$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("LeaveDateFrom$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("LeaveDateTo$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("LeaveDateTo", "To")
        .formParam("LeaveDateTo$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("LeaveDateTo$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("LeaveDateTo$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("SubmissionDateFrom$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("SubmissionDateFrom", "From")
        .formParam("SubmissionDateFrom$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("SubmissionDateFrom$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("SubmissionDateFrom$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("SubmissionDateTo$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("SubmissionDateTo", "To")
        .formParam("SubmissionDateTo$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("SubmissionDateTo$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("SubmissionDateTo$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("PostingDateFrom$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("PostingDateFrom", "From")
        .formParam("PostingDateFrom$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("PostingDateFrom$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("PostingDateFrom$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("PostingDateTo$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("PostingDateTo", "To")
        .formParam("PostingDateTo$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("PostingDateTo$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("PostingDateTo$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("ddlOrganizationLevel$State", "{&quot;rawValue&quot;:&quot;Company&quot;}")
        .formParam("ddlOrganizationLevel_VI", "1")
        .formParam("ddlOrganizationLevel", "Company")
        .formParam("ddlOrganizationLevel$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:96:386:1:280:142:1:0:0:0&quot;}")
        .formParam("ddlOrganizationLevel$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("ddlOrganizationLevel$DDD$L", "1")
        .formParam("ddlChildOrganization$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;keyValue&quot;:&quot;&quot;}")
        .formParam("ddlChildOrganization", "Select Organization")
        .formParam("ddlChildOrganization$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Organization$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("Organization", "")
        .formParam("OrgChartPopupState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Category$State", "{&quot;selectedKeyValues&quot;:null}")
        .formParam("Category", "Please Select")
        .formParam("Category$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Category$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;ADMN&quot;,&quot;ALLH&quot;,&quot;CLIN&quot;,&quot;MEDI&quot;,&quot;NA&quot;,&quot;NURS&quot;,&quot;STUD&quot;],&quot;callbackState&quot;:&quot;T3hR69sD/MK1MFDj5xJ3ryp0EJyMcOHQEV/yKnNqWQX3pgSZHWTT9bY1jXmIPNgR9jBOoXW8Ff6KfEeQyzkZs8SfvtItmACAIMKWrWQ+aemVlMZvPsdwi3Rrw66L2S3aWhgw9vUt1Gt77/V5hk5JuOlTTj7jPjXCHBy8rPtUQrf1iqUahNEzSPcTOfJlDqdsu1DbMST397suM2AB5n7ZbGD49dfeXgd6iRJKL0tQPGGGQRvRBlJUYX7ZK8HDhIMxQZHRLC8E8i0Nr4Us5oAaJCAhhNQKzNV+NCCK8SW52lA3Xw+3yyCH563BYbG1UEBkzbwHuQG4zuajDQ+7FGzHtG0X80i+0EOgtSKy0r2tIZFAQGw8XAfYJB2JgPNDJpLKlMDrdtypuwTdqNnty29NuHUG2THO4DOvlRHAjb6bmwVdMRR+Hkv/D1kbOKw3LkS87m8dkc+unBYgNjO5v6+Ing==&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("Category$DDD$gv$DXFREditorcol1", "")
        .formParam("CategoryPopupState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Grade$State", "{&quot;selectedKeyValues&quot;:null}")
        .formParam("Grade", "Please Select")
        .formParam("Grade$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Grade$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;1&quot;,&quot;2&quot;,&quot;2A&quot;,&quot;2B&quot;,&quot;3A&quot;,&quot;3B&quot;,&quot;4A&quot;,&quot;4AII&quot;,&quot;4A3&quot;,&quot;4B&quot;,&quot;4C&quot;,&quot;4D&quot;,&quot;4E&quot;,&quot;5A&quot;,&quot;5B&quot;,&quot;5C&quot;,&quot;6A&quot;,&quot;6B&quot;,&quot;6C&quot;,&quot;6D&quot;,&quot;6E&quot;,&quot;7A&quot;,&quot;7B&quot;,&quot;7C&quot;,&quot;7D&quot;,&quot;7E&quot;,&quot;7F&quot;,&quot;7G&quot;,&quot;7I&quot;,&quot;A&quot;,&quot;5&quot;,&quot;N14&quot;,&quot;JG8&quot;,&quot;JG9&quot;,&quot;N02&quot;,&quot;N01&quot;,&quot;N10&quot;,&quot;JG12&quot;,&quot;G12&quot;,&quot;B&quot;,&quot;C1&quot;,&quot;C2&quot;,&quot;C3&quot;,&quot;C4&quot;,&quot;GM12&quot;,&quot;10&quot;,&quot;N15&quot;,&quot;11&quot;,&quot;N16&quot;,&quot;E1&quot;,&quot;AG&quot;,&quot;E2&quot;,&quot;SM&quot;,&quot;M&quot;,&quot;E3&quot;,&quot;E4&quot;,&quot;NE&quot;,&quot;E5&quot;,&quot;E6&quot;,&quot;JG6&quot;,&quot;EXAN&quot;,&quot;EXAH&quot;,&quot;EXCS&quot;,&quot;EXDO&quot;,&quot;EXNU&quot;,&quot;G1&quot;,&quot;G10&quot;,&quot;G2&quot;,&quot;G3&quot;,&quot;G4&quot;,&quot;G5&quot;,&quot;G6&quot;,&quot;G7&quot;,&quot;G8&quot;,&quot;G9&quot;,&quot;N05&quot;,&quot;JG14&quot;,&quot;G14&quot;,&quot;M1&quot;,&quot;M2&quot;,&quot;M3&quot;,&quot;4&quot;,&quot;JG10&quot;,&quot;MG1&quot;,&quot;MG2&quot;,&quot;MG3&quot;,&quot;MG4&quot;,&quot;8&quot;,&quot;JG2&quot;,&quot;NEAN&quot;,&quot;NEAH&quot;,&quot;NECS&quot;,&quot;NENU&quot;,&quot;NA&quot;,&quot;N12&quot;,&quot;N11&quot;,&quot;O1&quot;,&quot;O2&quot;,&quot;O3&quot;,&quot;JG5&quot;],&quot;callbackState&quot;:&quot;Xoh6zKMEy6UX/oI1tbj1EIO7x6etzfRwn0pI5YYSGKqC5NMb9sQKDKzcOGq/5mzVt2hyGcT2qaidvqgYV2aTD7FeYNOwy6yzV/DmQEFryXSUDzQwVCcniFI87kR7L1QWFN5mmPsz978VClu2NN0lVwLk0KkT82KoHZ+NkfsRf4QPGP2DTKbA6u96M70nwWSPRkBSy9TZO9fI/eEI/d9iint/En81Gg/ym11CGosF6Wu6c3HwGyjRgFxiJEvEVyI6lttZ0iwJ26UHvOm4B+dFAwzpHJ4JnM4Ir5UjXPSlQHqAX0xlu2reA7yDPrSFT0G38B7V7aoFwrWrR6gR9AyJaT3tQOWkhsmSJSx4S1TZ38gfiBIoQsOoDHLIo1w5OrIp9jHLiA2iH3p4azxQMrtluRtG6yKH93HclzrQnkUK8DqQ0FjAi0msloRcyavpt9zS9Y/QklvqxisPI1VM8TJBYid3wzL6/F+p22bGnS5JfLYZN5WdEb1iDequeYPpSGXgSQsyu6nreydhEYDXorH45eF3n895d6jB54KSlMSOHY1puXgy63Xf3LLP4tbRG9rLmtkTUVnb8JyIKhY4ks51PXyNRIZ/H35uiEArr6btM0M=&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("Grade$DDD$gv$DXFREditorcol1", "")
        .formParam("GradePopupState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Employee$State", "{&quot;selectedKeyValues&quot;:null}")
        .formParam("Employee", "Please Select")
        .formParam("Employee$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("Employee$DDD$gv", "{&quot;focusedRow&quot;:-1,&quot;keys&quot;:[&quot;2802_KK000001_ARC&quot;,&quot;8745_KK000002_ARC&quot;,&quot;8746_KK000004_ARC&quot;,&quot;8747_KK000006_ARC&quot;,&quot;8748_KK000009_ARC&quot;,&quot;8749_KK000012_ARC&quot;,&quot;8750_KK000013_ARC&quot;,&quot;8751_KK000015_ARC&quot;,&quot;8744_KK000016_ARC&quot;,&quot;8752_KK000017_ARC&quot;,&quot;8754_KK000019_ARC&quot;,&quot;8753_KK000021_ARC&quot;,&quot;9039_KK000022_ARC&quot;,&quot;9580_KK000024_ARC&quot;,&quot;9718_KK000025_ARC&quot;,&quot;9364_KK000026_ARC&quot;,&quot;9365_KK000027_ARC&quot;,&quot;10230_KK000028_ARC&quot;,&quot;5646_R000088_GKK&quot;,&quot;6379_R000091_GKK&quot;,&quot;5660_R000112_GKK&quot;,&quot;10761_R000117_GKK&quot;,&quot;5590_R000119_GKK&quot;,&quot;5591_R000121_GKK&quot;,&quot;5592_R000122_GKK&quot;,&quot;6380_R000123_GKK&quot;,&quot;5593_R000126_GKK&quot;,&quot;5594_R000127_GKK&quot;,&quot;5595_R000130_GKK&quot;,&quot;5596_R000131_GKK&quot;,&quot;5597_R000132_GKK&quot;,&quot;6381_R000133_GKK&quot;,&quot;8743_R000134_GKK&quot;,&quot;2557_R000135_GKK&quot;,&quot;5611_R000137_GKK&quot;,&quot;5612_R000138_GKK&quot;,&quot;2558_R000139_GKK&quot;,&quot;5613_R000140_GKK&quot;,&quot;5614_R000142_GKK&quot;,&quot;5615_R000143_GKK&quot;,&quot;5616_R000144_GKK&quot;,&quot;5617_R000145_GKK&quot;,&quot;5618_R000148_GKK&quot;,&quot;5619_R000149_GKK&quot;,&quot;5620_R000151_GKK&quot;,&quot;5621_R000152_GKK&quot;,&quot;5622_R000153_GKK&quot;,&quot;5623_R000154_GKK&quot;,&quot;6382_R000155_GKK&quot;,&quot;5637_R000169_GKK&quot;,&quot;5840_R000178_GKK&quot;,&quot;5836_R000182_GKK&quot;,&quot;11015_R000183_GKK&quot;,&quot;6383_R000184_GKK&quot;,&quot;5589_R000186_GKK&quot;,&quot;5837_R000187_GKK&quot;,&quot;5838_R000189_GKK&quot;,&quot;6400_R000190_GKK&quot;,&quot;5839_R000191_GKK&quot;,&quot;6401_R000196_GKK&quot;,&quot;5862_R000197_GKK&quot;,&quot;5863_R000203_GKK&quot;,&quot;6402_R000204_GKK&quot;,&quot;5864_R000206_GKK&quot;,&quot;5865_R000207_GKK&quot;,&quot;5866_R000208_GKK&quot;,&quot;5665_R000213_GKK&quot;,&quot;6403_R000215_GKK&quot;,&quot;5666_R000217_GKK&quot;,&quot;5867_R000218_GKK&quot;,&quot;6404_R000219_GKK&quot;,&quot;5868_R000221_GKK&quot;,&quot;5869_R000224_GKK&quot;,&quot;5720_R000231_GKK&quot;,&quot;6405_R000238_GKK&quot;,&quot;5798_R000241_GKK&quot;,&quot;5787_R000246_GKK&quot;,&quot;5783_R000248_GKK&quot;,&quot;5782_R000251_GKK&quot;,&quot;5780_R000253_GKK&quot;,&quot;5679_R000256_GKK&quot;,&quot;5781_R000262_GKK&quot;,&quot;5784_R000264_GKK&quot;,&quot;10829_R000265_GKK&quot;,&quot;5785_R000267_GKK&quot;,&quot;5786_R000268_GKK&quot;,&quot;5641_R000270_GKK&quot;,&quot;5642_R000272_GKK&quot;,&quot;5640_R000273_GKK&quot;,&quot;5639_R000275_GKK&quot;,&quot;5577_R000287_GKK&quot;,&quot;5578_R000290_GKK&quot;,&quot;5580_R000293_GKK&quot;,&quot;6064_R000294_GKK&quot;,&quot;6065_R000302_GKK&quot;,&quot;5606_R000303_GKK&quot;,&quot;5607_R000304_GKK&quot;,&quot;5628_R000305_GKK&quot;,&quot;5629_R000310_GKK&quot;,&quot;6027_R000317_GKK&quot;],&quot;callbackState&quot;:&quot;pNU6bzCQCqK2wKM8TSG/LvboJ1Hux91axb/A7VMOldBDuWUDkCR/8u5DZiwnMetW/eU42bMhw8yUfbNUgXEnmhsYXApajjRhzDFO3VHVmQ39K7Lsc3149JLWe7RB7CU8FTGv5uudWTDT4U57yeqRejPmwMJ6J7t/tPQ22viWh6FXeXgUVROMdObCCwlEweiRRNxBTWBKRSHqXx3j3BAxcVnM+AlMMYs9YZMtOsovhlsy+rSLGeZNxqakP3TMABSu9RcPkGPpar729qdy8jO4uvSbP+3ZXcH7xQTEUt2l46bjUceMzDbygy8/MuCIyc5l3xGd3zm3wtlMBRT1qkWXGNaYkLH9XrMCEsKdPFFOABnc8jkCcxNcEFgI6CYALx5w48uibVbUbmv5ZLRRWsdrd0hM4kbT8Xgxlyx8SvTeGSACPAb/qCJOz+SEjaLsAXf1V1mnuPbJXhxiAu/cQJstj5KIMYDGJPO0t9DXHTaom4+f1nme7q+QRTUIDXsXf1d87wzBRZHHFAe6bD7c1Yjk5vHRLg/bKJvStqamZ4llMi/yLdT5cuJ0dmTDtW7VWHLVSZE/NWNFgesMHsHdM5odbH6UjZzX1tqBW8joXtVWWDqmDhovl7XPcquoYtufVo+oRdnHzeq3kWXtF0NV3neVz1nmmtezn8kqIW9mpldaWIg=&quot;,&quot;lastMultiSelectIndex&quot;:-1,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;,&quot;focusedKey&quot;:null}")
        .formParam("Employee$DDD$gv$DXFREditorcol1", "")
        .formParam("Employee$DDD$gv$DXFREditorcol2", "")
        .formParam("Employee$DDD$gv$DXFREditorcol3", "")
        .formParam("EmployeePopupState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("HireDateFrom$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("HireDateFrom", "From")
        .formParam("HireDateFrom$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("HireDateFrom$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("HireDateFrom$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("HireDateTo$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("HireDateTo", "To")
        .formParam("HireDateTo$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("HireDateTo$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("HireDateTo$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("TerminationDateFrom$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("TerminationDateFrom", "From")
        .formParam("TerminationDateFrom$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("TerminationDateFrom$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("TerminationDateFrom$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("TerminationDateTo$State", "{&quot;rawValue&quot;:&quot;N&quot;}")
        .formParam("TerminationDateTo", "To")
        .formParam("TerminationDateTo$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("TerminationDateTo$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("TerminationDateTo$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing", "{&quot;batchEditClientModifiedValues&quot;:{&quot;ClientState&quot;:{&quot;InsertedIndices&quot;:[],&quot;InsertedValues&quot;:{},&quot;UpdatedValues&quot;:{},&quot;DeletedKeys&quot;:[]},&quot;EditState&quot;:{&quot;insertedRowValues&quot;:{},&quot;modifiedRowValues&quot;:{},&quot;deletedRowKeys&quot;:[]}},&quot;keys&quot;:[&quot;122178&quot;,&quot;122179&quot;],&quot;callbackState&quot;:&quot;1Hb6DMY8dfLfPjNQdQ3Al4ZavG/3NLVzDhTCXPJcviPegCfVbQDA+TQrK4y++dENuk9I8Bsy6wAdk850nQEGhK1YWUpSMl6UZbDDuDUvOhk23GmuAIDl8fTdnpPwmK66MyR5yDNprbDRDiLFnaDzcEVEKdftJ25w7u/B/kaoaizXZPMkLo6ASivj59yHk9S7adQFT+lhNt0yZsgYO0kq9jOXU9xmS2bHq8yPM3APOweH9vwLcinitRZeiGVwj63QFvZKn/kNAw5XSepF4pBT01XA4m5YaeBJp2bVfNFqlgCk56dtTd55VkGeNnmRhifBjccWNYftHsRiA+bn7w7GxSKYZmp+6w0WHVdpcnNZhB20T2Ie9l4Gc95amfazD5MhVoib5nLtBAXFsuB9dEp0LHwjhR9QjpZruIWiCipNl9RgcDgmFxk6lU1suJcpHtQ1BlgriWAPGiVtomf9QUBHwKKyLH+vx1me7Zgy7nRuKloUfp9aabYn7JAVwo5R5FKRBr0Exa2NEnowz9GY5lAqude3hmc3EZgdQB8xi1oEBiLNVhnCbF26k22M3CxOLDTr&quot;,&quot;scrollState&quot;:null,&quot;selection&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor1$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor1", "")
        .formParam("gvLeavePostedListing$DXEditor2$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor2", "")
        .formParam("gvLeavePostedListing$DXEditor3$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor3", "")
        .formParam("gvLeavePostedListing$DXEditor4$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor4", "")
        .formParam("gvLeavePostedListing$DXEditor5$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor5", "")
        .formParam("gvLeavePostedListing$DXEditor6$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor6", "")
        .formParam("gvLeavePostedListing$DXEditor6$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor6$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvLeavePostedListing$DXEditor6$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor7$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor7", "")
        .formParam("gvLeavePostedListing$DXEditor7$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor7$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvLeavePostedListing$DXEditor7$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor8$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing_DXEditor8_VI", "")
        .formParam("gvLeavePostedListing$DXEditor8", "")
        .formParam("gvLeavePostedListing$DXEditor8$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor8$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor8$DDD$L", "")
        .formParam("gvLeavePostedListing$DXEditor9$State", "{&quot;rawValue&quot;:&quot;&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor9", "")
        .formParam("gvLeavePostedListing$DXEditor10$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor10", "")
        .formParam("gvLeavePostedListing$DXEditor10$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor10$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvLeavePostedListing$DXEditor10$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor11$State", "{&quot;rawValue&quot;:&quot;N&quot;,&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor11", "")
        .formParam("gvLeavePostedListing$DXEditor11$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor11$DDD$C", "{&quot;visibleDate&quot;:&quot;06/10/2021&quot;,&quot;initialVisibleDate&quot;:&quot;06/10/2021&quot;,&quot;selectedDates&quot;:[]}")
        .formParam("gvLeavePostedListing$DXEditor11$DDD$C$FNPState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor12$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing_DXEditor12_VI", "")
        .formParam("gvLeavePostedListing$DXEditor12", "")
        .formParam("gvLeavePostedListing$DXEditor12$DDDState", "{&quot;windowsState&quot;:&quot;0:0:-1:0:0:0:-10000:-10000:1:0:0:0&quot;}")
        .formParam("gvLeavePostedListing$DXEditor12$DDD$L$State", "{&quot;CustomCallback&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor12$DDD$L", "")
        .formParam("gvLeavePostedListing$DXEditor13$State", "{&quot;validationState&quot;:&quot;&quot;}")
        .formParam("gvLeavePostedListing$DXEditor13", "")
        .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
        .formParam("DXCss", "/Content/css/root?v=Y-cRE08jNAR0IkYEwKTDpwfzJ2kuWuiVp8Nt6e1lBRg1,0_2312,1_50,1_53,1_51,0_2317,0_5685,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css")
        .formParam("DXMVCEditorsValues", """{"LeavePostedListingType":"L","PayPeriod_DDD_gv_DXFREditorcol0":null,"PayPeriod_DDD_gv_DXFREditorcol1":null,"PayPeriod":["600"],"EmployeeStatus":["A","L","I"],"RequestId":null,"Leave_DDD_gv_DXFREditorcol1":null,"Leave_DDD_gv_DXFREditorcol2":null,"Leave_DDD_gv_DXFREditorcol3":null,"Leave":null,"LeaveType_DDD_gv_DXFREditorcol0":null,"LeaveType_DDD_gv_DXFREditorcol1":null,"LeaveType_DDD_gv_DXFREditorcol2":null,"LeaveType":null,"LeaveDateFrom":null,"LeaveDateTo":null,"SubmissionDateFrom":null,"SubmissionDateTo":null,"PostingDateFrom":null,"PostingDateTo":null,"ddlOrganizationLevel_DDD_L":["1"],"ddlOrganizationLevel":"1","Organization":[],"ddlChildOrganization":null,"Category_DDD_gv_DXFREditorcol1":null,"Category":null,"Grade_DDD_gv_DXFREditorcol1":null,"Grade":null,"Employee_DDD_gv_DXFREditorcol1":null,"Employee_DDD_gv_DXFREditorcol2":null,"Employee_DDD_gv_DXFREditorcol3":null,"Employee":null,"HireDateFrom":null,"HireDateTo":null,"TerminationDateFrom":null,"TerminationDateTo":null,"gvLeavePostedListing_DXEditor1":null,"gvLeavePostedListing_DXEditor2":null,"gvLeavePostedListing_DXEditor3":null,"gvLeavePostedListing_DXEditor4":null,"gvLeavePostedListing_DXEditor5":null,"gvLeavePostedListing_DXEditor6":null,"gvLeavePostedListing_DXEditor7":null,"gvLeavePostedListing_DXEditor8_DDD_L":[],"gvLeavePostedListing_DXEditor8":null,"gvLeavePostedListing_DXEditor9":null,"gvLeavePostedListing_DXEditor10":null,"gvLeavePostedListing_DXEditor11":null,"gvLeavePostedListing_DXEditor12_DDD_L":[],"gvLeavePostedListing_DXEditor12":null,"gvLeavePostedListing_DXEditor13":null}"""))
      .pause(19)
  }

  def logout = {

    exec(http("Logout Submission")
      .post("/Account/LogOff")

      .formParam("__RequestVerificationToken", "${__RequestVerificationToken2}")
      .formParam("DXScript", "1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_270,1_286,1_289,1_183,17_42,17_3,1_285,1_188,17_8,1_297,1_192,17_10,1_287,1_194,1_193,17_11,1_208,1_216,1_301,1_253,1_234,1_246,1_302,1_221,17_12,1_296,1_295,1_278,17_41,1_189,1_222,1_290,1_288,1_195,1_255,1_262,1_261,1_254,1_251,1_258,1_252,1_260,1_257,1_256,1_247,1_243,1_241,1_250,1_249,1_248,1_245,1_244,1_259,1_240,1_237,1_238,1_239,1_242,17_15,17_17,1_271,1_272,17_19,1_273,1_274,17_20,17_21,1_223,17_14,1_276,17_24,17_28,1_280,17_25,1_293,17_27,1_291,1_294,17_32,1_298,17_36,17_40,1_197,17_1,1_207,1_235,17_16,6_18,6_16,6_15,6_14,6_17,17_39,1_212,1_196,17_0,1_198,17_2,1_199,17_4,1_200,1_201,1_202,1_204,1_218,1_205,17_7,1_211,17_23,1_206,17_9,1_275,1_214,1_215,17_22,1_213,1_217,17_38,1_219,1_232,1_233,1_231,17_5,1_191,1_284,18_36,18_38,18_33,18_42,18_37,18_35,17_31,1_203,1_283,9_54,9_55,24_379,24_389,9_57,9_56,17_44,9_45,9_47,9_46,17_30,9_51,9_48,9_31,17_29,9_50,9_41,9_53,9_52,9_49")
      .formParam("DXCss", "/Content/css/root?v=Y-cRE08jNAR0IkYEwKTDpwfzJ2kuWuiVp8Nt6e1lBRg1,0_2312,1_50,1_53,1_51,0_2317,0_5685,1_40,1_17,0_2214,1_16,0_2219,0_2221,0_2225,1_18,1_4,0_2279,6_3,0_2283,0_2186,0_2190,0_2257,18_3,18_11,18_7,0_2261,0_2313,1_34,24_359,24_364,24_360,9_19,9_15,9_12,0_2338,9_1,0_2342,9_4,1_7,/Content/ExecutiveDashboard/ExecutiveDashboardBundle?v=K3bp7bOUCg7jvMi3yCOp8VvRDHaxkZJNkgNJYDsPeIA1,/Content/ExecutiveDashboardBundle?v=yudLVP8cmmFF7pYfIl5_OmdH-W3uaCGxdSLyC-jbYQo1,/Content/notifications.css")
      .check(status.is(302)))
      .exec(http("Login After Logout")
        .get("/Account/Login")
      )
      .exec(http("request_107")
        .get("/bundles/jquery?v=BOadP4NdMhfEAxOx_qgeCESNgZMYYlRzghlNUzq6K-Y1")
      )
      .exec(http("request_108")
        .get("/DXR.axd?r=1_58-N3Vxm")
      )
      .exec(http("request_109")
        .get("/DXR.axd?r=1_17,0_2214,1_50,1_53,1_51,1_16,0_2219,0_2312,0_2317-O3Vxm")
      )
      .exec(http("request_110")
        .get("/Content/css?v=w9USDPGryprQSMA62T1giyRXrtqAIG-BphxyQY0Qw_w1")
      )
      .exec(http("request_111")
        .get("/DXR.axd?r=1_303,1_210,1_184,1_220,1_187,1_181,1_279,1_292,1_208,1_216,1_212,1_189,1_222,17_42,1_297,1_215,1_207,1_289,1_205,17_7,1_287,1_211,17_23,1_197,17_1-N3Vxm")
      )
      .exec(http("request_112")
        .get("/Content/fonts/icomoon.ttf?5vru0d")
      )
      .exec(http("request_113")
        .get("/Content/Images/bg-login.jpg?V=03")
      )

  }


}
